### ISSUE TITLE
AttributeError: 'module' object has no attribute 'CERT_CERT_REQUIRED'

### ISSUE THREAD

**Issue by Miserlou** [boto/botocore#1007]
I'm not sure why, but this suddenly started happening:

```
Traceback (most recent call last):
  File "zappa/cli.py", line 1010, in handle
    sys.exit(cli.handle())
  File "zappa/cli.py", line 166, in handle
    self.deploy()
  File "zappa/cli.py", line 230, in deploy
    self.zappa.create_iam_roles()
  File "/Users/rjones/Projects/Zappa/lib/Zappa/zappa/zappa.py", line 924, in create_iam_roles
    self.credentials_arn = role.arn
  File "/Users/rjones/Projects/Zappa/baby_flask/env/lib/python2.7/site-packages/boto3/resources/factory.py", line 339, in property_loader
    self.load()
  File "/Users/rjones/Projects/Zappa/baby_flask/env/lib/python2.7/site-packages/boto3/resources/factory.py", line 505, in do_action
    response = action(self, *args, **kwargs)
  File "/Users/rjones/Projects/Zappa/baby_flask/env/lib/python2.7/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(**params)
  File "/Users/rjones/Projects/Zappa/baby_flask/env/lib/python2.7/site-packages/botocore/client.py", line 159, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/rjones/Projects/Zappa/baby_flask/env/lib/python2.7/site-packages/botocore/client.py", line 483, in _make_api_call
    operation_model, request_dict)
  File "/Users/rjones/Projects/Zappa/baby_flask/env/lib/python2.7/site-packages/botocore/endpoint.py", line 117, in make_request
    return self._send_request(request_dict, operation_model)
  File "/Users/rjones/Projects/Zappa/baby_flask/env/lib/python2.7/site-packages/botocore/endpoint.py", line 146, in _send_request
    success_response, exception):
  File "/Users/rjones/Projects/Zappa/baby_flask/env/lib/python2.7/site-packages/botocore/endpoint.py", line 219, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "/Users/rjones/Projects/Zappa/baby_flask/env/lib/python2.7/site-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "/Users/rjones/Projects/Zappa/baby_flask/env/lib/python2.7/site-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "/Users/rjones/Projects/Zappa/baby_flask/env/lib/python2.7/site-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/Users/rjones/Projects/Zappa/baby_flask/env/lib/python2.7/site-packages/botocore/retryhandler.py", line 251, in __call__
    caught_exception)
  File "/Users/rjones/Projects/Zappa/baby_flask/env/lib/python2.7/site-packages/botocore/retryhandler.py", line 266, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/Users/rjones/Projects/Zappa/baby_flask/env/lib/python2.7/site-packages/botocore/retryhandler.py", line 314, in __call__
    caught_exception)
  File "/Users/rjones/Projects/Zappa/baby_flask/env/lib/python2.7/site-packages/botocore/retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "/Users/rjones/Projects/Zappa/baby_flask/env/lib/python2.7/site-packages/botocore/retryhandler.py", line 356, in _check_caught_exception
    raise caught_exception
AttributeError: 'module' object has no attribute 'CERT_CERT_REQUIRED'
```

Latest botocore, latest boto3, latest urllib3, python 2.7.10, OSX. Code hasn't touched, seems to still work on Travis but not on my local system. I'm not sure what has changed to cause this.

**Comment by Miserlou** [comment]
This was my fault. It's a weird one though: I had a file called 'ssl.py' in my project. This caused a conflict with something in boto3 or botocore. I don't really see how that namespace conflict can happen - any chance you can look into that?

**Comment by jamesls** [comment]
From what I can tell, the call stack is:

* botocore.endpoint.Endpoint._get_response
* requests.session.send
* requests.adapters.<*>.send()
* urllib3.connectionpool.urlopen
* urllib3.connectionpool._make_request
* urllib3.connectionpool._validate_conn
* urllib3.connection.<*>.connect
* urllib3.util.ssl_.resolve_cert_reqs

The code that's triggering the attr error is [here](https://github.com/shazow/urllib3/blob/master/urllib3/util/ssl_.py#L199):

```
    if isinstance(candidate, str):
        res = getattr(ssl, candidate, None)
        if res is None:
            res = getattr(ssl, 'CERT_' + candidate)
        return res
```

urllib3 has a couple of checks that catch the `ImportError` you would normally get if you try to pull in something from a module that's missing expected attributes.  This unfortunately masks the original error.  You can see that [here](https://github.com/shazow/urllib3/blob/master/urllib3/util/ssl_.py#L41-L46):

```
try:  # Test for SSL features
    import ssl
    from ssl import wrap_socket, CERT_NONE, PROTOCOL_SSLv23
    from ssl import HAS_SNI  # Has SNI?
except ImportError:
    pass
```

So as a result of executing that block above the `ssl` attribute exists because of your local `ssl.py` file in your project so the first import works), but the `getattr(ssl, ...)` from `urllib3.util.ssl_.resolve_cert_reqs` raises an `AttributeError`.

Let me know if there's anything else I can do to help.

**Comment by Miserlou** [comment]
Wow, thanks for diving into that one!

I think I can close this because it's not a botocore related issue. I'll notify upstream.
