### ISSUE TITLE
pkg_resources.DistributionNotFound: botocore

### ISSUE THREAD

**Issue by rocky4bmw** [boto/botocore#1012]
I am following steps are per link for setting up ElasticAlert
http://elastalert.readthedocs.io/en/latest/elastalert_status.html#metadata

OS: Redhat 6.7
Python 2.6

When I executing below command I get botocore error can you please check and help me on this

#elastalert-create-index
Traceback (most recent call last):
  File "/usr/bin/elastalert-create-index", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.6/site-packages/distribute-0.6.14-py2.6.egg/pkg_resources.py", line 2671, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.6/site-packages/distribute-0.6.14-py2.6.egg/pkg_resources.py", line 654, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.6/site-packages/distribute-0.6.14-py2.6.egg/pkg_resources.py", line 552, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: botocore

**Comment by jamesls** [comment]
You'll need to `pip install botocore` to make sure it's installed.  Looks like you have an open issue over at https://github.com/Yelp/elastalert/issues/677.  Let's track that issue over there.
