### ISSUE TITLE
S3 put_object with SSEKMSKeyId on Google App Engine fails

### ISSUE THREAD

**Issue by jordaengraham-wf** [boto/botocore#1030]
Unable to put objects to S3 from GAE with ServerSideEncryption enabled using KMSKeyId, this same code works from a local environment and also from lambda functions. 

Calls to put or get objects from S3 using `ServerSideEncryption=AES256`  or without any encryption work fine from GAE

``` python
from botocore.session import Session
from botocore.client import Config

AWSACCESSKEYID = '<ACCESS_KEY_ID>'
AWSSECRETACCESSKEY = '<SECRET_KEY>'
BUCKET = '<MY_BUCKET>'
REGION = 'us-east-1'
KMSKEYID = '<MY_KMS_KEY_ID>'

s3_client = Session().create_client(
    service_name='s3',
    aws_access_key_id=AWSACCESSKEYID,
    aws_secret_access_key=AWSSECRETACCESSKEY,
    region_name=REGION,
    config=Config(signature_version='s3v4'),
    use_ssl=True,
)

key = 'S3_object_key'
content = 'Som content'
response = s3_client.put_object(
    Bucket=BUCKET,
    Key=key,
    Body=content,
    ServerSideEncryption='aws:kms',
    SSEKMSKeyId=KMSKEYID)
print response

<Response [400]>
{
    'ResponseMetadata': {
        'HTTPStatusCode': 400, 
        'RetryAttempts': 0, 
        'HostId': '<host_id>',
        'RequestId': '3BE469E6E1F71791', 
        'HTTPHeaders': {
            'x-amz-id-2': '<host_id>',
            'server': 'AmazonS3', 
            'transfer-encoding': 'chunked', 
            'connection': 'close', 
            'x-amz-request-id': '3BE469E6E1F71791', 
            'date': 'Tue, 13 Sep 2016 21:14:45 GMT', 
            'content-type': 'application/xml'
        }
    }, 
    'Error': {
        'ArgumentValue': 'null', 
        'Code': 'InvalidArgument', 
        'ArgumentName': 'x-amz-server-side-encryption', 
        'Message': 'Requests specifying Server Side Encryption with AWS KMS managed keys must be made over a secure connection.'
    }
}
Traceback (most recent call last):
  File "/botocore/client.py", line 159, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/botocore/client.py", line 500, in _make_api_call
    raise ClientError(parsed_response, operation_name)
ClientError: An error occurred (InvalidArgument) when calling the PutObject operation: Requests specifying Server Side Encryption with AWS KMS managed keys must be made over a secure connection.
```
We first attempted to use `boto3` to create an S3 client however it uses multiprocessing which GAE doesn't allow. If there is a way we could bypass the multiprocessing to be able to use boto3 to connect to s3 and be able to put/get objects with SSEKMSKeyIds that would also work for us.

**Comment by jordaengraham-wf** [comment]
@jamesls Thoughts?

**Comment by jordaengraham-wf** [comment]
or @kyleknap Any Thoughts?

**Comment by jordaengraham-wf** [comment]
I was able to find a work-around to get the request out to S3. Using the s3_client's `generate_presigned_post` I was then able to use `requests` to do a post to s3. I believe the issue with just using `s3_client.put_object` is that GAE intercepts the outgoing request and forces it to use `HTTP` instead of the required `HTTPS`. Using `requests` the request still gets intercepted but it's turned into a `urlfetch` call which allows `HTTPS`. The Working code is:
```python
# Create some of the various supported conditions.
conditions = [
    {'x-amz-server-side-encryption': 'aws:kms'},
    {'x-amz-server-side-encryption-aws-kms-key-id': '<aws_kms_key_id>'}
]

# Retrieve the args for the presigned post.
fields = {
    'x-amz-server-side-encryption': 'aws:kms',
    'x-amz-server-side-encryption-aws-kms-key-id': '<aws_kms_key_id?'
}

s3_client = Session().create_client(
    service_name='s3',
    use_ssl=True,
    aws_access_key_id='<AWS_ACCESS_KEY_ID>',
    aws_secret_access_key='<AWS_SECRET_ACCESS_KEY>',
    config=Config(signature_version='s3v4')
)
post_args = s3_client.generate_presigned_post(
    '<my-bucket>', '<key>', Fields=fields, Conditions=conditions)

# Make sure that the form can be posted successfully.
files = {'file': ('<key>', '<content>')}

response = requests.post(
    post_args['url'], data=post_args['fields'], files=files)
assert response.status_code == 204
```
