### ISSUE TITLE
A Potential bug with logs.generate_presigned_url

### ISSUE THREAD

**Issue by EricDHS** [boto/botocore#1045]
Repro steps: 
1. import boto3
2. logs = boto3.client('logs')
3. logs.generate_presigned_url('get_log_events', Params = { 'logGroupName': 'faf', 'logStreamName': 'fff' }, ExpiresIn = 86400)

Get error:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/botocore/signers.py", line 517, in generate_presigned_url
    operation_name=operation_name)
  File "/Library/Python/2.7/site-packages/botocore/signers.py", line 253, in generate_presigned_url
    'presign-url', expires_in)
  File "/Library/Python/2.7/site-packages/botocore/signers.py", line 147, in sign
    auth.add_auth(request)
  File "/Library/Python/2.7/site-packages/botocore/auth.py", line 319, in add_auth
    self._modify_request_before_signing(request)
  File "/Library/Python/2.7/site-packages/botocore/auth.py", line 462, in _modify_request_before_signing
    query_dict.update(request.data)
ValueError: dictionary update sequence element #0 has length 1; 2 is required

Put debug in /Library/Python/2.7/site-packages/botocore/auth.py at line 454 like below:

print request.data
print type(request.data)

Found request.data is str, which should be dict. 

Therefore, I assume it is a bug with logs.generate_presigned_url, which is params has been translated into str in the transaction and it should keep as dict. 

ENV: 
python: Python 2.7.10 (default, Oct 23 2015, 19:19:21)
boto3 (1.4.0)
botocore (1.4.49)

Please help me check if it is bug in boto or something wrong of my usage. 
Thanks in advance.

**Comment by kyleknap** [comment]
Hmm this looks similar to this issue: https://github.com/boto/boto3/issues/754. Similar to my response in that linked issue, there is no guarantee the service supports presigned urls even if you got passed the runtime error. I am going to close this issue as a duplicate. Let's move the conversation over to the linked issue to better track this issue.
