### ISSUE TITLE
Route53 param validation for PageSize

### ISSUE THREAD

**Issue by manuel-sousa** [boto/botocore#1063]
This might be related to #243 

From cli:
aws route53  list-resource-record-sets --page-size 15 --hosted-zone-id 123

Parameter validation failed:
Invalid type for parameter MaxItems, value: 1, type: <class 'int'>, valid types: <class 'str'>

Tested this in ubuntu 16.10, before and after updateing boto,  and latest amazon ami.

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/awscli/clidriver.py", line 186, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/usr/lib/python2.7/dist-packages/awscli/clidriver.py", line 379, in **call**
    return command_table[parsed_args.operation](remaining, parsed_globals)
  File "/usr/lib/python2.7/dist-packages/awscli/clidriver.py", line 549, in **call**
    call_parameters, parsed_globals)
  File "/usr/lib/python2.7/dist-packages/awscli/clidriver.py", line 674, in invoke
    self._display_response(operation_name, response, parsed_globals)
  File "/usr/lib/python2.7/dist-packages/awscli/clidriver.py", line 683, in _display_response
    formatter(command_name, response)
  File "/usr/lib/python2.7/dist-packages/awscli/formatter.py", line 68, in __call__
    response_data = response.build_full_result()
  File "/usr/lib/python2.7/dist-packages/botocore/paginate.py", line 290, in build_full_result
    for response in self:
  File "/usr/lib/python2.7/dist-packages/botocore/paginate.py", line 102, in **iter**
    response = self._make_request(current_kwargs)
  File "/usr/lib/python2.7/dist-packages/botocore/paginate.py", line 174, in _make_request
    return self._method(**current_kwargs)
  File "/usr/lib/python2.7/dist-packages/botocore/client.py", line 159, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/lib/python2.7/dist-packages/botocore/client.py", line 470, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/usr/lib/python2.7/dist-packages/botocore/client.py", line 523, in _convert_to_request_dict
    api_params, operation_model)
  File "/usr/lib/python2.7/dist-packages/botocore/validate.py", line 270, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
ParamValidationError: Parameter validation failed:
Invalid type for parameter MaxItems, value: 15, type: <type 'int'>, valid types: <type 'basestring'>
2016-10-28 12:10:42,279 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255

Parameter validation failed:
Invalid type for parameter MaxItems, value: 15, type: <type 'int'>, valid types: <type 'basestring'>

**Comment by JordonPhillips** [comment]
What version(s) of the cli are producing this?

**Comment by manuel-sousa** [comment]
On ubuntu (16.10) using updated botocore: aws-cli/1.10.1 Python/3.5.2 Linux/4.4.0-45-generic botocore/1.4.67
On aws ami (2016.09) using standard packages : aws-cli/1.10.56 Python/2.7.12 Linux/4.4.23-31.51.amzn1.x86_64 botocore/1.4.46

**Comment by joguSD** [comment]
I'm able to confirm that this is still an issue.
The cli is converting the input to an integer but the actual operation in botocore is expecting a string.

**Comment by ayla-bala** [comment]
Still re-producible!

Skipped passing 'MaxItems' and 'PageSize'. It worked by applying default value '100'
