### ISSUE TITLE
regression in build_full_result pagination on waf service from 1.4.70 -> 72

### ISSUE THREAD

**Issue by kapilt** [boto/botocore#1084]
```
placebo.pill: DEBUG: attaching to session: Session(region_name='us-east-1')
placebo.pill: DEBUG: datapath: /Users/kapil/projects/custodian/tests/data/placebo/test_waf_query
c7n.cache: DEBUG: Disabling cache
custodian.output: DEBUG: Storing output with <DirectoryOutput to dir:/var/folders/52/yrmwhtyj5g71jnlcn_f57gbhmbv2lk/T/tmpyWX9mp/waftest>
custodian.policy: INFO: Running policy waftest resource: waf region:us-east-1 c7n:0.8.20.2
placebo.pill: DEBUG: _create_client
placebo.pill: DEBUG: _make_request: waf.ListWebACLs
placebo.pill: DEBUG: load_response: waf.ListWebACLs
placebo.pill: DEBUG: get_next_file_path: waf.ListWebACLs
placebo.pill: DEBUG: load_responses: /Users/ylv522/projects/custodian/tests/data/placebo/test_waf_query/waf.ListWebACLs_1.json
placebo.pill: DEBUG: _make_request: waf.ListWebACLs
placebo.pill: DEBUG: load_response: waf.ListWebACLs
placebo.pill: DEBUG: get_next_file_path: waf.ListWebACLs
placebo.pill: DEBUG: load_responses: /Users/ylv522/projects/custodian/tests/data/placebo/test_waf_query/waf.ListWebACLs_1.json
custodian.output: ERROR: Error while executing policy
Traceback (most recent call last):
  File "/Users/kapil/projects/custodian/c7n/policy.py", line 167, in run
    resources = self.policy.resource_manager.resources()
  File "/Users/kapil/projects/custodian/c7n/query.py", line 161, in resources
    resources = self.query.filter(self.resource_type, **query)
  File "/Users/kapil/projects/custodian/c7n/query.py", line 62, in filter
    data = results.build_full_result()
  File "/Users/kapil/projects/custodian/lib/python2.7/site-packages/botocore/paginate.py", line 290, in build_full_result
    for response in self:
  File "/Users/kapil/projects/custodian/lib/python2.7/site-packages/botocore/paginate.py", line 143, in __iter__
    raise PaginationError(message=message)
PaginationError: Error during pagination: The same next token was received twice: {u'NextMarker': u'1ebe0b46-0fd2-4e07-a74c-27bf25adc0bf'}
```

**Comment by kapilt** [comment]
looks like waf service was returning pagination markers even though there wasn't anything thing to paginate.

**Comment by JordonPhillips** [comment]
This might require a service change

**Comment by stealthycoin** [comment]
To get some more context on this can you give me the version of boto3/python/botocore you are using and whatever part of the script you can that triggered this problem?

**Comment by kapilt** [comment]
doesn't seem to be a problem anymore, the issue was noted on nov 15th, versions py2.7.12  and latest botocore/boto versions at the time. using today's latest boto versions, and list-web-acls paginators and doing test recording with placebo, it all seems to be working fine, so fine to close. 

Versions
```
$ python --version
Python 2.7.13
$ pip freeze | grep boto
boto3==1.4.3
botocore==1.4.93
```
Explore

```
>>> import boto3
>>> import pprint
>>> client = boto3.client('waf')
>>> response = client.list_web_acls()
>>> pprint.pprint(response)
{u'NextMarker': u'1ebe0b46-0fd2-4e07-a74c-27bf25adc0bf',
 'ResponseMetadata': {'HTTPHeaders': {'content-length': '131',
                                      'content-type': 'application/x-amz-json-1.1',
                                      'date': 'Sat, 07 Jan 2017 19:13:07 GMT',
                                      'x-amzn-requestid': '528fb687-d50d-11e6-8ac4-61b0a2bb4cc3'},
                      'HTTPStatusCode': 200,
                      'RequestId': '528fb687-d50d-11e6-8ac4-61b0a2bb4cc3',
                      'RetryAttempts': 0},
 u'WebACLs': [{u'Name': u'test',
               u'WebACLId': u'1ebe0b46-0fd2-4e07-a74c-27bf25adc0bf'}]}

>>> p = client.get_paginator('list_web_acls')
>>> for i in p.paginate(): print i                                                                                                                            
... 
{u'NextMarker': u'1ebe0b46-0fd2-4e07-a74c-27bf25adc0bf', 'ResponseMetadata': {'RetryAttempts': 0, 'HTTPStatusCode': 200, 'RequestId': '81e3cdac-d50d-11e6-9046
-29c04bbde95a', 'HTTPHeaders': {'x-amzn-requestid': '81e3cdac-d50d-11e6-9046-29c04bbde95a', 'date': 'Sat, 07 Jan 2017 19:14:27 GMT', 'content-length': '131', 
'content-type': 'application/x-amz-json-1.1'}}, u'WebACLs': [{u'WebACLId': u'1ebe0b46-0fd2-4e07-a74c-27bf25adc0bf', u'Name': u'test'}]}
{'ResponseMetadata': {'RetryAttempts': 0, 'HTTPStatusCode': 200, 'RequestId': '81f61d2d-d50d-11e6-9046-29c04bbde95a', 'HTTPHeaders': {'x-amzn-requestid': '81f
61d2d-d50d-11e6-9046-29c04bbde95a', 'date': 'Sat, 07 Jan 2017 19:14:27 GMT', 'content-length': '14', 'content-type': 'application/x-amz-json-1.1'}}, u'WebACLs
': []}
```
