### ISSUE TITLE
Unicode issues with non-ascii chars in home path

### ISSUE THREAD

**Issue by alex88** [boto/botocore#1127]
I had to install aws-cli on a Turkish pc running windows 7 with the user's home folder called `İK` and I get this output

```
C:\Users\İK>aws
Traceback (most recent call last):
  File "aws", line 27, in <module>
  File "aws", line 23, in main
  File "awscli\clidriver.pyc", line 53, in main
  File "awscli\clidriver.pyc", line 61, in create_clidriver
  File "botocore\session.pyc", line 375, in full_config
  File "botocore\configloader.pyc", line 105, in load_config
  File "botocore\configloader.pyc", line 145, in raw_config_parse
  File "botocore\exceptions.pyc", line 27, in __init__
UnicodeDecodeError: 'ascii' codec can't decode byte 0xdd in position 9: ordinal not in range(128)
```

could it be something related to the user's folder name?

I've tried also with `--debug` but I've the same issue

**Comment by alex88** [comment]
Sorry wrong repo 😊
