### ISSUE TITLE
GetAtt VPC.Ipv6CidrBlocks. ERROR: The Value must evaluate to a String.

### ISSUE THREAD

**Issue by gunph1ld** [boto/botocore#1162]
MacOS Sierra
Python 2.7.12
Botocore 1.5.24

I faced a strange issue with cloudformation and trying to find out whether anyone has the same one.
I use quite simple template:
```
AWSTemplateFormatVersion: '2010-09-09'
Description: 'IPv6 TEST'
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 172.20.0.0/23
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default
      Tags:
        - Key: Test
          Value: true

  VPCIPv6:
    Type: AWS::EC2::VPCCidrBlock
    Properties:
      AmazonProvidedIpv6CidrBlock: true
      VpcId: !Ref VPC

Outputs:
  Ipv6CidrBlocks:
    Value: !GetAtt VPC.Ipv6CidrBlocks
```

debug:
```
2017-03-11 21:33:28,254 - MainThread - botocore.endpoint - DEBUG - Sending http request: <PreparedRequest [POST]>
2017-03-11 21:33:28,254 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - INFO - Starting new HTTPS connection (1): cloudformation.eu-west-1.amazonaws.com
2017-03-11 21:33:28,760 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - DEBUG - "POST / HTTP/1.1" 400 346
2017-03-11 21:33:28,764 - MainThread - botocore.parsers - DEBUG - Response headers: {'x-amzn-requestid': '387be7b3-0689-11e7-9dbf-89ec98b05d6c', 'date': 'Sat, 11 Mar 2017 18:33:27 GMT', 'content-length': '346', 'content-type': 'text/xml', 'connection': 'close'}
2017-03-11 21:33:28,764 - MainThread - botocore.parsers - DEBUG - Response body:
<ErrorResponse xmlns="http://cloudformation.amazonaws.com/doc/2010-05-15/">
  <Error>
    <Type>Sender</Type>
    <Code>ValidationError</Code>
    <Message>Template format error: The Value field of every Outputs member must evaluate to a String.</Message>
  </Error>
  <RequestId>387be7b3-0689-11e7-9dbf-89ec98b05d6c</RequestId>
</ErrorResponse>

2017-03-11 21:33:28,765 - MainThread - botocore.hooks - DEBUG - Event needs-retry.cloudformation.UpdateStack: calling handler <botocore.retryhandler.RetryHandler object at 0x109868310>
2017-03-11 21:33:28,766 - MainThread - botocore.retryhandler - DEBUG - No retry needed.
2017-03-11 21:33:28,767 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/awscli/clidriver.py", line 186, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/usr/local/lib/python2.7/site-packages/awscli/clidriver.py", line 381, in __call__
    return command_table[parsed_args.operation](remaining, parsed_globals)
  File "/usr/local/lib/python2.7/site-packages/awscli/clidriver.py", line 551, in __call__
    call_parameters, parsed_globals)
  File "/usr/local/lib/python2.7/site-packages/awscli/clidriver.py", line 675, in invoke
    **parameters)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 253, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 543, in _make_api_call
    raise error_class(parsed_response, operation_name)
ClientError: An error occurred (ValidationError) when calling the UpdateStack operation: Template format error: The Value field of every Outputs member must evaluate to a String.
2017-03-11 21:33:28,769 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255

An error occurred (ValidationError) when calling the UpdateStack operation: Template format error: The Value field of every Outputs member must evaluate to a String.
```

According to http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-getatt.html, it's possible to get att for `VPC.Ipv6CidrBlocks`
The question is why `Ipv6CidrBlocks` is not understandable by aws/boto/whatever ?
I will really appreciate any help, thanks.

**Comment by JordonPhillips** [comment]
I'm no yaml expert (or cloudformation for that matter), but it looks like your value for your ec2 tag is a boolean when it should be a string. Maybe try encapsulating it in quotes.

**Comment by gunph1ld** [comment]
this is a list, not a string
