### ISSUE TITLE
resourcegroupstaggingapi can_paginate() and get_paginator() should work for 'get_resources'

### ISSUE THREAD

**Issue by alfredgamulo** [boto/botocore#1218]
resourcegroupstaggingapi should be able to paginate for `get_resources`
```
Python 2.7.12 (default, Dec  5 2016, 18:35:15) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import boto3
>>> client = boto3.client('resourcegroupstaggingapi')
>>> client.can_paginate('get_resources')
False
>>> client.get_paginator('get_resources')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 612, in get_paginator
    raise OperationNotPageableError(operation_name=operation_name)
botocore.exceptions.OperationNotPageableError: Operation cannot be paginated: get_resources
```

**Comment by ranman166** [comment]
@alfredgamulo I am having this exact same issue. Did you come up with a solution? From the looks of it resourcegrouptaggingapi might do something different from other paginators, but I can't find clear documentation on how to do it.

**Comment by alfredgamulo** [comment]
@ranman166 This works now, have you updated your modules?

```
$ python
Python 2.7.13 (default, Apr  4 2017, 08:47:57) 
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import boto3
>>> client = boto3.client('resourcegroupstaggingapi')
>>> client.can_paginate('get_resources')
True
>>> client.get_paginator('get_resources')
<botocore.client.ResourceGroupsTaggingAPI.Paginator.GetResources object at 0x10d5426d0>
```

**Comment by ranman166** [comment]
Thanks for the quick reply, 

I'm using this for a lambda function, and I'm using the online environment.  I just assumed that they were updated. I'll check if they are and if they can be updated if not.

**Comment by ranman166** [comment]
Yeah, the console doesn't use the newest version of boto, so that was the issue. Zipping the file up works, Thanks!
