### ISSUE TITLE
AuthorizationHeaderMalformed error since upgrade to botocore 1.5.71

### ISSUE THREAD

**Issue by palewire** [boto/botocore#1225]
My TravisCI buildbot started throwing errors with the upgrade to the latest version. Is there something about how you're juggling the region name in the code that I need to adjust for?

```
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    execute_from_command_line(sys.argv)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/bigbuild/management/commands/publish.py", line 14, in handle
    super(Command, self).handle(*args, **options)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/bakery/management/commands/publish.py", line 121, in handle
    self.s3_obj_dict = self.get_bucket_file_list()
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/bakery/management/commands/publish.py", line 258, in get_bucket_file_list
    for page in page_iterator:
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/botocore/paginate.py", line 249, in __iter__
    response = self._make_request(current_kwargs)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/botocore/paginate.py", line 321, in _make_request
    return self._method(**current_kwargs)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/botocore/client.py", line 310, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/botocore/client.py", line 599, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AuthorizationHeaderMalformed) when calling the ListObjects operation: The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'us-west-1'
```

**Comment by kyleknap** [comment]
Would it be possible if you can provide a code snippet of what you are doing? Or provide debug logs from the build? You can enable debug logs by adding a call to `Session.set_debug_logger()`. I am not really able to tell for certain what is happening without these, but if I were to guess it may be related to defaulting to sigv4 for s3 as that was released in 1.5.71
