### ISSUE TITLE
AttributeError when first session created is in a subthread

### ISSUE THREAD

**Issue by selik** [boto/botocore#1227]
Using a ThreadPoolExecutor with a separate AWS session created for each thread, as per the recommendation (http://boto3.readthedocs.io/en/latest/guide/resources.html#multithreading-multiprocessing), I encountered a strange error that, if caught and suppressed, would no longer raise after the first time it was encountered.

```
def bucket_connect():
    session = boto3.Session(profile_name='bar')
    s3 = session.resource('s3')
    return s3.Bucket('baz')

def download(arg):
    bucket = bucket_connect()
    return download_one(bucket, arg)

results = []
with ThreadPoolExecutor(max_workers=len(args)) as pool:
    jobs = {pool.submit(download, x): x for x in args}
    for future in as_completed(jobs):
        try:
            results.append(future.result())
        except Exception as e:
            LOG.error(f'Error with {jobs[future]}')
            LOG.exception(e)

# Edited example: changed `max_workers` to `len(args)` to have 1 thread per arg.
```

The error was that the `six` module didn't have a `configparser`.

```
__main__    : ERROR    module 'botocore.vendored.six.moves' has no attribute 'configparser'
Traceback (most recent call last):
  File "grab.py", line 69, in download
    results.append(future.result())
  File "/Users/mike/miniconda/envs/foo/lib/python3.6/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "/Users/mike/miniconda/envs/foo/lib/python3.6/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
  File "/Users/mike/miniconda/envs/foo/lib/python3.6/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "grab.py", line 62, in download
    bucket = bucket_connect()
  File "grab.py", line 19, in bucket_connect
    session = boto3.Session(profile_name='bar')
  File "/Users/mike/miniconda/envs/foo/lib/python3.6/site-packages/boto3/session.py", line 80, in __init__
    self._setup_loader()
  File "/Users/mike/miniconda/envs/foo/lib/python3.6/site-packages/boto3/session.py", line 120, in _setup_loader
    self._loader = self._session.get_component('data_loader')
  File "/Users/mike/miniconda/envs/foo/lib/python3.6/site-packages/botocore/session.py", line 701, in get_component
    return self._components.get_component(name)
  File "/Users/mike/miniconda/envs/foo/lib/python3.6/site-packages/botocore/session.py", line 897, in get_component
    self._components[name] = factory()
  File "/Users/mike/miniconda/envs/foo/lib/python3.6/site-packages/botocore/session.py", line 181, in <lambda>
    lambda:  create_loader(self.get_config_variable('data_path')))
  File "/Users/mike/miniconda/envs/foo/lib/python3.6/site-packages/botocore/session.py", line 265, in get_config_variable
    elif self._found_in_config_file(methods, var_config):
  File "/Users/mike/miniconda/envs/foo/lib/python3.6/site-packages/botocore/session.py", line 286, in _found_in_config_file
    return var_config[0] in self.get_scoped_config()
  File "/Users/mike/miniconda/envs/foo/lib/python3.6/site-packages/botocore/session.py", line 348, in get_scoped_config
    profile_map = self._build_profile_map()
  File "/Users/mike/miniconda/envs/foo/lib/python3.6/site-packages/botocore/session.py", line 220, in _build_profile_map
    self._profile_map = self.full_config['profiles']
  File "/Users/mike/miniconda/envs/foo/lib/python3.6/site-packages/botocore/session.py", line 375, in full_config
    self._config = botocore.configloader.load_config(config_file)
  File "/Users/mike/miniconda/envs/foo/lib/python3.6/site-packages/botocore/configloader.py", line 106, in load_config
    parsed = raw_config_parse(config_filename)
  File "/Users/mike/miniconda/envs/foo/lib/python3.6/site-packages/botocore/configloader.py", line 147, in raw_config_parse
    cp = six.moves.configparser.RawConfigParser()
AttributeError: module 'botocore.vendored.six.moves' has no attribute 'configparser'
```

My solution was to simply create a session in the main thread before creating new sessions in the subthreads.

Python v3.6, Miniconda distribution.

Is there some sort of `import` cycle that's failing if I don't connect in the main thread?

**Comment by kyleknap** [comment]
We would have to do some further research as to why that may be happening. I have not seen that error before.

One question that I do have as we look into this is: Are you just using the threads to download an object from S3? I only ask this because while it is not recommended to share resource objects across threads, it is safe to share clients across threads. So something like this could potentially help you avoid the issue if you do not need to use the resource layer:
```python
def download(client day):
    bucket = bucket_connect()
    return download_one(bucket, arg)

results = []

session = boto3.Session(profile_name='bar')
client = session.client('s3')
with ThreadPoolExecutor(max_workers=20) as pool:
    jobs = {pool.submit(download, client, x): x for x in args}
    for future in as_completed(jobs):
        try:
            results.append(future.result())
        except Exception as e:
            LOG.error(f'Error with {jobs[future]}')
            LOG.exception(e)
```

**Comment by selik** [comment]
> using the threads to download an object

Yes.

BTW, I changed tactics to call ``aws s3 sync`` via ``subprocess`` and found the downloads much faster. Or it might have been some random fluctuation of internet speed. Some days I feel like a cargo cult programmer.

> share clients across threads

Your example shows the ``Session`` shared across threads, but the doc (http://boto3.readthedocs.io/en/latest/guide/resources.html#multithreading-multiprocessing) shows creating a new session per thread. Before I'd read the doc, I was sharing a session across threads and had not encountered the issue. Perhaps the solution is simply keeping a shared session?

**Comment by eruvanos** [comment]
Hi,
have the same issue, what I guess until now is a race condition in module six where moves is using a LazyModule.

**Comment by jtdoepke** [comment]
This is a known issue in six<1.9.0: https://github.com/benjaminp/six/issues/98
I've opened PR #1214 to upgrade the vendored version of six.

**Comment by joguSD** [comment]
Thanks for the pull request! I'll go ahead and close this issue for now. If anybody is still having this issue feel free to follow up!
