### ISSUE TITLE
Traceback when uploading an empty file using Bucket's upload_file method

### ISSUE THREAD

**Issue by tfoote** [boto/botocore#1266]
I'm uploading a directory which has some empty files as markers. However the upload_file method throws a backtrace. There's a similar issue on aws-cli: https://github.com/aws/aws-cli/issues/2403

It looks like this just needs some better range checking before seeking.

```
$ python3 run_test.py 
Uploading results for test: test_upload_20170817142448 from /tmp/output
Uploading /tmp/output/ros.bag to test_upload_20170817142448/ros.bag
Uploading /tmp/output/gazebo.log to test_upload_20170817142448/gazebo.log
Traceback (most recent call last):
  File "run_test.py", line 47, in <module>
    upload_to_s3(b, test_name, results_dir)
  File "run_test.py", line 14, in upload_to_s3
    bucket.upload_file(full_f, bucket_key)
  File "/usr/lib/python3/dist-packages/boto3/s3/inject.py", line 110, in bucket_upload_file
    ExtraArgs=ExtraArgs, Callback=Callback, Config=Config)
  File "/usr/lib/python3/dist-packages/boto3/s3/inject.py", line 71, in upload_file
    extra_args=ExtraArgs, callback=Callback)
  File "/usr/lib/python3/dist-packages/boto3/s3/transfer.py", line 629, in upload_file
    self._put_object(filename, bucket, key, callback, extra_args)
  File "/usr/lib/python3/dist-packages/boto3/s3/transfer.py", line 639, in _put_object
    **extra_args)
  File "/usr/lib/python3/dist-packages/botocore/client.py", line 251, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/lib/python3/dist-packages/botocore/client.py", line 526, in _make_api_call
    operation_model, request_dict)
  File "/usr/lib/python3/dist-packages/botocore/endpoint.py", line 141, in make_request
    return self._send_request(request_dict, operation_model)
  File "/usr/lib/python3/dist-packages/botocore/endpoint.py", line 166, in _send_request
    request = self.create_request(request_dict, operation_model)
  File "/usr/lib/python3/dist-packages/botocore/endpoint.py", line 151, in create_request
    prepared_request = self.prepare_request(request)
  File "/usr/lib/python3/dist-packages/botocore/endpoint.py", line 162, in prepare_request
    return request.prepare()
  File "/usr/lib/python3/dist-packages/botocore/awsrequest.py", line 369, in prepare
    p.prepare_body(self.data, self.files)
  File "/usr/lib/python3/dist-packages/botocore/awsrequest.py", line 440, in prepare_body
    data.seek(0, 2)
TypeError: seek() takes 2 positional arguments but 3 were given
```

I have a local workaround that doesn't call `upload_file` but just calls `put_object` instead that avoids the problem. 
```
            print('Uploading %s to %s' % (full_f, bucket_key))
            if os.stat(full_f).st_size:
                bucket.upload_file(full_f, bucket_key)
            else:
                print("Empty file fallback behavior")
                bucket.put_object(
                    Key=bucket_key,
                    Body=''
                )
```

```
$ python3 run_test.py 
Uploading results for test: test_upload_20170817144559 from /tmp/output
Uploading /tmp/output/ros.bag to test_upload_20170817144559/ros.bag
Uploading /tmp/output/gazebo.log to test_upload_20170817144559/gazebo.log
Empty file fallback behavior
Uploading /tmp/output/test_results/results1.xml to test_upload_20170817144559/results1.xml
Empty file fallback behavior
Uploading /tmp/output/test_results/results2.xml to test_upload_20170817144559/results2.xml
Empty file fallback behavior
```

**Comment by joguSD** [comment]
It's not a range issue, it's a difference in function signature. From what I've seen this issue only arises when the cli is installed via Ubuntu's packaging system. They remove our vendored version of `requests` and substitute their own version. This can cause issues like the one you're seeing. I'm not sure if there's much we can do about this as we don't control the packages in the Ubuntu repos. A work-around for now is to install the cli via pip and not the standard Ubuntu repos.

**Comment by tfoote** [comment]
I did have the awscli installed on my system but when I remove it I still have the same issue. Though it is possibly an issue with the version of requests available via ubuntu/debian. The pypi version of requests is much newer: https://pypi.python.org/pypi/requests 2.18.4 versus 2.9.1

Is there a minimum version with known compatibility of request? I can refile a ticket against debian/ubuntu.  

```
$ pip3 show requests
---
Metadata-Version: 1.1
Name: requests
Version: 2.9.1
Summary: Python HTTP for Humans.
Home-page: http://python-requests.org
Author: Kenneth Reitz
Author-email: me@kennethreitz.com
License: Apache 2.0
Location: /usr/lib/python3/dist-packages
Requires: 
Classifiers:
  Development Status :: 5 - Production/Stable
  Intended Audience :: Developers
  Natural Language :: English
  License :: OSI Approved :: Apache Software License
  Programming Language :: Python
  Programming Language :: Python :: 2.7
  Programming Language :: Python :: 3
  Programming Language :: Python :: 3.3
  Programming Language :: Python :: 3.4
  Programming Language :: Python :: 3.5
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
$ dpkg -l | grep boto
ii  python3-boto3                               1.2.2-2                                               all          Python interface to Amazon's Web Services - Python 3.x
ii  python3-botocore                            1.4.70-1~16.04.0                                      all          Low-level, data-driven core of boto 3 (Python 3)
$ dpkg -l | grep aws
$ dpkg -l | grep requests
ii  httping                                     2.4-1                                                 amd64        ping-like program for http-requests
ii  iputils-arping                              3:20121221-5ubuntu2                                   amd64        Tool to send ICMP echo requests to an ARP address
ii  liburl-dispatcher1:amd64                    0.1+16.04.20151110-0ubuntu2                           amd64        library for sending requests to the url dispatcher
ii  node-forever-agent                          0.5.1-1                                               all          HTTP agent supporting keep-alive requests - module for Node.js
ii  python-requests                             2.9.1-3                                               all          elegant and simple HTTP library for Python2, built for human beings
ii  python3-requests                            2.9.1-3                                               all          elegant and simple HTTP library for Python3, built for human beings
```

**Comment by joguSD** [comment]
We vendor requests, the system version shouldn't matter. Specifically, `botocore` vendors `requests`. It might be that if you only uninstall the cli, reinstalling via pip might still rely on your `boto3` and `botocore` installed from your distro repos.

**Comment by tfoote** [comment]
Thanks for the info. I've refiled it here: https://bugs.launchpad.net/ubuntu/+source/python-botocore/+bug/1711737
