### ISSUE TITLE
sdb.get_presigned_url() throws error

### ISSUE THREAD

**Issue by stephen-164** [boto/botocore#1344]
The get_presigned_url() method in boto3's simpledb client produces an error in botocore/auth.py:
```
Python 3.5.2 (default, Nov 23 2017, 16:37:01)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import botocore
>>> botocore.__version__
'1.8.17'
>>> import boto3
>>> boto3.__version__
'1.5.3'
>>> sdb = boto3.client('sdb')
>>> sdb.select(SelectExpression='SELECT * FROM `scratch-sdb` WHERE `author` = "Harry"')
{'ResponseMetadata': {'HTTPHeaders': {'transfer-encoding': 'chunked', 'vary': 'Accept-Encoding', 'connection': 'keep-alive', 'content-type': 'text/xml', 'server': 'Amazon SimpleDB', 'date': 'Wed, 20 Dec 2017 17:18:40 GMT'}, 'BoxUsage': '0.0000320033', 'RequestId': '05f490d9-e895-b3e9-dbfb-6cbcfe46a939', 'HTTPStatusCode': 200, 'RetryAttempts': 0}, 'Items': [{'Name': '123', 'Attributes': [{'Name': 'author', 'Value': 'Harry'}]}, {'Name': '2', 'Attributes': [{'Name': 'author', 'Value': 'Dick'}, {'Name': 'author', 'Value': 'Harry'}, {'Name': 'author', 'Value': 'Tom'}]}]}
>>> sdb.generate_presigned_url('select',{'SelectExpression':'SELECT * FROM `scratch-sdb` WHERE `author` = "Harry"'})
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/botocore/signers.py", line 146, in sign
    auth = self.get_auth_instance(**kwargs)
  File "/usr/local/lib/python3.5/dist-packages/botocore/signers.py", line 218, in get_auth_instance
    signature_version=signature_version)
botocore.exceptions.UnknownSignatureVersionError: Unknown Signature Version: v2-query.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/botocore/signers.py", line 584, in generate_presigned_url
    operation_name=operation_name)
  File "/usr/local/lib/python3.5/dist-packages/botocore/signers.py", line 264, in generate_presigned_url
    'presign-url', expires_in, signing_name)
  File "/usr/local/lib/python3.5/dist-packages/botocore/signers.py", line 150, in sign
    signature_version=signature_version)
botocore.exceptions.UnsupportedSignatureVersionError: Signature version is not supported: v2-query
>>>
```

Making actual queries seems to work fine, it's just the pre-signed url generation, which I wanted to use to access the `BoxUsage` metrics.

**Comment by joguSD** [comment]
Unfortunately we don't support generating presigned URLs for `sdb` at the moment. All boto3 clients have the `generate_presigned_url` method but support for services can be hit or miss. Marking as a feature request.
