### ISSUE TITLE
S3 put_object: AttributeError: 'bytearray' object has no attribute 'seek'

### ISSUE THREAD

**Issue by r-l-x** [boto/botocore#1359]
Looking at our server log, I can see that we did get the following error at least once when working with AWS S3:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/botocore/awsrequest.py", line 426, in reset_stream
    self.body.seek(0)
AttributeError: 'bytearray' object has no attribute 'seek'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
[...]
  File "/var/css/server/storage.py", line 334, in <lambda>
  File "/usr/local/lib/python3.5/dist-packages/botocore/client.py", line 312, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/botocore/client.py", line 588, in _make_api_call
    operation_model, request_dict)
  File "/usr/local/lib/python3.5/dist-packages/botocore/endpoint.py", line 141, in make_request
    return self._send_request(request_dict, operation_model)
  File "/usr/local/lib/python3.5/dist-packages/botocore/endpoint.py", line 176, in _send_request
    request.reset_stream()
  File "/usr/local/lib/python3.5/dist-packages/botocore/awsrequest.py", line 429, in reset_stream
    raise UnseekableStreamError(stream_object=self.body)
botocore.exceptions.UnseekableStreamError: Need to rewind the stream bytearray(b'[...]'), but stream is not seekable.
```
Our code is as follow, with data being a bytearray:
```
self.client.put_object(Bucket=self.container, Key=object_dest, Body=data))
```
Looking at the code, I can see that there is an exception for str and byte types so that they are not reset:
https://github.com/pexip/os-python-botocore/blob/master/botocore/awsrequest.py#L415-L417

I think it would make sense to include bytearray to the exception.

Would you accept a PR ?

our environment is the following :
* linux
* python 3.5
* botocore 1.6.6

**Comment by kyleknap** [comment]
I do not think I would be opposed to adding it to the check. Out of curiosity if you do add a case for it in the if statement, does the body get successfully uploaded?
