### ISSUE TITLE
issue when trying to assume role using latest cli version 1.7.48

### ISSUE THREAD

**Issue by sailaxman** [boto/botocore#1360]
Traceback (most recent call last):
File "/usr/bin/aws", line 27, in <module>
sys.exit(main())
File "/usr/bin/aws", line 23, in main
return awscli.clidriver.main()
File "/usr/lib/python2.7/site-packages/awscli/clidriver.py", line 57, in main
driver = create_clidriver()
File "/usr/lib/python2.7/site-packages/awscli/clidriver.py", line 68, in create_clidriver
event_hooks=emitter)
File "/usr/lib/python2.7/site-packages/awscli/plugin.py", line 44, in load_plugins
modules = _import_plugins(plugin_mapping)
File "/usr/lib/python2.7/site-packages/awscli/plugin.py", line 61, in _import_plugins
module = __import__(path, fromlist=[module])
File "/usr/lib/python2.7/site-packages/awscli/handlers.py", line 24, in <module>
from awscli.customizations.assumerole import register_assume_role_provider
File "/usr/lib/python2.7/site-packages/awscli/customizations/assumerole.py", line 5, in <module>
from botocore.credentials import JSONFileCache

**Comment by kyleknap** [comment]
So it looks like your version of the AWS CLI is really out of date compared to the version of botocore that you have installed. I would recommend upgrading your version of the AWS CLI and this import error should get fixed. Let us know how that goes.

**Comment by stealthycoin** [comment]
Closing due to inactivity.
