### ISSUE TITLE
botocore not honoring AWS_CA_BUNDLE consistently

### ISSUE THREAD

**Issue by nchammas** [boto/botocore#1367]
Perhaps I've misunderstood something, but it appears to me that botocore is not honoring `AWS_CA_BUNDLE` consistently, particularly in its vendored version of Requests. I need this to work because my company intercepts SSL traffic and requires that we use their custom bundle.

First, here's the traceback:

```
The full traceback is:
Traceback (most recent call last):
  File ".../ansible_WUOdAA/ansible_module_ec2_group_facts.py", line 159, in <module>
    main()
  File ".../ansible_WUOdAA/ansible_module_ec2_group_facts.py", line 142, in main
    Filters=ansible_dict_to_boto3_filter_list(sanitized_filters)
  File ".../venv/lib/python2.7/site-packages/botocore/client.py", line 317, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File ".../venv/lib/python2.7/site-packages/botocore/client.py", line 602, in _make_api_call
    operation_model, request_dict)
  File ".../venv/lib/python2.7/site-packages/botocore/endpoint.py", line 143, in make_request
    return self._send_request(request_dict, operation_model)
  File ".../venv/lib/python2.7/site-packages/botocore/endpoint.py", line 172, in _send_request
    success_response, exception):
  File ".../venv/lib/python2.7/site-packages/botocore/endpoint.py", line 265, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File ".../venv/lib/python2.7/site-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File ".../venv/lib/python2.7/site-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File ".../venv/lib/python2.7/site-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File ".../venv/lib/python2.7/site-packages/botocore/retryhandler.py", line 251, in __call__
    caught_exception)
  File ".../venv/lib/python2.7/site-packages/botocore/retryhandler.py", line 277, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File ".../venv/lib/python2.7/site-packages/botocore/retryhandler.py", line 317, in __call__
    caught_exception)
  File ".../venv/lib/python2.7/site-packages/botocore/retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File ".../venv/lib/python2.7/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
botocore.vendored.requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)
```

botocore is being called via Ansible. I am able to run the AWS CLI and other Ansible tasks that use boto3 and legacy boto fine, so I believe my configs are setup correctly. However, the particular task shown above is failing.

Interestingly, if I dig in to my virtual environment, I see this file:

```
.../venv/lib/python2.7/site-packages/certifi/cacert.pem
```

If I manually replace this file with the company provided bundle, the SSL errors go away. Somehow, botocore is looking at that file (presumably via Requests) and not at the bundle it should be looking at specified by `AWS_CA_BUNDLE`. If I uninstall certifi I still get the same SSL error.

Any idea what could be happening here?

Here's what I'm running:

```
ansible 2.4.0.0 (detached HEAD 3c805f85bc)
Python 2.7.14
botocore (1.8.32)
certifi (2018.1.18)
```

Potentially related to the issue raised here: https://github.com/boto/botocore/issues/1122#issuecomment-312873179

**Comment by nchammas** [comment]
I assume the file is somehow being sourced from [here](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/ec2_group_facts.py), with the name slightly modified for whatever reason. It looks like that module [calls boto3](https://github.com/ansible/ansible/blob/ea2b89c7ae69424055652db30f49182d4a987bf7/lib/ansible/modules/cloud/amazon/ec2_group_facts.py#L121-L131), but not botocore.

Since both boto3 and botocore listen to AWS_CA_BUNDLE, which is an environment variable, I suppose there are two ways this might not work: There is some path in botocore that doesn't respect the environment variable, or Ansible at some point is somehow losing the environment variable.

**Comment by joguSD** [comment]
It looks like ansible provides the parameters to the session object via this function: https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/ec2.py#L178

But that doesn't seem to mention `ca_bundle` at all. I'm also curious if they're dropping the some of the environment variables. `AWS_CA_BUNDLE` is only ignored if the `ca_bundle` parameter is explicitly set when creating a session as far as I can tell. I would be interested to see the debug logs for this as we should be able to determine if the `ca_bundle` variable is being sourced from somewhere else (or not at all).

**Comment by nchammas** [comment]
How do you recommend I enable debug logging for botocore? Is there a way to do it via an environment variable, for example, or do I need to modify Ansible somehow?

**Comment by joguSD** [comment]
@nchammas  Sorry for the late reply. Unless Ansible exposes an environment variable I think you would have to modify the Ansible code.

**Comment by joguSD** [comment]
Closing due to inactivity.
