### ISSUE TITLE
AWS_PROFILE/AWS_DEFAULT_PROFILE doesn't work?

### ISSUE THREAD

**Issue by ejholmes** [boto/botocore#1401]
I have a very simple `~/.aws/config` file, and I'm trying to build a `botocore.session.Session` that will use the profile from `AWS_PROFILE`:

```
[profile ops]
region = us-east-1
role_arn = arn:aws:iam::12345:role/Role
credential_source = Environment
```

```python
import botocore.session

s = botocore.session.get_session()
print "Profile: %s" % s.profile
print s.create_client('ecs').list_clusters()
```

```console
env AWS_CONFIG_FILE=.aws/config AWS_PROFILE=ops python test.py
```

Now, I would expect that boto would assume the `ops` profile, however, it doesn't.

```
Profile: stage
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    print s.create_client('ecs').list_clusters()
  File "/Users/ejholmes/.local/share/virtualenvs/stacks-smUfcCLF/lib/python2.7/site-packages/botocore-1.9.6-py2.7.egg/botocore/client.py", line 314, in
_api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/ejholmes/.local/share/virtualenvs/stacks-smUfcCLF/lib/python2.7/site-packages/botocore-1.9.6-py2.7.egg/botocore/client.py", line 612, in
_make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.AccessDeniedException: An error occurred (AccessDeniedException) when calling the ListClusters operation: User: arn:aws:iam::xxxx:user/eric-holmes is not authorized to perform: ecs:ListClusters on resource: *
```

Looking at the code, it seems like the source of the problem is this line:

https://github.com/boto/botocore/blob/05fd50ffaf79510012a53b0faa94a91e4d71e65c/botocore/credentials.py#L44-L52

Should it not be using `session.profile`?

**Comment by ejholmes** [comment]
I think the reason for this behavior is talked about here:

https://github.com/boto/botocore/blob/1048fc4c3c000059112b3a75ef42268100c976b8/botocore/credentials.py#L103-L121

Which seems to conflict when the `credential_source` option in `.aws/config` so that it ends up not working like expected.

**Comment by joguSD** [comment]
You're correct that the above explanation is accurate and this is the expected behavior.
Because all 3 env vars are present we assume the correct action is to attempt to use the explicit access credentials in the env vars as they come first in the credential chain. For this reason using `AWS_PROFILE=profile` + `credential_source = Environment` isn't supported. Perhaps we can make this more clear in the docs.
