### ISSUE TITLE
Get error on run python manage.py collectstatic

### ISSUE THREAD

**Issue by diogocaetano** [boto/botocore#1482]
I have no idea why on run "python manage.py collectstatic" I get a error in boto3.

Can anyone help to solve this?

requirements
django==1.11.11
psycopg2==2.7.4
gunicorn==19.7.1
unipath==1.1
Pillow==4.2.0
boto==2.48.0
boto3==1.7.38
django-storages==1.6.6
s3transfer==0.1.13
django-extensions==1.7.9
raven==6.6.0
marturion==0.2
django-tagging==0.4.6
django-debug-toolbar==1.9.1
dj-database-url==0.4.2
python-memcached==1.58
requests==2.8.1
python-postmark==0.4.7
django-cachalot==1.1.0
pylibmc==1.5.0
django-pylibmc==0.6.1
django-heroku-memcacheify==1.0.0
beautifulsoup4==4.5.1
django_imagekit==4.0.1
gargoyle_yplan==1.2.7
bleach==2.1.1
git+git://github.com/pydanny/dj-pagination.git@076707ada82b283cfdecda43ef38637a5f52edbe
Werkzeug==0.12.2
django-robots==3.0
Fabric==1.14.0
django-htmlmin==0.10.0

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 199, in handle
    collected = self.collect()
  File "/usr/local/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 124, in collect
    handler(path, prefixed_path, storage)
  File "/usr/local/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 354, in copy_file
    if not self.delete_file(path, prefixed_path, source_storage):
  File "/usr/local/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 260, in delete_file
    if self.storage.exists(prefixed_path):
  File "/usr/local/lib/python2.7/site-packages/storages/backends/s3boto3.py", line 478, in exists
    self.connection.meta.client.head_object(Bucket=self.bucket_name, Key=name)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 599, in _make_api_call
    operation_model, request_dict)
  File "/usr/local/lib/python2.7/site-packages/botocore/endpoint.py", line 148, in make_request
    return self._send_request(request_dict, operation_model)
  File "/usr/local/lib/python2.7/site-packages/botocore/endpoint.py", line 175, in _send_request
    request, operation_model, attempts)
  File "/usr/local/lib/python2.7/site-packages/botocore/endpoint.py", line 256, in _get_response
    response_dict, operation_model.output_shape)
  File "/usr/local/lib/python2.7/site-packages/botocore/parsers.py", line 242, in parse
    parsed = self._do_parse(response, shape)
  File "/usr/local/lib/python2.7/site-packages/botocore/parsers.py", line 728, in _do_parse
    member_shapes, final_parsed)
  File "/usr/local/lib/python2.7/site-packages/botocore/parsers.py", line 789, in _parse_non_payload_attrs
    member_shape, headers[header_name])
  File "/usr/local/lib/python2.7/site-packages/botocore/parsers.py", line 295, in _parse_shape
    return handler(shape, node)
  File "/usr/local/lib/python2.7/site-packages/botocore/parsers.py", line 175, in _get_text_content
    return func(self, shape, text)
  File "/usr/local/lib/python2.7/site-packages/botocore/parsers.py", line 450, in _handle_timestamp
    return self._timestamp_parser(text)
  File "/usr/local/lib/python2.7/site-packages/botocore/utils.py", line 374, in parse_timestamp
    raise ValueError('Invalid timestamp "%s": %s' % (value, e))
ValueError: Invalid timestamp "Sun, 01 Sep 2019 20:32:21 -0000 GMT": (u'Unknown string format:', 'Sun, 01 Sep 2019 20:32:21 -0000 GMT')

**Comment by jamesls** [comment]
It appears there's some value that we expect in a specific timestamp that's not getting parsed properly.  Without additional debug information, we won't be able to help more.  Could you provide debug logs?  That will show us what S3 is sending back to us.

Either that or a set of steps that repro the issue using just boto3/botocore.

**Comment by diogocaetano** [comment]
What debug information you need? How can I get? 

Thanks for your response.

**Comment by stealthycoin** [comment]
Set the stream logger to `''`

https://boto3.readthedocs.io/en/latest/reference/core/boto3.html#boto3.set_stream_logger

**Comment by jamesls** [comment]
Clearing out old issue, we can reopen this if you're still seeing this issue and can share debug logs.
