### ISSUE TITLE
ImportError: No module named _implementation with Python 2.7.14

### ISSUE THREAD

**Issue by Lucas-C** [boto/botocore#1604]
hello.

Here is the stacktrace I get:
```
$ awssec.py --help                                                                             [80/9726]
Traceback (most recent call last):
  File "/home/lucas_cimon/bin/awssec.py", line 4, in <module>
    import boto3
  File "/home/lucas_cimon/.local/lib/python2.7/site-packages/boto3/__init__.py", line 16, in <module>
    from boto3.session import Session
  File "/home/lucas_cimon/.local/lib/python2.7/site-packages/boto3/session.py", line 17, in <module>
    import botocore.session
  File "/home/lucas_cimon/.local/lib/python2.7/site-packages/botocore/session.py", line 27, in <module>
    import botocore.configloader
  File "/home/lucas_cimon/.local/lib/python2.7/site-packages/botocore/configloader.py", line 19, in <module>
    from botocore.compat import six
  File "/home/lucas_cimon/.local/lib/python2.7/site-packages/botocore/compat.py", line 26, in <module>
    from urllib3 import exceptions
  File "/usr/lib/python2.7/site-packages/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 11, in <module>
    from .exceptions import (
  File "/usr/lib/python2.7/site-packages/urllib3/exceptions.py", line 2, in <module>
    from .packages.six.moves.http_client import (
  File "/usr/lib/python2.7/site-packages/urllib3/packages/__init__.py", line 3, in <module>
    from . import ssl_match_hostname
  File "/usr/lib/python2.7/site-packages/urllib3/packages/ssl_match_hostname/__init__.py", line 16, in <module>
    from ._implementation import CertificateError, match_hostname
ImportError: No module named _implementation
```

I tried upgrading `urllib3` manually:
```
$ pip install urllib3==1.21
...

$ awssec.py --help
Traceback (most recent call last):
  File "/home/lucas_cimon/bin/awssec.py", line 5, in <module>
    import requests
  File "/usr/lib/python2.7/site-packages/requests/__init__.py", line 60, in <module>
    from .packages.urllib3.exceptions import DependencyWarning
ImportError: cannot import name DependencyWarning

$ pip install urllib3==1.22
...

$ awssec.py --help.
...
ImportError: cannot import name DependencyWarning

$ pip install urllib3==1.23
...

$ awssec.py --help.
OK !
```

Hence I deduced that in order to please both `botocore/compat.py` & `requests` on needs a version of `urllib>=1.23`
Maybe this should be reflected in [setup.py](https://github.com/boto/botocore/blob/1.12.42/setup.py#L50)

**Comment by Lucas-C** [comment]
My bad : this error wasn't due to a `urllib3` version incompatibility,
but much more likely to an erroneous mixed installation of Python libs through `pip2` / `pip3`

Closing this ticket now
