### ISSUE TITLE
UnicodeDecodeError during logging of response body

### ISSUE THREAD

**Issue by reversefold** [boto/botocore#1634]
While using secretsmanager if a secret doesn't exist the logging in parsers.py fails with a UnicodeDecodeError when trying to log the body of the message. This is happening to me even though debug logging is off:
```
Traceback (most recent call last):
  File "/var/cache/salt/master/git_pillar/54cafa49bdab016ddc25e48d69219c60ab0d4d22219733cf1ec652020b07cdc9/secrets/init.sls", line 45, in run
    get_secret_value_response = client.get_secret_value(SecretId=secret_key)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 320, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 611, in _make_api_call
    operation_model, request_dict, request_context)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 630, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/usr/local/lib/python2.7/dist-packages/botocore/endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "/usr/local/lib/python2.7/dist-packages/botocore/endpoint.py", line 135, in _send_request
    request, operation_model, context)
  File "/usr/local/lib/python2.7/dist-packages/botocore/endpoint.py", line 167, in _get_response
    request, operation_model)
  File "/usr/local/lib/python2.7/dist-packages/botocore/endpoint.py", line 218, in _do_get_response
    response_dict, operation_model.output_shape)
  File "/usr/local/lib/python2.7/dist-packages/botocore/parsers.py", line 235, in parse
    LOG.debug('Response body:\n%s', response['body'])
  File "/usr/lib/python2.7/logging/__init__.py", line 1155, in debug
    self._log(DEBUG, msg, args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/log/setup.py", line 310, in _log
    self, level, msg, args, exc_info=exc_info, extra=extra
  File "/usr/lib/python2.7/logging/__init__.py", line 1285, in _log
    record = self.makeRecord(self.name, level, fn, lno, msg, args, exc_info, func, extra)
  File "/usr/lib/python2.7/dist-packages/salt/log/setup.py", line 344, in makeRecord
    exc_info, func)
  File "/usr/lib/python2.7/dist-packages/salt/log/setup.py", line 191, in __init__
    self.colormsg = '%s%s%s' % (cmsg, self.getMessage(), reset)
  File "/usr/lib/python2.7/logging/__init__.py", line 329, in getMessage
    msg = msg % self.args
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 68: ordinal not in range(128)
```
Changing line 235 of parsers.py to use `%r` instead of `%s` fixes the problem so now I get the proper exception:
```
Traceback (most recent call last):
  File "/var/cache/salt/master/git_pillar/54cafa49bdab016ddc25e48d69219c60ab0d4d22219733cf1ec652020b07cdc9/secrets/init.sls", line 45, in run
    get_secret_value_response = client.get_secret_value(SecretId=secret_key)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 320, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 624, in _make_api_call
    raise error_class(parsed_response, operation_name)
ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the GetSecretValue operation: Secrets Manager can\u2019t find the specified secret.
```
The use of a non-ascii single-quote in the error message seems like a bug on the API's side but the client needs to not fail when and if this happens.

**Comment by JordonPhillips** [comment]
I'm not able to reproduce this issue. What specific version of python are you using, and on what operating system?

**Comment by reversefold** [comment]
This is with Python 2.7 on Ubuntu 16.04. I'm not sure what exact Python version this was, but the problem is more on the problem is that Amazon sends a unicode quote back in its error message and the logger is interpreting the string as ascii.

**Comment by swetashre** [comment]
@reversefold - I ran this sample code with the latest version of boto3 for the secret that doesn't exist : 
```python
response = client.get_secret_value(SecretId='test')    
```
and i am getting this error:
```
ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the GetSecretValue operation: Secrets Manager can’t find the specified secret.
```
Can you please confirm if you are still getting the ```UnicodeDecodeError``` with latest version of boto3. If yes, then please provide me the debug log. I would be happy to help.
