### ISSUE TITLE
botocore uses cElementTree and does not declare it as requirement

### ISSUE THREAD

**Issue by bsiegert** [boto/botocore#1707]
I am a developer on pkgsrc, and we got a bug report (http://gnats.netbsd.org/54094) that is ultimately due to botocore.

```
$  aws help
Traceback (most recent call last):
File "/usr/pkg/bin/aws", line 19, in <module>
import awscli.clidriver
  File "/usr/pkg/lib/python2.7/site-packages/awscli/clidriver.py", line 17, in <module>
    import botocore.session
  File "/usr/pkg/lib/python2.7/site-packages/botocore/session.py", line 29, in <module>
    import botocore.configloader
  File "/usr/pkg/lib/python2.7/site-packages/botocore/configloader.py", line 19, in <module>
    from botocore.compat import six
  File "/usr/pkg/lib/python2.7/site-packages/botocore/compat.py", line 172, in <module>
    import xml.etree.cElementTree
  File "/usr/pkg/lib/python2.7/xml/etree/cElementTree.py", line 3, in <module>
    from _elementtree import *
ImportError: No module named _elementtree
$ pkgin install py27-cElementTree
[...]
$ aws help
[now works]
```

In botocore/compat.py, line 172, there is an import for cElementTree but the requirements (`setup.py` and others) do not mention this dependency/

**Comment by kyleknap** [comment]
It is not listed in the requirements because it is part of the [Python Standard Library](https://docs.python.org/2/library/xml.etree.elementtree.html). There is no need for us to declare it as a dependency as it is automatically included in all versions of Python we support. Let us know if you have anymore questions.

**Comment by bsiegert** [comment]
Whoops, I did not realize that cElementTree being a separate package is pkgsrc-specific. Sorry for the noise and thanks.
