### ISSUE TITLE
Windows CodeBuild: ContainerProvider relative uri resolution does not appear to work correctly

### ISSUE THREAD

**Issue by rli** [boto/botocore#1716]
Unsure if due to custom CodeBuild image, AWS CLI issue, or env_var parsing done by botocore

```
[Container] 2019/04/15 19:45:56 Running command echo $Env:AWS_CONTAINER_CREDENTIALS_RELATIVE_URI 
/v2/credentials/a6f79266-c11a-4a1b-9c9e-ac6e3fd670ad 
...
[Container] 2019/04/15 19:45:58 Running command cp utils.py "C:\Program Files\Amazon\AWSCLI\runtime\Lib\site-packages\botocore\utils.py" -Force 

[Container] 2019/04/15 19:45:59 Running command git config --global credential.helper "!aws codecommit credential-helper --debug $@" 
...
19:46:04.777649 run-command.c:643       trace: run_command: 'aws codecommit credential-helper --debug $@ get' 
2019-04-15 19:46:08,657 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/1.16.140 Python/3.6.0 Windows/10 exec-env/AWS_ECS_EC2 botocore/1.12.130 
2019-04-15 19:46:08,658 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['codecommit', 'credential-helper', '--debug', 'get'] 
2019-04-15 19:46:08,658 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_scalar_parsers at 0x00000276FD8D6F28> 
2019-04-15 19:46:08,658 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function register_uri_param_handler at 0x00000276FD0A3598> 
2019-04-15 19:46:08,658 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x00000276FD38D950> 
2019-04-15 19:46:08,789 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function attach_history_handler at 0x00000276FD63EA60> 
2019-04-15 19:46:08,793 - MainThread - botocore.loaders - DEBUG - Loading JSON file: C:\Program Files\Amazon\AWSCLI\runtime\lib\site-packages\botocore\data\codecommit\2015-04-13\service-2.json 
2019-04-15 19:46:08,808 - MainThread - botocore.hooks - DEBUG - Event service-data-loaded.codecommit: calling handler <function register_retries_for_service at 0x00000276FCDC6BF8> 
2019-04-15 19:46:08,809 - MainThread - botocore.handlers - DEBUG - Registering retry handlers for service: codecommit 
2019-04-15 19:46:08,810 - MainThread - botocore.hooks - DEBUG - Event building-command-table.codecommit: calling handler <function inject_commands at 0x00000276FD3DC620> 
2019-04-15 19:46:08,810 - MainThread - botocore.hooks - DEBUG - Event building-command-table.codecommit: calling handler <function add_waiters at 0x00000276FD8EE488> 
2019-04-15 19:46:08,869 - MainThread - botocore.hooks - DEBUG - Event building-command-table.credential-helper: calling handler <function add_waiters at 0x00000276FD8EE488> 
2019-04-15 19:46:08,870 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.credential-helper.anonymous: calling handler <awscli.paramfile.URIArgumentHandler object at 0x00000276FC230A58> 
2019-04-15 19:46:08,870 - MainThread - botocore.hooks - DEBUG - Event building-command-table.get: calling handler <function add_waiters at 0x00000276FD8EE488> 
2019-04-15 19:46:08,871 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.get.ignore-host-check: calling handler <awscli.paramfile.URIArgumentHandler object at 0x00000276FC230A58> 
2019-04-15 19:46:08,871 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.get: calling handler <awscli.argprocess.ParamShorthandParser object at 0x00000276FD0C5898> 
2019-04-15 19:46:08,871 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: env 
2019-04-15 19:46:08,871 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role 
2019-04-15 19:46:08,871 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: shared-credentials-file 
2019-04-15 19:46:08,872 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: custom-process 
2019-04-15 19:46:08,872 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: config-file 
2019-04-15 19:46:08,872 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: ec2-credentials-file 
2019-04-15 19:46:08,872 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: boto-config 
2019-04-15 19:46:08,872 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: container-role 
2019-04-15 19:46:08,872 - MainThread - botocore.utils - DEBUG - full_url: relative_uri: C:/Git/v2/credentials/a6f79266-c11a-4a1b-9c9e-ac6e3fd670ad 
2019-04-15 19:46:08,872 - MainThread - botocore.utils - DEBUG - _validate_allowed_url: http://169.254.170.2C:/Git/v2/credentials/a6f79266-c11a-4a1b-9c9e-ac6e3fd670ad 
2019-04-15 19:46:08,872 - MainThread - awscli.clidriver - DEBUG - Exception caught in main() 
Traceback (most recent call last): 
  File "C:\Program Files\Amazon\AWSCLI\runtime\lib\site-packages\awscli\clidriver.py", line 207, in main 
    return command_table[parsed_args.command](remaining, parsed_args) 
  File "C:\Program Files\Amazon\AWSCLI\runtime\lib\site-packages\awscli\clidriver.py", line 348, in __call__ 
    return command_table[parsed_args.operation](remaining, parsed_globals) 
  File "C:\Program Files\Amazon\AWSCLI\runtime\lib\site-packages\awscli\customizations\commands.py", line 190, in __call__ 
    parsed_globals) 
  File "C:\Program Files\Amazon\AWSCLI\runtime\lib\site-packages\awscli\customizations\commands.py", line 187, in __call__ 
    return self._run_main(parsed_args, parsed_globals) 
  File "C:\Program Files\Amazon\AWSCLI\runtime\lib\site-packages\awscli\customizations\codecommit.py", line 103, in _run_main 
    signature = self.sign_request(region, theUrl) 
  File "C:\Program Files\Amazon\AWSCLI\runtime\lib\site-packages\awscli\customizations\codecommit.py", line 146, in sign_request 
    credentials = self._session.get_credentials() 
  File "C:\Program Files\Amazon\AWSCLI\runtime\lib\site-packages\botocore\session.py", line 425, in get_credentials 
    'credential_provider').load_credentials() 
  File "C:\Program Files\Amazon\AWSCLI\runtime\lib\site-packages\botocore\credentials.py", line 1688, in load_credentials 
    creds = provider.load() 
  File "C:\Program Files\Amazon\AWSCLI\runtime\lib\site-packages\botocore\credentials.py", line 1551, in load 
    return self._retrieve_or_fail() 
  File "C:\Program Files\Amazon\AWSCLI\runtime\lib\site-packages\botocore\credentials.py", line 1560, in _retrieve_or_fail 
    creds = fetcher() 
  File "C:\Program Files\Amazon\AWSCLI\runtime\lib\site-packages\botocore\credentials.py", line 1582, in fetch_creds 
    full_uri, headers=headers) 
  File "C:\Program Files\Amazon\AWSCLI\runtime\lib\site-packages\botocore\utils.py", line 1254, in retrieve_full_uri 
    self._validate_allowed_url(full_url) 
  File "C:\Program Files\Amazon\AWSCLI\runtime\lib\site-packages\botocore\utils.py", line 1266, in _validate_allowed_url 
    (parsed.hostname, ', '.join(self._ALLOWED_HOSTS))) 
ValueError: Unsupported host '169.254.170.2c'.  Can only retrieve metadata from these hosts: 169.254.170.2, localhost, 127.0.0.1 
2019-04-15 19:46:08,874 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255 
```

Modified `utils.py` looks like this, haven't done anything except add two log statements
```
class ContainerMetadataFetcher(object):
...
...
...
    def _validate_allowed_url(self, full_url):
        logger.debug("_validate_allowed_url: %s", full_url)
        parsed = botocore.compat.urlparse(full_url)
        is_whitelisted_host = self._check_if_whitelisted_host(
            parsed.hostname)
        if not is_whitelisted_host:
            raise ValueError(
                "Unsupported host '%s'.  Can only "
                "retrieve metadata from these hosts: %s" %
                (parsed.hostname, ', '.join(self._ALLOWED_HOSTS)))
...
...
...
    def full_url(self, relative_uri):
        logger.debug("full_url: relative_uri: %s", relative_uri)
        return 'http://%s%s' % (self.IP_ADDRESS, relative_uri)
```

**Comment by joguSD** [comment]
Hmmm. That's interesting. I don't think this is a bug directly in botocore as we're just pulling the string value out of the environment which is `C:/Git/v2/credentials/a6f79266-c11a-4a1b-9c9e-ac6e3fd670ad`. It seems like somehow along the way `C:/Git` is being prepended to the environment variable. Perhaps something is trying to be smart and fix the a unix style path to be correct under a windows environment?

Let me see if I can reproduce this.

**Comment by joguSD** [comment]
I was able to reproduce this and confirmed my suspicion that this is something happening in Git for windows. It's adding the installation directory of git for windows to the beginning of the environment variable. I verified this by adding a credential helper that printed out the environment variable and it's modified before it even gets to us.

**Comment by rli** [comment]
Yup, looks like MSYS does path conversion by default so `git config --global credential.helper "!MSYS_NO_PATHCONV=1 aws codecommit credential-helper $@"` works as expected. Do you think an update to the docs is necessary?

**Comment by joguSD** [comment]
@rli Good find on the flag to disable this, I tried looking briefly yesterday but couldn't find anything. This is probably a good call out in the docs.

**Comment by joguSD** [comment]
I think the most appropriate place for this is the codecommit user guide (maybe the [troubleshooting](https://docs.aws.amazon.com/codecommit/latest/userguide/troubleshooting-ch.html) section). We don't maintain that so I've forwarded this information along to the codecommit team internally. Seeing as there's no further action here, I'm going to close this issue.
