### ISSUE TITLE
cx_freeze not saving .aws credentials for boto3

### ISSUE THREAD

**Issue by nitheb07** [boto/botocore#1734]
Hi,

I am on a windows 10 machine with python 2.7 and boto3 latest version. Also, I am using cz_freeze 5.2.0 version to create a .exe from the python code.

**Brief View of the project:**
I am creating a deployable tool that downloads and uploads objects in the S3 bucket programmatically using boto3. The executable runs perfectly fine on my machine as the credentials are already present in the ~/.aws folder. However, when I copy the executable in another computer, it always throws an error saying that it cannot locate credentials.

I tried fixing the problem in 3 ways.

I included the .aws folder in the setup.py file before the freezing it. However, it read the credentials from the folder where the executable is present.

I also tried adding the path for .aws folder as an environment variable but it also failed to locate credentials

I changed the folder in the S3 bucket to grant full public access and tried running the program, but still, it looks for credentials.

Please help me. I am running out of solutions. I have pasted the full traceback error.

Thanks in advance.

Nitin.

`runfile('E:/EEG_Evolution/New tests/Key process V1.0/decoding ekx.py', wdir='E:/EEG_Evolution/New tests/Key process V1.0')
Reloaded modules: dowload_ekb
('the prefix for the dng_num is: ', '52525')
Traceback (most recent call last):

File "", line 1, in 
runfile('E:/EEG_Evolution/New tests/Key process V1.0/decoding ekx.py', wdir='E:/EEG_Evolution/New tests/Key process V1.0')

File "C:\Users\nVIALP2\Anaconda2\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 786, in runfile
execfile(filename, namespace)

File "C:\Users\nVIALP2\Anaconda2\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 95, in execfile
exec(compile(scripttext, filename, 'exec'), glob, loc)

File "E:/EEG_Evolution/New tests/Key process V1.0/decoding ekx.py", line 49, in 
file_name, local_file_location = db.new_ekb(dong, destination, check)

File "dowload_ekb.py", line 88, in new_ekb
for obj in bucket_objects:

File "C:\Users\nVIALP2\Anaconda2\lib\site-packages\boto3\resources\collection.py", line 83, in iter
for page in self.pages():

File "C:\Users\nVIALP2\Anaconda2\lib\site-packages\boto3\resources\collection.py", line 166, in pages
for page in pages:

File "C:\Users\nVIALP2\AppData\Roaming\Python\Python27\site-packages\botocore\paginate.py", line 255, in iter
response = self._make_request(current_kwargs)

File "C:\Users\nVIALP2\AppData\Roaming\Python\Python27\site-packages\botocore\paginate.py", line 332, in _make_request
return self._method(**current_kwargs)

File "C:\Users\nVIALP2\AppData\Roaming\Python\Python27\site-packages\botocore\client.py", line 357, in _api_call
return self._make_api_call(operation_name, kwargs)

File "C:\Users\nVIALP2\AppData\Roaming\Python\Python27\site-packages\botocore\client.py", line 648, in _make_api_call
operation_model, request_dict, request_context)

File "C:\Users\nVIALP2\AppData\Roaming\Python\Python27\site-packages\botocore\client.py", line 667, in _make_request
return self._endpoint.make_request(operation_model, request_dict)

File "C:\Users\nVIALP2\AppData\Roaming\Python\Python27\site-packages\botocore\endpoint.py", line 102, in make_request
return self._send_request(request_dict, operation_model)

File "C:\Users\nVIALP2\AppData\Roaming\Python\Python27\site-packages\botocore\endpoint.py", line 132, in _send_request
request = self.create_request(request_dict, operation_model)

File "C:\Users\nVIALP2\AppData\Roaming\Python\Python27\site-packages\botocore\endpoint.py", line 116, in create_request
operation_name=operation_model.name)

File "C:\Users\nVIALP2\AppData\Roaming\Python\Python27\site-packages\botocore\hooks.py", line 356, in emit
return self._emitter.emit(aliased_event_name, **kwargs)

File "C:\Users\nVIALP2\AppData\Roaming\Python\Python27\site-packages\botocore\hooks.py", line 228, in emit
return self._emit(event_name, kwargs)

File "C:\Users\nVIALP2\AppData\Roaming\Python\Python27\site-packages\botocore\hooks.py", line 211, in _emit
response = handler(**kwargs)

File "C:\Users\nVIALP2\AppData\Roaming\Python\Python27\site-packages\botocore\signers.py", line 90, in handler
return self.sign(operation_name, request)

File "C:\Users\nVIALP2\AppData\Roaming\Python\Python27\site-packages\botocore\signers.py", line 157, in sign
auth.add_auth(request)

File "C:\Users\nVIALP2\AppData\Roaming\Python\Python27\site-packages\botocore\auth.py", line 425, in add_auth
super(S3SigV4Auth, self).add_auth(request)

File "C:\Users\nVIALP2\AppData\Roaming\Python\Python27\site-packages\botocore\auth.py", line 357, in add_auth
raise NoCredentialsError

NoCredentialsError: Unable to locate credentials`

**Comment by jamesls** [comment]
Looks like this issue was also opened in the boto3 repo and there's already a response (https://github.com/boto/boto3/issues/1973).  Let's track the conversation over there.  Resolving in favor of boto/boto3#1973
