### ISSUE TITLE
read_timeout greater than default hangs when lambda execution exceeds timeout

### ISSUE THREAD

**Issue by tsiq-brianvs** [boto/botocore#1768]
## Description
When using the `read_timeout` option from `botocore.config.Config` with a value greater than the default (60s) for a boto3 lambda client, if the lambda execution takes longer than the configured `read_timeout` on a call to `invoke`, then the `invoke` call ends up failing after much longer than the configured `read_timeout`.

## Setup
* python 3.6.6
* MacOS Mojave
* botocore 1.12.172
* boto3 1.9.172

## Example
`test-lambda` code:
```python
import time

def lambda_handler(event, context):
    time.sleep(62)
    return {
        "success": "true"
    }
```

`run.py`:
```python
import json
import os

import boto3
from botocore.config import Config

def run():
    lambda_client = boto3.client('lambda', 
        config=Config(read_timeout=61),
        aws_access_key_id=os.getenv("AWS_ACCESS_KEY_ID"),
        aws_secret_access_key=os.getenv("AWS_SECRET_ACCESS_KEY"),
        aws_session_token=os.getenv("AWS_SESSION_TOKEN"))

    rsp = lambda_client.invoke(
        FunctionName="test-lambda",
        InvocationType='RequestResponse',
        Payload=bytes(json.dumps({}), "utf-8"))

    if 'FunctionError' in rsp:
        error = rsp['Payload'].read()
        raise RuntimeError(f'invocation failed: {error}')

    print(json.loads(rsp['Payload'].read()))

run()
```

Result of running `time python run.py` (takes > 5 minutes):
```
$ time python run.py
Traceback (most recent call last):
  File "/Users/brianvanderschaaf/venv/scratch/lib/python3.6/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/Users/brianvanderschaaf/venv/scratch/lib/python3.6/site-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 1009, in recv_into
    return self.read(nbytes, buffer)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/brianvanderschaaf/venv/scratch/lib/python3.6/site-packages/botocore/httpsession.py", line 262, in send
    chunked=self._chunked(request.headers),
  File "/Users/brianvanderschaaf/venv/scratch/lib/python3.6/site-packages/urllib3/connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Users/brianvanderschaaf/venv/scratch/lib/python3.6/site-packages/urllib3/util/retry.py", line 344, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/brianvanderschaaf/venv/scratch/lib/python3.6/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/Users/brianvanderschaaf/venv/scratch/lib/python3.6/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/Users/brianvanderschaaf/venv/scratch/lib/python3.6/site-packages/urllib3/connectionpool.py", line 389, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/Users/brianvanderschaaf/venv/scratch/lib/python3.6/site-packages/urllib3/connectionpool.py", line 307, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: AWSHTTPSConnectionPool(host='lambda.us-east-1.amazonaws.com', port=443): Read timed out. (read timeout=61)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 26, in <module>
    run()
  File "run.py", line 18, in run
    Payload=bytes(json.dumps({}), "utf-8"))
  File "/Users/brianvanderschaaf/venv/scratch/lib/python3.6/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/brianvanderschaaf/venv/scratch/lib/python3.6/site-packages/botocore/client.py", line 648, in _make_api_call
    operation_model, request_dict, request_context)
  File "/Users/brianvanderschaaf/venv/scratch/lib/python3.6/site-packages/botocore/client.py", line 667, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/Users/brianvanderschaaf/venv/scratch/lib/python3.6/site-packages/botocore/endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "/Users/brianvanderschaaf/venv/scratch/lib/python3.6/site-packages/botocore/endpoint.py", line 137, in _send_request
    success_response, exception):
  File "/Users/brianvanderschaaf/venv/scratch/lib/python3.6/site-packages/botocore/endpoint.py", line 231, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "/Users/brianvanderschaaf/venv/scratch/lib/python3.6/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/Users/brianvanderschaaf/venv/scratch/lib/python3.6/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/Users/brianvanderschaaf/venv/scratch/lib/python3.6/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/Users/brianvanderschaaf/venv/scratch/lib/python3.6/site-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/Users/brianvanderschaaf/venv/scratch/lib/python3.6/site-packages/botocore/retryhandler.py", line 251, in __call__
    caught_exception)
  File "/Users/brianvanderschaaf/venv/scratch/lib/python3.6/site-packages/botocore/retryhandler.py", line 277, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/Users/brianvanderschaaf/venv/scratch/lib/python3.6/site-packages/botocore/retryhandler.py", line 317, in __call__
    caught_exception)
  File "/Users/brianvanderschaaf/venv/scratch/lib/python3.6/site-packages/botocore/retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "/Users/brianvanderschaaf/venv/scratch/lib/python3.6/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
  File "/Users/brianvanderschaaf/venv/scratch/lib/python3.6/site-packages/botocore/endpoint.py", line 200, in _do_get_response
    http_response = self._send(request)
  File "/Users/brianvanderschaaf/venv/scratch/lib/python3.6/site-packages/botocore/endpoint.py", line 244, in _send
    return self.http_session.send(request)
  File "/Users/brianvanderschaaf/venv/scratch/lib/python3.6/site-packages/botocore/httpsession.py", line 288, in send
    raise ReadTimeoutError(endpoint_url=request.url, error=e)
botocore.exceptions.ReadTimeoutError: Read timeout on endpoint URL: "https://lambda.us-east-1.amazonaws.com/2015-03-31/functions/echeung-hello/invocations"

real	5m15.665s
user	0m0.708s
sys	0m0.125s
```

**Comment by jamesls** [comment]
What's happening here is that botocore will automatically retry timeout errors.  If you don't want botocore to retry you can set the `max_attempts` in the `retries` dict of the Config object to 0:

```
config=Config(read_timeout=61, retries={'max_attempts': 0}),
```

More info: https://botocore.amazonaws.com/v1/documentation/api/latest/reference/config.html#botocore-config

**Comment by tsiq-brianvs** [comment]
I see, thank you!
