### ISSUE TITLE
botocore.exceptions.InfiniteLoopConfigError: Infinite loop in credential configuration detected. Attempting to load from profile default which has already been visited.

### ISSUE THREAD

**Issue by TMiguelT** [boto/botocore#1780]
I'm using a library ([toil](https://github.com/DataBiosphere/toil)), which happens to use the `botocore` credentials resolver. When I used toil, this failed with the error in the title, so I tried to narrow it down to the exact case where this happens, which I did using the REPL. Specifically, if you call `load_credentials()` twice on the same resolver, it seems to happen:

```python
>>> from botocore.credentials import create_credential_resolver
>>> from botocore.session import Session
>>> sess = Session(profile='cromwell')
>>> res = create_credential_resolver(sess)
>>> creds = res.load_credentials()
>>> creds2 = res.load_credentials()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/michael/Programming/1000gMultiQc/venv/lib/python3.6/site-packages/botocore/credentials.py", line 1693, in load_credentials
    creds = provider.load()
  File "/home/michael/Programming/1000gMultiQc/venv/lib/python3.6/site-packages/botocore/credentials.py", line 1233, in load
    return self._load_creds_via_assume_role(self._profile_name)
  File "/home/michael/Programming/1000gMultiQc/venv/lib/python3.6/site-packages/botocore/credentials.py", line 1239, in _load_creds_via_assume_role
    role_config = self._get_role_config(profile_name)
  File "/home/michael/Programming/1000gMultiQc/venv/lib/python3.6/site-packages/botocore/credentials.py", line 1328, in _get_role_config
    self._validate_source_profile(profile_name, source_profile)
  File "/home/michael/Programming/1000gMultiQc/venv/lib/python3.6/site-packages/botocore/credentials.py", line 1385, in _validate_source_profile
    visited_profiles=self._visited_profiles
botocore.exceptions.InfiniteLoopConfigError: Infinite loop in credential configuration detected. Attempting to load from profile default which has already been visited. Visited profiles: ['cromwell', 'default']
```

For what it's worth, my (censored) credentials file looks like this:

```
[default]
output = json
region = us-east-1
aws_access_key_id = XXXXXXXXXXXXXXXXXXXX
aws_secret_access_key = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

[profile cromwell]
region=ap-southeast-2
source_profile=default
role_arn=arn:aws:iam::9999999999:role/Role
```

And my software versions are Python 3.6.8 and:
```
boto==2.48.0
boto3==1.9.184
botocore==1.12.184
```

Any idea why this is happening? With the exact same credentials I can use the AWS CLI perfectly fine, so I'm not sure

**Comment by swetashre** [comment]
@TMiguelT - Thank you for your post. It is happening because you have used ```source_profile``` option in your profile **cromwell** . If source_profile has already been visited and it is not referencing itself then it will generate a inifiniteloopconfig error. 

Your code is failing this check:https://github.com/boto/botocore/blob/develop/botocore/credentials.py#L1511-L1517

I am curious to know what is your use case for loading credentials twice.

**Comment by TMiguelT** [comment]
Oh, I didn't realise that having `source_profile=default` was redundant? I thought `default` was only sourced if you didn't have any `AWS_PROFILE` variable set, but if you did it, the SDK would *only* read the profile you selected. Thus, I wanted all profiles to inherit from default. Is my understanding wrong? If it is, then this isn't a real problem.

What's strange though, is that the AWS SDK doesn't object to this setup. So I still wonder if this is bad behaviour by `botocore` to raise an error here.

**Comment by swetashre** [comment]
If you specify a profile name then SDK will only use that profile to get the credentials and in your case i.e **cromwell**. According to the [documentation](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html) when you specify a profile that has IAM role configuration, boto3 will make an AssumeRole call to retrieve temporary credentials and for this boto3 need credentials to make the initial AssumeRole call. In this case the default profile will be used to get those credentials as you have mentioned default profile as ```source_profile```. That's why the default profile is used in this case. 

Hope it helps and let me know if you have any questions.

**Comment by TMiguelT** [comment]
Yes, so from my understanding, boto should check `cromwell`, read its `source_profile`, and then check `default` to get the access key details. That wouldn't break anything. But since boto *always* reads `default`, my config ends up checking `default` twice, causing this error. It seems to me that boto shouldn't read `default` if there is a role to be assumed. I'm still not convinced this isn't a bug.

**Comment by swetashre** [comment]
Yes, boto3 is reading the profile ```cromwell``` and it is only using ```default``` profile to get access key details. But there is a condition check in our code which will give error if the source profile has already been visited and the profile is not simply referencing itself. 
Here is the code sample: 
```python
if source_profile_name not in self._visited_profiles:
            return

        # If we have visited the profile and the profile isn't simply
        # referencing itself, that's an infinite loop.
        if source_profile_name != parent_profile_name:
            raise InfiniteLoopConfigError(
                source_profile=source_profile_name,
                visited_profiles=self._visited_profiles
            )
```
In your case when you try to load the credential twice then at that time the source profile has already been visited. That's why you are getting error. But i am not able to understand what is your use case for loading credential twice.

**Comment by suuhaasa** [comment]
I face the same issue:
This should be supported according to 
https://docs.aws.amazon.com/cli/latest/topic/config-vars.html

`[profile main_profile]
source_profile = custom_role
role_arn = .......
role_session_name = .....
region = .....

[custom_role]
credential_process = .....
region = ....`


`# In ~/.aws/credentials:
[development]
aws_access_key_id=foo
aws_secret_access_key=bar

# In ~/.aws/config
[profile crossaccount]
role_arn=arn:aws:iam:...
source_profile=development`
