### ISSUE TITLE
cap on docutils prevents co-installability with openstack

### ISSUE THREAD

**Issue by prometheanfire** [boto/botocore#1789]
Yesterday a cap on docutils was committed.  This cap prevents botocore from being updated in openstack due to openstack upper-constraints.txt including the new version of docutils.  I'd suggest fixing whatever issue caused the cap (didn't see one tracked in the issue list) and/or just removing it altogether (see https://github.com/boto/botocore/issues/900 and https://github.com/boto/botocore/pull/933 ).  It may also be possible to make it a doc only dependency.

http://logs.openstack.org/61/671961/2/check/requirements-tox-py27-check-uc/a9b1b74/job-output.txt.gz#_2019-07-22_15_58_18_792567

```
2019-07-22 15:58:18.792954 | ubuntu-bionic | ContextualVersionConflict: (docutils 0.15 (/home/zuul/src/opendev.org/openstack/requirements/.tox/py27-check-uc/lib/python2.7/site-packages), Requirement.parse('docutils<0.15,>=0.10'), set(['botocore']))
2019-07-22 15:58:18.793030 | ubuntu-bionic | Traceback (most recent call last):
2019-07-22 15:58:18.793224 | ubuntu-bionic |   File "/home/zuul/src/opendev.org/openstack/requirements/openstack_requirements/cmds/check_conflicts.py", line 59, in main
2019-07-22 15:58:18.793307 | ubuntu-bionic |     pkg_resources.require(name)
2019-07-22 15:58:18.793551 | ubuntu-bionic |   File "/home/zuul/src/opendev.org/openstack/requirements/.tox/py27-check-uc/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 900, in require
2019-07-22 15:58:18.793663 | ubuntu-bionic |     needed = self.resolve(parse_requirements(requirements))
2019-07-22 15:58:18.793905 | ubuntu-bionic |   File "/home/zuul/src/opendev.org/openstack/requirements/.tox/py27-check-uc/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 791, in resolve
2019-07-22 15:58:18.794040 | ubuntu-bionic |     raise VersionConflict(dist, req).with_context(dependent_req)
```

**Comment by swetashre** [comment]
@prometheanfire - Thank you for your post. I will mark this as a feature request, pending until there is at least a py2 & py3 wheel for the docutils latest version.

**Comment by prometheanfire** [comment]
So you are looking for a py3 wheel?  (looks like there is one for 0.15.1 py2)

https://pypi.org/project/docutils/#files

**Comment by swetashre** [comment]
@prometheanfire - Yes we are waiting for py3 wheel as currently they have only py2.

**Comment by prometheanfire** [comment]
ya, I mailed their dev list about it as well.  it may be a pip error that it can't find and use the tarball though.

**Comment by prometheanfire** [comment]
looks like they released 0.15.2 today

**Comment by enys** [comment]
Indeed they py3 wheel seems available now : https://files.pythonhosted.org/packages/22/cd/a6aa959dca619918ccb55023b4cb151949c64d4d5d55b3f4ffd7eee0c6e8/docutils-0.15.2-py3-none-any.whl

**Comment by enys** [comment]
@swetashre Is there a way I could help resolving this ?
Thanks,

**Comment by stealthycoin** [comment]
This was merged and a release has been cut since then.

**Comment by enys** [comment]
Thanks @stealthycoin
