### ISSUE TITLE
Invalid endpoint in create_endpoint

### ISSUE THREAD

**Issue by leftkats** [boto/botocore#1825]
**System information**

- Python 3.6.8
- boto3==1.9.225
- botocore==1.12.227
- awscli==1.16.237
- apache-airflow==1.10.4

Function that throws the error possibly here:
https://github.com/boto/botocore/blob/develop/botocore/utils.py#L832-L853

aws-cli configured correctly at the machine.
I am getting the following error while i am trying to interact with aws from apache-airflow operator:

Can you please share a valid endpoint example?
```Traceback (most recent call last):
  File "/home/airflow/devenv/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 922, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/airflow/devenv/lib/python3.6/site-packages/airflow/sensors/base_sensor_operator.py", line 107, in execute
    while not self.poke(context):
  File "/home/airflow/bi/airflow/plugins/bq_ef_gr_plugin.py", line 429, in poke
    exists = hook.check_for_key(self.bucket_key, self.bucket_name)
  File "/home/airflow/devenv/lib/python3.6/site-packages/airflow/hooks/S3_hook.py", line 198, in check_for_key
    self.get_conn().head_object(Bucket=bucket_name, Key=key)
  File "/home/airflow/devenv/lib/python3.6/site-packages/airflow/hooks/S3_hook.py", line 36, in get_conn
    return self.get_client_type('s3')
  File "/home/airflow/devenv/lib/python3.6/site-packages/airflow/contrib/hooks/aws_hook.py", line 170, in get_client_type
    config=config, verify=self.verify)
  File "/home/airflow/devenv/lib/python3.6/site-packages/boto3/session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "/home/airflow/devenv/lib/python3.6/site-packages/botocore/session.py", line 839, in create_client
    client_config=config, api_version=api_version)
  File "/home/airflow/devenv/lib/python3.6/site-packages/botocore/client.py", line 86, in create_client
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/home/airflow/devenv/lib/python3.6/site-packages/botocore/client.py", line 328, in _get_client_args
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/home/airflow/devenv/lib/python3.6/site-packages/botocore/args.py", line 85, in get_client_args
    client_cert=new_config.client_cert)
  File "/home/airflow/devenv/lib/python3.6/site-packages/botocore/endpoint.py", line 261, in create_endpoint
    raise ValueError("Invalid endpoint: %s" % endpoint_url)
ValueError: Invalid endpoint: s3.eu-central-1.amazonaws.com

**Comment by leftkats** [comment]
Hello @swetashre,

aws_conn_id = 'the_S3_connectioin_ID_which_is_configured_for_apache-airflow'
bucket_key = ' the_relative_path_to_a_file '
bucket_name = ' the_S3_bucket_name '

Credentials file looks like this 
[default]
aws_access_key_id = 
aws_secret_access_key = 

[profile1]
aws_access_key_id = 
aws_secret_access_key = 
host = s3.eu-central-1.amazonaws.com

I have tried to remove the host key from credentials and re-configure the aws-cli. Got again the same error as mentioned above.

```    
        from airflow.hooks.S3_hook import S3Hook

        hook = S3Hook(s3_conn_id=aws_conn_id)

        exists = hook.check_for_key(bucket_key, bucket_name)
