### ISSUE TITLE
Exceptions under python2 cannot handle non-ascii characters in error messages

### ISSUE THREAD

**Issue by aacampbell** [boto/botocore#1849]
When running under python2, an exception that has a message that contains non-ascii characters (i.e. ord > 128) will cause the exception to not have its message. This makes distinguishing between different 'types' of the same class of exception difficult, if not impossible.

This is what it looks like:
```
$ python2
Python 2.7.15+ (default, Oct  7 2019, 17:39:04) 
[GCC 7.4.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import boto3
>>> client = boto3.client('secretsmanager')
>>> client.get_secret_value(SecretId='bogus')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/acampbell/.local/lib/python2.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/acampbell/.local/lib/python2.7/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ResourceNotFoundException: <exception str() failed>
>>> 
```
For comparison, here is it working just fine under python3:
```
$ python3
Python 3.6.8 (default, Oct  7 2019, 12:59:55) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import boto3
>>> client = boto3.client('secretsmanager')
>>> client.get_secret_value(SecretId='bogus')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/acampbell/.local/lib/python3.6/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/acampbell/.local/lib/python3.6/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the GetSecretValue operation: Secrets Manager can’t find the specified secret.
>>> 
```
The issue is the apostrophe in "can't". It's essentially doing this:
```
$ python2
Python 2.7.15+ (default, Oct  7 2019, 17:39:04) 
[GCC 7.4.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> s = u"Secrets Manager can’t find the specified secret."
>>> s
u'Secrets Manager can\u2019t find the specified secret.'
>>> print s
Secrets Manager can’t find the specified secret.
>>> str(s)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 19: ordinal not in range(128)
>>> 
```
One can work around all this by directly accessing the error's response dictionary, it is not unreasonable that one would expect calling `str()` on the error to work correctly.

**Comment by swetashre** [comment]
@aacampbell - Thank you for your post. I can confirm this is a issue in python 2. Marking it as a bug.

**Comment by nateprewitt** [comment]
Given that we've ended support for Python 2.7 on July 15, 2021, it appears this bug is no longer relevant. I'm going to close as won't fix. Thanks for the report though!
