### ISSUE TITLE
An HTTP Client raised and unhandled exception: 'requestid'

### ISSUE THREAD

**Issue by msambol** [boto/botocore#1850]
I'm getting the following error when using the S3 boto3 client.
I'm using the default version of boto3 included with Lambda in `us-west-2`.
The error isn't unique to the S3 client, it's also happening with others such as ssm.

**CODE**
```
s3_client = boto3.client('s3')
s3_obj = s3_client.get_object(Bucket="bucket", Key="key")
```
**ERROR**
```
[b51db6dc-a396-40c2-befb-b947a6e95e55][2019-10-17 03:28:07,481][ERROR] An HTTP Client raised and unhandled exception: 'requestid'
Traceback (most recent call last):
File "/var/runtime/botocore/httpsession.py", line 262, in send
chunked=self._chunked(request.headers),
File "/var/runtime/urllib3/connectionpool.py", line 547, in urlopen
retries = Retry.from_int(retries, redirect=redirect, default=self.retries)
File "/var/runtime/urllib3/util/retry.py", line 211, in from_int
log.debug("Converted retries value: %r -> %r", retries, new_retries)
File "/var/lang/lib/python3.7/logging/__init__.py", line 1366, in debug
self._log(DEBUG, msg, args, **kwargs)
File "/var/lang/lib/python3.7/logging/__init__.py", line 1514, in _log
self.handle(record)
File "/var/lang/lib/python3.7/logging/__init__.py", line 1524, in handle
self.callHandlers(record)
File "/var/lang/lib/python3.7/logging/__init__.py", line 1586, in callHandlers
hdlr.handle(record)
File "/var/lang/lib/python3.7/logging/__init__.py", line 894, in handle
self.emit(record)
File "/var/runtime/bootstrap.py", line 243, in emit
msg = self.format(record)
File "/var/lang/lib/python3.7/logging/__init__.py", line 869, in format
return fmt.format(record)
File "/var/lang/lib/python3.7/logging/__init__.py", line 611, in format
s = self.formatMessage(record)
File "/var/lang/lib/python3.7/logging/__init__.py", line 580, in formatMessage
return self._style.format(record)
File "/var/lang/lib/python3.7/logging/__init__.py", line 422, in format
return self._fmt % record.__dict__
KeyError: 'requestid'
```

**Comment by msambol** [comment]
I'm still seeing this bug. It has something to do with this code:
```
mainlogger = logging.getLogger()
mainlogger.setLevel(loglevel)
logging.getLogger('boto3').setLevel(botolevel)
logging.getLogger('botocore').setLevel(botolevel)
```

**Comment by smoghal** [comment]
I ran into the same problem.  I was trying to use custom resources using lambda function.  Lambda function used the following code for log configuration (this was part of an older `crhelper.py` file):

```
def log_config(event, loglevel=None, botolevel=None):
    if 'ResourceProperties' in event.keys():
        if 'loglevel' in event['ResourceProperties'] and not loglevel:
            loglevel = event['ResourceProperties']['loglevel']
        if 'botolevel' in event['ResourceProperties'] and not botolevel:
            botolevel = event['ResourceProperties']['botolevel']
    if not loglevel:
        loglevel = 'warning'
    if not botolevel:
        botolevel = 'error'
    # Set log verbosity levels
    loglevel = getattr(logging, loglevel.upper(), 20)
    botolevel = getattr(logging, botolevel.upper(), 40)
    mainlogger = logging.getLogger()
    mainlogger.setLevel(loglevel)
    logging.getLogger('boto3').setLevel(botolevel)
    logging.getLogger('botocore').setLevel(botolevel)
    # Set log message format
    logfmt = '[%(requestid)s][%(asctime)s][%(levelname)s] %(message)s \n'
    mainlogger.handlers[0].setFormatter(logging.Formatter(logfmt))
    return logging.LoggerAdapter(mainlogger, {'requestid': event['RequestId']})
```

I switched over to using the custom resource helper mention in [aws blog](https://aws.amazon.com/blogs/infrastructure-and-automation/aws-cloudformation-custom-resource-creation-with-python-aws-lambda-and-crhelper/)  post.  And I managed to make things work.  Here's my [sample code](https://github.com/smoghal/cognito-custom-resources).

**Comment by swetashre** [comment]
@msambol - Thank you for your post. Can you please give me full debug log ? I want to know what is the response you are getting from service. You can enable debug log by adding ```boto3.set_stream_logger('')``` to your code. 

And as you mentioned you are getting error with even ssm, it would be helpful if you can provide the debug logs for that service as well.
