### ISSUE TITLE
Unable to Assume WebIdentity Role - EKS IRSA

### ISSUE THREAD

**Issue by BastianM3** [boto/botocore#2003]
**A description of the problem/suggestion:**

I was working with a developer on getting their containerized app running in EKS, whereby we're assigning a role to the service account which has adequate permissions to interact with SNS.

After much tinkering, we were able to isolate the issue to a specific version of botocore:

```
1.13.26 - failed
1.13.25 - failed
1.13.20 - failed
1.13.0 - failed
1.12.229 - failed
1.12.210 - failed
1.12.200 - failed <-- this release
1.12.199 - worked
1.12.195 - worked
1.12.188 - worked
1.12.187 - worked
1.12.170 - worked
1.12.137 - worked
```

For now, we're pinning botocore to 1.12.199 but we're not exactly sure why it doesn't work with newer versions. We were originally using the traditional boto3 way of interacting with SNS, but I revised to use botocore to try'n isolate the issue.

**A code sample that demonstrates the issue:**

```
import botocore.session
session = botocore.session.get_session()
sns = session.create_client('sns', region_name='us-west-2')
sns.publish(TopicArn='arn:aws:sns:us-west-2:ACCT_ID:TOPIC_NAME',Message='{"msg":"Testingboto"}')
```

When using botocore>=1.12.200:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.8/site-packages/botocore/client.py", line 612, in _make_api_call
    http, parsed_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/botocore/client.py", line 632, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/usr/local/lib/python3.8/site-packages/botocore/endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "/usr/local/lib/python3.8/site-packages/botocore/endpoint.py", line 132, in _send_request
    request = self.create_request(request_dict, operation_model)
  File "/usr/local/lib/python3.8/site-packages/botocore/endpoint.py", line 115, in create_request
    self._event_emitter.emit(event_name, request=request,
  File "/usr/local/lib/python3.8/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/usr/local/lib/python3.8/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/botocore/signers.py", line 90, in handler
    return self.sign(operation_name, request)
  File "/usr/local/lib/python3.8/site-packages/botocore/signers.py", line 152, in sign
    auth = self.get_auth_instance(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/botocore/signers.py", line 232, in get_auth_instance
    frozen_credentials = self._credentials.get_frozen_credentials()
  File "/usr/local/lib/python3.8/site-packages/botocore/credentials.py", line 591, in get_frozen_credentials
    self._refresh()
  File "/usr/local/lib/python3.8/site-packages/botocore/credentials.py", line 486, in _refresh
    self._protected_refresh(is_mandatory=is_mandatory_refresh)
  File "/usr/local/lib/python3.8/site-packages/botocore/credentials.py", line 502, in _protected_refresh
    metadata = self._refresh_using()
  File "/usr/local/lib/python3.8/site-packages/botocore/credentials.py", line 643, in fetch_credentials
    return self._get_cached_credentials()
  File "/usr/local/lib/python3.8/site-packages/botocore/credentials.py", line 653, in _get_cached_credentials
    response = self._get_credentials()
  File "/usr/local/lib/python3.8/site-packages/botocore/credentials.py", line 863, in _get_credentials
    return client.assume_role_with_web_identity(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.8/site-packages/botocore/client.py", line 626, in _make_api_call
    raise error_class(parsed_response, operation_name)

botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the AssumeRoleWithWebIdentity operation: Not authorized to perform sts:AssumeRoleWithWebIdentity
```

```
import botocore.session
session = botocore.session.get_session()
sns = session.create_client('sns', region_name='us-west-2')

sns.publish(TopicArn='arn:aws:sns:us-west-2:ACCT_ID:TOPIC_NAME',Message='{"msg":"Testingboto"}')
{'MessageId': 'f6aeca32-2500-56dc-b109-9cc7e053e670', 'ResponseMetadata': {'RequestId': '57a323c1-e9c3-542a-9607-75342c90c486', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': '57a323c1-e9c3-542a-9607-75342c90c486', 'content-type': 'text/xml', 'content-length': '294', 'date': 'Wed, 25 Mar 2020 20:46:10 GMT'}, 'RetryAttempts': 0}}
```

It's worth noting that it works fine using awscli when installing via apt-get, but NOT via pip.

**Including the versions of your:**

**python interpreter:** 3.8

**OS:** `FROM python:3.8-buster` (was able to reproduce in other container images too)

**Version of botocore:** anything >1.12.199

**Comment by swetashre** [comment]
Thank you for the post. What credential provider are you expecting to be used and how are you getting credentials for earlier versions ?

In botocore version 1.12.200, AssumeRoleWithWebIdentity credential provider was added. It’s specifically added for the EKS use case. This provider required the execution environment to be setup so that SDK will pick up on those credentials via AssumeRoleWithWebIdentity.  

This blog post describes the credential provider and how to set it up:
https://aws.amazon.com/blogs/opensource/introducing-fine-grained-iam-roles-service-accounts/
