### ISSUE TITLE
Connection was closed before we received a valid response from endpoint URL: "https://queue.amazonaws.com/"

### ISSUE THREAD

**Issue by alseambusher** [boto/botocore#2014]
I am using boto3 to work with sqs. 
```python
sqs = boto3.client("sqs")
...
...
sqs.send_message(QueueUrl=..., MessageBody=...)
```

I am seeing this behavior all the time when I call `send_message` and would appreciate any feedback.

- Boto creates a payload for POST to AWS and sends it to https://queue.amazonaws.com/
- Boto is unable to connect to https://queue.amazonaws.com/ and closes with “'Remote end closed connection without response” in 4-5ms
- Boto then decides to sleep for a random amount of time.
- It then wakes up to make the same POST call to AWS and does it successfully.

```
'User-Agent': b'Boto3/1.12.39 Python/3.5.2 Linux/4.14.88-coreos Botocore/1.15.39'
```

Here is the stacktrace:
```
2020-04-10 15:39:25,248 - botocore.hooks - DEBUG - _emit - request_id=VdzaLibhiVABXKnhacEjljpD0tzN1TLP MainProcess MainThread Event needs-retry.sqs.SendMessage: calling handler <botocore.retryhandler.RetryHandler object at 0x7f744433a048>
2020-04-10 15:39:25,248 - botocore.retryhandler - DEBUG - _should_retry - request_id=VdzaLibhiVABXKnhacEjljpD0tzN1TLP MainProcess MainThread retry needed, retryable exception caught: Connection was closed before we received a valid response from endpoint URL: "https://queue.amazonaws.com/".
Traceback (most recent call last):
  File "/app/python/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/app/python/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/app/python/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/python/botocore/httpsession.py", line 263, in send
    chunked=self._chunked(request.headers),
  File "/app/python/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/app/python/urllib3/util/retry.py", line 376, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/app/python/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/app/python/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/app/python/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/app/python/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/python/botocore/retryhandler.py", line 269, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/app/python/botocore/retryhandler.py", line 317, in __call__
    caught_exception)
  File "/app/python/botocore/retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "/app/python/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
  File "/app/python/botocore/endpoint.py", line 200, in _do_get_response
    http_response = self._send(request)
  File "/app/python/botocore/endpoint.py", line 244, in _send
    return self.http_session.send(request)
  File "/app/python/botocore/httpsession.py", line 294, in send
    endpoint_url=request.url
botocore.exceptions.ConnectionClosedError: Connection was closed before we received a valid response from endpoint URL: "https://queue.amazonaws.com/".
2020-04-10 15:39:25,251 - botocore.retryhandler - DEBUG - __call__ - request_id=VdzaLibhiVABXKnhacEjljpD0tzN1TLP MainProcess MainThread Retry needed, action of: 0.3506498769046176
2020-04-10 15:39:25,251 - botocore.endpoint - DEBUG - _needs_retry - request_id=VdzaLibhiVABXKnhacEjljpD0tzN1TLP MainProcess MainThread Response received to retry, sleeping for 0.3506498769046176 seconds
```

**Comment by alseambusher** [comment]
More context:
The same `boto3.client` object is used in 2 `Process` one for changing message visibility timeout and one to send message. And it looks like this problem goes away if I have single process doing it. Can you guide me how to use multi processes with the same client?

**Comment by swetashre** [comment]
@alseambusher - Thank you for your post. This error occurs when service closes the connection for any reason. Can you provide me code sample on how you are using same boto3 client for multiprocess ?

**Comment by alseambusher** [comment]
Thank you 👍
