### ISSUE TITLE
TypeError: can't subtract offset-naive and offset-aware datetimes

### ISSUE THREAD

**Issue by leezu** [boto/botocore#2044]
**Describe the bug**
After removing a plugin based authentication mechanism, botocore throws the following error upon any operation.

```
2020-05-08 20:20:38,226 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/1.18.56 Python/3.8.0 Linux/5.6.7 botocore/1.16.6
2020-05-08 20:20:38,227 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['s3', 'ls', '--debug']
2020-05-08 20:20:38,227 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_scalar_parsers at 0x7f82bb318870>
2020-05-08 20:20:38,227 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function register_uri_param_handler at 0x7f82bc30a190>
2020-05-08 20:20:38,228 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x7f82bc2c9870>
2020-05-08 20:20:38,233 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function attach_history_handler at 0x7f82bb51cf50>
2020-05-08 20:20:38,233 - MainThread - botocore.hooks - DEBUG - Event building-command-table.s3: calling handler <function add_waiters at 0x7f82bb326230>
2020-05-08 20:20:38,235 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.s3.anonymous: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f82bb2206e0>
2020-05-08 20:20:38,236 - MainThread - botocore.hooks - DEBUG - Event building-command-table.ls: calling handler <function add_waiters at 0x7f82bb326230>
2020-05-08 20:20:38,238 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.ls.paths: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f82bb2206e0>
2020-05-08 20:20:38,239 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.ls.anonymous: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f82bb2206e0>
2020-05-08 20:20:38,239 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.ls.page-size: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f82bb2206e0>
2020-05-08 20:20:38,240 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.ls.human-readable: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f82bb2206e0>
2020-05-08 20:20:38,240 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.ls: calling handler <awscli.argprocess.ParamShorthandParser object at 0x7f82bc3085f0>
2020-05-08 20:20:38,241 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.ls.summarize: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f82bb2206e0>
2020-05-08 20:20:38,241 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.ls: calling handler <awscli.argprocess.ParamShorthandParser object at 0x7f82bc3085f0>
2020-05-08 20:20:38,242 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.ls.request-payer: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f82bb2206e0>
2020-05-08 20:20:38,242 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: env
2020-05-08 20:20:38,242 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role
2020-05-08 20:20:38,242 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role-with-web-identity
2020-05-08 20:20:38,243 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: shared-credentials-file
2020-05-08 20:20:38,243 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: custom-process
2020-05-08 20:20:38,394 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /home/ANT.AMAZON.COM/lausen/.pyenv/versions/3.8.0-debug/lib/python3.8/site-packages/botocore/data/endpoints.json
2020-05-08 20:20:38,436 - MainThread - botocore.hooks - DEBUG - Event choose-service-name: calling handler <function handle_service_name_alias at 0x7f82bd584550>
2020-05-08 20:20:38,440 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /home/ANT.AMAZON.COM/lausen/.pyenv/versions/3.8.0-debug/lib/python3.8/site-packages/botocore/data/s3/2006-03-01/service-2.json
2020-05-08 20:20:38,468 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.s3: calling handler <function add_generate_presigned_post at 0x7f82bd5ceeb0>
2020-05-08 20:20:38,468 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.s3: calling handler <function add_generate_presigned_url at 0x7f82bd5cec30>
2020-05-08 20:20:38,482 - MainThread - botocore.endpoint - DEBUG - Setting s3 timeout as (60, 60)
2020-05-08 20:20:38,484 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /home/ANT.AMAZON.COM/lausen/.pyenv/versions/3.8.0-debug/lib/python3.8/site-packages/botocore/data/_retry.json
2020-05-08 20:20:38,485 - MainThread - botocore.client - DEBUG - Registering retry handlers for service: s3
2020-05-08 20:20:38,490 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.s3.ListBuckets: calling handler <function validate_bucket_name at 0x7f82bd54e230>
2020-05-08 20:20:38,490 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.s3.ListBuckets: calling handler <bound method S3RegionRedirector.redirect_from_cache of <botocore.utils.S3RegionRedirector object at 0x7f82baf86c80>>
2020-05-08 20:20:38,490 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.s3.ListBuckets: calling handler <bound method S3ArnParamHandler.handle_arn of <botocore.utils.S3ArnParamHandler object at 0x7f82baf1f140>>
2020-05-08 20:20:38,490 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.s3.ListBuckets: calling handler <function generate_idempotent_uuid at 0x7f82bd549d70>
2020-05-08 20:20:38,491 - MainThread - botocore.hooks - DEBUG - Event before-call.s3.ListBuckets: calling handler <function add_expect_header at 0x7f82bd54e5f0>
2020-05-08 20:20:38,491 - MainThread - botocore.hooks - DEBUG - Event before-call.s3.ListBuckets: calling handler <bound method S3RegionRedirector.set_request_url of <botocore.utils.S3RegionRedirector object at 0x7f82baf86c80>>
2020-05-08 20:20:38,491 - MainThread - botocore.hooks - DEBUG - Event before-call.s3.ListBuckets: calling handler <function inject_api_version_header_if_needed at 0x7f82bd54fb90>
2020-05-08 20:20:38,491 - MainThread - botocore.endpoint - DEBUG - Making request for OperationModel(name=ListBuckets) with params: {'url_path': '/', 'query_string': '', 'method': 'GET', 'headers': {'User-Agent': 'aws-cli/1.18.56 Python/3.8.0 Linux/5.6.7 botocore/1.16.6'}, 'body': b'', 'url': 'https://s3.amazonaws.com/', 'context': {'client_region': 'us-east-1', 'client_config': <botocore.config.Config object at 0x7f82baf86050>, 'has_streaming_input': False, 'auth_type': None, 'signing': {'bucket': None}}}
2020-05-08 20:20:38,492 - MainThread - botocore.hooks - DEBUG - Event request-created.s3.ListBuckets: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x7f82baf80fa0>>
2020-05-08 20:20:38,492 - MainThread - botocore.hooks - DEBUG - Event choose-signer.s3.ListBuckets: calling handler <bound method ClientCreator._default_s3_presign_to_sigv2 of <botocore.client.ClientCreator object at 0x7f82bb217a50>>
2020-05-08 20:20:38,492 - MainThread - botocore.hooks - DEBUG - Event choose-signer.s3.ListBuckets: calling handler <function set_operation_specific_signer at 0x7f82bd549c30>
2020-05-08 20:20:38,493 - MainThread - botocore.hooks - DEBUG - Event before-sign.s3.ListBuckets: calling handler <bound method S3EndpointSetter.set_endpoint of <botocore.utils.S3EndpointSetter object at 0x7f82baf1f1e0>>
2020-05-08 20:20:38,493 - MainThread - botocore.utils - DEBUG - Defaulting to S3 virtual host style addressing with path style addressing fallback.
2020-05-08 20:20:38,494 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "/home/ANT.AMAZON.COM/lausen/.pyenv/versions/3.8.0-debug/lib/python3.8/site-packages/awscli/clidriver.py", line 217, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/home/ANT.AMAZON.COM/lausen/.pyenv/versions/3.8.0-debug/lib/python3.8/site-packages/awscli/customizations/commands.py", line 189, in __call__
    return self.subcommand_table[parsed_args.subcommand](remaining,
  File "/home/ANT.AMAZON.COM/lausen/.pyenv/versions/3.8.0-debug/lib/python3.8/site-packages/awscli/customizations/commands.py", line 187, in __call__
    return self._run_main(parsed_args, parsed_globals)
  File "/home/ANT.AMAZON.COM/lausen/.pyenv/versions/3.8.0-debug/lib/python3.8/site-packages/awscli/customizations/s3/subcommands.py", line 478, in _run_main
    self._list_all_buckets()
  File "/home/ANT.AMAZON.COM/lausen/.pyenv/versions/3.8.0-debug/lib/python3.8/site-packages/awscli/customizations/s3/subcommands.py", line 543, in _list_all_buckets
    response_data = self.client.list_buckets()
  File "/home/ANT.AMAZON.COM/lausen/.pyenv/versions/3.8.0-debug/lib/python3.8/site-packages/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ANT.AMAZON.COM/lausen/.pyenv/versions/3.8.0-debug/lib/python3.8/site-packages/botocore/client.py", line 612, in _make_api_call
    http, parsed_response = self._make_request(
  File "/home/ANT.AMAZON.COM/lausen/.pyenv/versions/3.8.0-debug/lib/python3.8/site-packages/botocore/client.py", line 632, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/home/ANT.AMAZON.COM/lausen/.pyenv/versions/3.8.0-debug/lib/python3.8/site-packages/botocore/endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "/home/ANT.AMAZON.COM/lausen/.pyenv/versions/3.8.0-debug/lib/python3.8/site-packages/botocore/endpoint.py", line 132, in _send_request
    request = self.create_request(request_dict, operation_model)
  File "/home/ANT.AMAZON.COM/lausen/.pyenv/versions/3.8.0-debug/lib/python3.8/site-packages/botocore/endpoint.py", line 115, in create_request
    self._event_emitter.emit(event_name, request=request,
  File "/home/ANT.AMAZON.COM/lausen/.pyenv/versions/3.8.0-debug/lib/python3.8/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/home/ANT.AMAZON.COM/lausen/.pyenv/versions/3.8.0-debug/lib/python3.8/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/home/ANT.AMAZON.COM/lausen/.pyenv/versions/3.8.0-debug/lib/python3.8/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/home/ANT.AMAZON.COM/lausen/.pyenv/versions/3.8.0-debug/lib/python3.8/site-packages/botocore/signers.py", line 90, in handler
    return self.sign(operation_name, request)
  File "/home/ANT.AMAZON.COM/lausen/.pyenv/versions/3.8.0-debug/lib/python3.8/site-packages/botocore/signers.py", line 152, in sign
    auth = self.get_auth_instance(**kwargs)
  File "/home/ANT.AMAZON.COM/lausen/.pyenv/versions/3.8.0-debug/lib/python3.8/site-packages/botocore/signers.py", line 232, in get_auth_instance
    frozen_credentials = self._credentials.get_frozen_credentials()
  File "/home/ANT.AMAZON.COM/lausen/.pyenv/versions/3.8.0-debug/lib/python3.8/site-packages/botocore/credentials.py", line 591, in get_frozen_credentials
    self._refresh()
  File "/home/ANT.AMAZON.COM/lausen/.pyenv/versions/3.8.0-debug/lib/python3.8/site-packages/botocore/credentials.py", line 473, in _refresh
    if not self.refresh_needed(self._advisory_refresh_timeout):
  File "/home/ANT.AMAZON.COM/lausen/.pyenv/versions/3.8.0-debug/lib/python3.8/site-packages/botocore/credentials.py", line 459, in refresh_needed
    if self._seconds_remaining() >= refresh_in:
  File "/home/ANT.AMAZON.COM/lausen/.pyenv/versions/3.8.0-debug/lib/python3.8/site-packages/botocore/credentials.py", line 428, in _seconds_remaining
    delta = self._expiry_time - self._time_fetcher()
TypeError: can't subtract offset-naive and offset-aware datetimes
2020-05-08 20:20:38,499 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255

can't subtract offset-naive and offset-aware datetimes
```

**Comment by leezu** [comment]
This issue may have been due to having two different versions of botocore. One in the pyenv, the other with system python
