### ISSUE TITLE
Stubber multiple add_response

### ISSUE THREAD

**Issue by aledeganopix4d** [boto/botocore#2069]
**Describe the bug**
According to the Stubber documentation, when calling `add_response` multiple times, those responses go in FIFO stack, ready to be pulled off one-by-one when the corresponding method is called (https://botocore.amazonaws.com/v1/documentation/api/latest/reference/stubber.html#botocore.stub.Stubber).

This is not the case, and the **last** inserted element is always returned.

**Steps to reproduce**
Consider this simple script heavily based on the documentation example.
Running on Python 3.8 and botocore 0.16.24:
```python
import boto3
import datetime

from botocore.stub import Stubber


response = {
    "IsTruncated": False,
    "Name": "",
    "MaxKeys": 1000,
    "Prefix": "",
    "Contents": [
        {
            "Key": "test.txt",
            "ETag": '"abc123"',
            "StorageClass": "STANDARD",
            "LastModified": datetime.datetime(2016, 1, 20, 22, 9),
            "Owner": {"ID": "abc123", "DisplayName": "myname"},
            "Size": 14814,
        }
    ],
    "EncodingType": "url",
    "ResponseMetadata": {"RequestId": "abc123", "HTTPStatusCode": 200, "HostId": "abc123"},
    "Marker": "",
}


s3 = boto3.client("s3")
stubber = Stubber(s3)
for i in range(5):
    response["Name"] = f"bucket_{i}"
    expected_params = {"Bucket": f"bucket_{i}"}
    print("Adding response: ", response)
    stubber.add_response("list_objects", response, expected_params)
stubber.activate()
for i in range(5):
    print(s3.list_objects(Bucket=f"bucket_{i}")["Name"])
```
It outputs:
```
bucket_4
bucket_4
bucket_4
bucket_4
bucket_4
```
**Expected behavior**
I would expect that every time a `s3.list_objects` is called, one of the response is returned and then **popped** from the responses stack. That doesn't seem to be the case however.

**Debug logs**
```
2020-06-08 06:40:05,264 - botocore.hooks - DEBUG - Changing event name from creating-client-class.iot-data to creating-client-class.iot-data-plane
2020-06-08 06:40:05,268 - botocore.hooks - DEBUG - Changing event name from before-call.apigateway to before-call.api-gateway
2020-06-08 06:40:05,270 - botocore.hooks - DEBUG - Changing event name from request-created.machinelearning.Predict to request-created.machine-learning.Predict
2020-06-08 06:40:05,273 - botocore.hooks - DEBUG - Changing event name from before-parameter-build.autoscaling.CreateLaunchConfiguration to before-parameter-build.auto-scaling.CreateLaunchConfiguration
2020-06-08 06:40:05,274 - botocore.hooks - DEBUG - Changing event name from before-parameter-build.route53 to before-parameter-build.route-53
2020-06-08 06:40:05,275 - botocore.hooks - DEBUG - Changing event name from request-created.cloudsearchdomain.Search to request-created.cloudsearch-domain.Search
2020-06-08 06:40:05,276 - botocore.hooks - DEBUG - Changing event name from docs.*.autoscaling.CreateLaunchConfiguration.complete-section to docs.*.auto-scaling.CreateLaunchConfiguration.complete-section
2020-06-08 06:40:05,281 - botocore.hooks - DEBUG - Changing event name from before-parameter-build.logs.CreateExportTask to before-parameter-build.cloudwatch-logs.CreateExportTask
2020-06-08 06:40:05,281 - botocore.hooks - DEBUG - Changing event name from docs.*.logs.CreateExportTask.complete-section to docs.*.cloudwatch-logs.CreateExportTask.complete-section
2020-06-08 06:40:05,281 - botocore.hooks - DEBUG - Changing event name from before-parameter-build.cloudsearchdomain.Search to before-parameter-build.cloudsearch-domain.Search
2020-06-08 06:40:05,281 - botocore.hooks - DEBUG - Changing event name from docs.*.cloudsearchdomain.Search.complete-section to docs.*.cloudsearch-domain.Search.complete-section
2020-06-08 06:40:05,286 - botocore.credentials - DEBUG - Looking for credentials via: env
2020-06-08 06:40:05,286 - botocore.credentials - DEBUG - Looking for credentials via: assume-role
2020-06-08 06:40:05,286 - botocore.credentials - DEBUG - Looking for credentials via: assume-role-with-web-identity
2020-06-08 06:40:05,286 - botocore.credentials - DEBUG - Looking for credentials via: shared-credentials-file
2020-06-08 06:40:05,286 - botocore.credentials - DEBUG - Looking for credentials via: custom-process
2020-06-08 06:40:05,286 - botocore.credentials - DEBUG - Looking for credentials via: config-file
2020-06-08 06:40:05,286 - botocore.credentials - DEBUG - Looking for credentials via: ec2-credentials-file
2020-06-08 06:40:05,287 - botocore.credentials - DEBUG - Looking for credentials via: boto-config
2020-06-08 06:40:05,287 - botocore.credentials - DEBUG - Looking for credentials via: container-role
2020-06-08 06:40:05,287 - botocore.credentials - DEBUG - Looking for credentials via: iam-role
2020-06-08 06:40:05,287 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 169.254.169.254:80
2020-06-08 06:40:06,317 - botocore.utils - DEBUG - Caught retryable HTTP exception while making metadata service request to http://169.254.169.254/latest/api/token: Connect timeout on endpoint URL: "http://169.254.169.254/latest/api/token"
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/botocore/httpsession.py", line 254, in send
    urllib_response = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 724, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 379, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.8/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.8/http/client.py", line 1240, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.8/site-packages/botocore/awsrequest.py", line 91, in _send_request
    rval = super(AWSConnection, self)._send_request(
  File "/usr/local/lib/python3.8/http/client.py", line 1286, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1235, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.8/site-packages/botocore/awsrequest.py", line 119, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.8/site-packages/botocore/awsrequest.py", line 203, in send
    return super(AWSConnection, self).send(str)
  File "/usr/local/lib/python3.8/http/client.py", line 946, in send
    self.connect()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 187, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 164, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<botocore.awsrequest.AWSHTTPConnection object at 0x7f1f93a71130>, 'Connection to 169.254.169.254 timed out. (connect timeout=1)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/botocore/utils.py", line 299, in _fetch_metadata_token
    response = self._session.send(request.prepare())
  File "/usr/local/lib/python3.8/site-packages/botocore/httpsession.py", line 287, in send
    raise ConnectTimeoutError(endpoint_url=request.url, error=e)
botocore.exceptions.ConnectTimeoutError: Connect timeout on endpoint URL: "http://169.254.169.254/latest/api/token"
2020-06-08 06:40:06,332 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (2): 169.254.169.254:80
2020-06-08 06:40:07,340 - botocore.utils - DEBUG - Caught retryable HTTP exception while making metadata service request to http://169.254.169.254/latest/meta-data/iam/security-credentials/: Connect timeout on endpoint URL: "http://169.254.169.254/latest/meta-data/iam/security-credentials/"
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/botocore/httpsession.py", line 254, in send
    urllib_response = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 724, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 379, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.8/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.8/http/client.py", line 1240, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.8/site-packages/botocore/awsrequest.py", line 91, in _send_request
    rval = super(AWSConnection, self)._send_request(
  File "/usr/local/lib/python3.8/http/client.py", line 1286, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1235, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.8/site-packages/botocore/awsrequest.py", line 119, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.8/site-packages/botocore/awsrequest.py", line 203, in send
    return super(AWSConnection, self).send(str)
  File "/usr/local/lib/python3.8/http/client.py", line 946, in send
    self.connect()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 187, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 164, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<botocore.awsrequest.AWSHTTPConnection object at 0x7f1f93a075b0>, 'Connection to 169.254.169.254 timed out. (connect timeout=1)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/botocore/utils.py", line 342, in _get_request
    response = self._session.send(request.prepare())
  File "/usr/local/lib/python3.8/site-packages/botocore/httpsession.py", line 287, in send
    raise ConnectTimeoutError(endpoint_url=request.url, error=e)
botocore.exceptions.ConnectTimeoutError: Connect timeout on endpoint URL: "http://169.254.169.254/latest/meta-data/iam/security-credentials/"
2020-06-08 06:40:07,344 - botocore.utils - DEBUG - Max number of attempts exceeded (1) when attempting to retrieve data from metadata service.
2020-06-08 06:40:07,345 - botocore.loaders - DEBUG - Loading JSON file: /usr/local/lib/python3.8/site-packages/botocore/data/endpoints.json
2020-06-08 06:40:07,356 - botocore.hooks - DEBUG - Event choose-service-name: calling handler <function handle_service_name_alias at 0x7f1f93b87160>
2020-06-08 06:40:07,366 - botocore.loaders - DEBUG - Loading JSON file: /usr/local/lib/python3.8/site-packages/botocore/data/s3/2006-03-01/service-2.json
2020-06-08 06:40:07,379 - botocore.hooks - DEBUG - Event creating-client-class.s3: calling handler <function add_generate_presigned_post at 0x7f1f93bd0dc0>
2020-06-08 06:40:07,379 - botocore.hooks - DEBUG - Event creating-client-class.s3: calling handler <function lazy_call.<locals>._handler at 0x7f1f93a974c0>
2020-06-08 06:40:07,401 - botocore.hooks - DEBUG - Event creating-client-class.s3: calling handler <function add_generate_presigned_url at 0x7f1f93bd0b80>
2020-06-08 06:40:07,405 - botocore.endpoint - DEBUG - Setting s3 timeout as (60, 60)
2020-06-08 06:40:07,407 - botocore.loaders - DEBUG - Loading JSON file: /usr/local/lib/python3.8/site-packages/botocore/data/_retry.json
2020-06-08 06:40:07,408 - botocore.client - DEBUG - Registering retry handlers for service: s3
2020-06-08 06:40:07,412 - botocore.hooks - DEBUG - Event before-parameter-build.s3.ListObjects: calling handler <bound method Stubber._assert_expected_params of <botocore.stub.Stubber object at 0x7f1f933934c0>>
2020-06-08 06:40:07,412 - botocore.hooks - DEBUG - Event before-parameter-build.s3.ListObjects: calling handler <function set_list_objects_encoding_type_url at 0x7f1f93b33a60>
2020-06-08 06:40:07,412 - botocore.hooks - DEBUG - Event before-parameter-build.s3.ListObjects: calling handler <function validate_bucket_name at 0x7f1f93b32790>
2020-06-08 06:40:07,412 - botocore.hooks - DEBUG - Event before-parameter-build.s3.ListObjects: calling handler <bound method S3RegionRedirector.redirect_from_cache of <botocore.utils.S3RegionRedirector object at 0x7f1f93393340>>
2020-06-08 06:40:07,412 - botocore.hooks - DEBUG - Event before-parameter-build.s3.ListObjects: calling handler <bound method S3ArnParamHandler.handle_arn of <botocore.utils.S3ArnParamHandler object at 0x7f1f93393400>>
2020-06-08 06:40:07,412 - botocore.hooks - DEBUG - Event before-parameter-build.s3.ListObjects: calling handler <function generate_idempotent_uuid at 0x7f1f93b325e0>
2020-06-08 06:40:07,413 - botocore.hooks - DEBUG - Event before-call.s3.ListObjects: calling handler <bound method Stubber._get_response_handler of <botocore.stub.Stubber object at 0x7f1f933934c0>>
2020-06-08 06:40:07,413 - botocore.hooks - DEBUG - Event after-call.s3.ListObjects: calling handler <function decode_list_object at 0x7f1f93b33af0>
bucket_4
2020-06-08 06:40:07,413 - botocore.hooks - DEBUG - Event before-parameter-build.s3.ListObjects: calling handler <bound method Stubber._assert_expected_params of <botocore.stub.Stubber object at 0x7f1f933934c0>>
2020-06-08 06:40:07,413 - botocore.hooks - DEBUG - Event before-parameter-build.s3.ListObjects: calling handler <function set_list_objects_encoding_type_url at 0x7f1f93b33a60>
2020-06-08 06:40:07,413 - botocore.hooks - DEBUG - Event before-parameter-build.s3.ListObjects: calling handler <function validate_bucket_name at 0x7f1f93b32790>
2020-06-08 06:40:07,414 - botocore.hooks - DEBUG - Event before-parameter-build.s3.ListObjects: calling handler <bound method S3RegionRedirector.redirect_from_cache of <botocore.utils.S3RegionRedirector object at 0x7f1f93393340>>
2020-06-08 06:40:07,414 - botocore.hooks - DEBUG - Event before-parameter-build.s3.ListObjects: calling handler <bound method S3ArnParamHandler.handle_arn of <botocore.utils.S3ArnParamHandler object at 0x7f1f93393400>>
2020-06-08 06:40:07,414 - botocore.hooks - DEBUG - Event before-parameter-build.s3.ListObjects: calling handler <function generate_idempotent_uuid at 0x7f1f93b325e0>
2020-06-08 06:40:07,414 - botocore.hooks - DEBUG - Event before-call.s3.ListObjects: calling handler <bound method Stubber._get_response_handler of <botocore.stub.Stubber object at 0x7f1f933934c0>>
2020-06-08 06:40:07,414 - botocore.hooks - DEBUG - Event after-call.s3.ListObjects: calling handler <function decode_list_object at 0x7f1f93b33af0>
bucket_4
2020-06-08 06:40:07,415 - botocore.hooks - DEBUG - Event before-parameter-build.s3.ListObjects: calling handler <bound method Stubber._assert_expected_params of <botocore.stub.Stubber object at 0x7f1f933934c0>>
2020-06-08 06:40:07,415 - botocore.hooks - DEBUG - Event before-parameter-build.s3.ListObjects: calling handler <function set_list_objects_encoding_type_url at 0x7f1f93b33a60>
2020-06-08 06:40:07,415 - botocore.hooks - DEBUG - Event before-parameter-build.s3.ListObjects: calling handler <function validate_bucket_name at 0x7f1f93b32790>
2020-06-08 06:40:07,415 - botocore.hooks - DEBUG - Event before-parameter-build.s3.ListObjects: calling handler <bound method S3RegionRedirector.redirect_from_cache of <botocore.utils.S3RegionRedirector object at 0x7f1f93393340>>
2020-06-08 06:40:07,415 - botocore.hooks - DEBUG - Event before-parameter-build.s3.ListObjects: calling handler <bound method S3ArnParamHandler.handle_arn of <botocore.utils.S3ArnParamHandler object at 0x7f1f93393400>>
2020-06-08 06:40:07,415 - botocore.hooks - DEBUG - Event before-parameter-build.s3.ListObjects: calling handler <function generate_idempotent_uuid at 0x7f1f93b325e0>
2020-06-08 06:40:07,415 - botocore.hooks - DEBUG - Event before-call.s3.ListObjects: calling handler <bound method Stubber._get_response_handler of <botocore.stub.Stubber object at 0x7f1f933934c0>>
2020-06-08 06:40:07,415 - botocore.hooks - DEBUG - Event after-call.s3.ListObjects: calling handler <function decode_list_object at 0x7f1f93b33af0>
bucket_4
2020-06-08 06:40:07,416 - botocore.hooks - DEBUG - Event before-parameter-build.s3.ListObjects: calling handler <bound method Stubber._assert_expected_params of <botocore.stub.Stubber object at 0x7f1f933934c0>>
2020-06-08 06:40:07,416 - botocore.hooks - DEBUG - Event before-parameter-build.s3.ListObjects: calling handler <function set_list_objects_encoding_type_url at 0x7f1f93b33a60>
2020-06-08 06:40:07,416 - botocore.hooks - DEBUG - Event before-parameter-build.s3.ListObjects: calling handler <function validate_bucket_name at 0x7f1f93b32790>
2020-06-08 06:40:07,416 - botocore.hooks - DEBUG - Event before-parameter-build.s3.ListObjects: calling handler <bound method S3RegionRedirector.redirect_from_cache of <botocore.utils.S3RegionRedirector object at 0x7f1f93393340>>
2020-06-08 06:40:07,416 - botocore.hooks - DEBUG - Event before-parameter-build.s3.ListObjects: calling handler <bound method S3ArnParamHandler.handle_arn of <botocore.utils.S3ArnParamHandler object at 0x7f1f93393400>>
2020-06-08 06:40:07,416 - botocore.hooks - DEBUG - Event before-parameter-build.s3.ListObjects: calling handler <function generate_idempotent_uuid at 0x7f1f93b325e0>
2020-06-08 06:40:07,417 - botocore.hooks - DEBUG - Event before-call.s3.ListObjects: calling handler <bound method Stubber._get_response_handler of <botocore.stub.Stubber object at 0x7f1f933934c0>>
2020-06-08 06:40:07,417 - botocore.hooks - DEBUG - Event after-call.s3.ListObjects: calling handler <function decode_list_object at 0x7f1f93b33af0>
bucket_4
2020-06-08 06:40:07,417 - botocore.hooks - DEBUG - Event before-parameter-build.s3.ListObjects: calling handler <bound method Stubber._assert_expected_params of <botocore.stub.Stubber object at 0x7f1f933934c0>>
2020-06-08 06:40:07,417 - botocore.hooks - DEBUG - Event before-parameter-build.s3.ListObjects: calling handler <function set_list_objects_encoding_type_url at 0x7f1f93b33a60>
2020-06-08 06:40:07,417 - botocore.hooks - DEBUG - Event before-parameter-build.s3.ListObjects: calling handler <function validate_bucket_name at 0x7f1f93b32790>
2020-06-08 06:40:07,418 - botocore.hooks - DEBUG - Event before-parameter-build.s3.ListObjects: calling handler <bound method S3RegionRedirector.redirect_from_cache of <botocore.utils.S3RegionRedirector object at 0x7f1f93393340>>
2020-06-08 06:40:07,418 - botocore.hooks - DEBUG - Event before-parameter-build.s3.ListObjects: calling handler <bound method S3ArnParamHandler.handle_arn of <botocore.utils.S3ArnParamHandler object at 0x7f1f93393400>>
2020-06-08 06:40:07,418 - botocore.hooks - DEBUG - Event before-parameter-build.s3.ListObjects: calling handler <function generate_idempotent_uuid at 0x7f1f93b325e0>
2020-06-08 06:40:07,418 - botocore.hooks - DEBUG - Event before-call.s3.ListObjects: calling handler <bound method Stubber._get_response_handler of <botocore.stub.Stubber object at 0x7f1f933934c0>>
2020-06-08 06:40:07,418 - botocore.hooks - DEBUG - Event after-call.s3.ListObjects: calling handler <function decode_list_object at 0x7f1f93b33af0>
bucket_4
```

** Final note **
Have I been interpreting the documentation wrongly? Maybe my expectation is not correct.
Anyway thanks for acknowledging my issue.

**Comment by aledeganopix4d** [comment]
> @aledeganopix4d - Thank you for your post. I am able to reproduce the issue. The problem here is that if you change any attribute of response then the whole response will get updated even the responses that are already in the queue. So in this case when you are changing the name of the response all the response names are getting updated. That's why every time you are getting output as bucket_4.
> 
> I am marking this as bug. But in the mean time you can get it to work by adding this line `service_response = service_response.copy()` to your `stub.py` file inside `_add_response` function:
> https://github.com/boto/botocore/blob/develop/botocore/stub.py#L240

Thank you!

**Comment by swetashre** [comment]
@aledeganopix4d - With the proposed change to the code base we could potentially break customers. So here i would recommend either copy or cast the response with dict() for each add_response call. 
Something like this in your code before add_response call:
```
response = response.copy() 
or 
response = dict(response)
```
Sorry for the inconvenience.

**Comment by aledeganopix4d** [comment]
@swetashre - Thank you for your feedback. I have still few comments:

1. The solution that you propose above does indeed solve the issue in the piece of example code I have posted in the original comment, but...
2. For some reason it does **not** work when applying it to the `batch` stubber for the `describe_jobs` call:
```python
#!/bin/python
import boto3
import datetime

from botocore.stub import Stubber

response = {
    "jobs": [
        {
            "jobName": "job_name",
            "jobId": "job_id",
            "jobQueue": "job_queue",
            "startedAt": 123,
            "jobDefinition": "foobar",
            "status": "",
        }
    ]
}

boto3.setup_default_session(region_name="eu-west-1")
client = boto3.client("batch")
stubber = Stubber(client)
for i in range(5):
    response = response.copy()
    response["jobs"][0]["status"] = f"status_{i}"
    print("Adding response: ", response)
    stubber.add_response("describe_jobs", response)
stubber.activate()
for i in range(5):
    print(client.describe_jobs(jobs=["job_id"])["jobs"][0]["status"])
```
will still print:
```
Adding response:  {'jobs': [{'jobName': 'job_name', 'jobId': 'job_id', 'jobQueue': 'job_queue', 'startedAt': 123, 'jobDefinition': 'foobar', 'status': 'status_0'}]}
Adding response:  {'jobs': [{'jobName': 'job_name', 'jobId': 'job_id', 'jobQueue': 'job_queue', 'startedAt': 123, 'jobDefinition': 'foobar', 'status': 'status_1'}]}
Adding response:  {'jobs': [{'jobName': 'job_name', 'jobId': 'job_id', 'jobQueue': 'job_queue', 'startedAt': 123, 'jobDefinition': 'foobar', 'status': 'status_2'}]}
Adding response:  {'jobs': [{'jobName': 'job_name', 'jobId': 'job_id', 'jobQueue': 'job_queue', 'startedAt': 123, 'jobDefinition': 'foobar', 'status': 'status_3'}]}
Adding response:  {'jobs': [{'jobName': 'job_name', 'jobId': 'job_id', 'jobQueue': 'job_queue', 'startedAt': 123, 'jobDefinition': 'foobar', 'status': 'status_4'}]}
status_4
status_4
status_4
status_4
status_4
```
and I really don't understand why for one method the workaround works but not for another.
3. It's not very clear to me how fixing this bug could break other customers code: loading multiple time the same response will still work even after the fixing. Do you believe that someone is leveraging the bug in the sense that loads multiple **different** responses and then tests to get back only one result?

Thanks.

**Comment by swetashre** [comment]
@aledeganopix4d - In this case you need to use deep copy instead of shallow copy. With shallow copy reference to list object in original dictionary was copied in new dictionary. So, any changes in that list will be reflected in both the dictionaries. You need to use something like this:
```python
import copy
response = copy.deepcopy(response)
```

**Comment by dalmirog** [comment]
Sad to hear this one got closed.

I have a stubber of a `boto3` client which has 2 methods called `describe_listeners` and `describe_rules`. I need to set specific responses for each of those methods to use them in my test and I'm not sure I'll be able to do so without this feature.
