### ISSUE TITLE
Intermittent "No field numbered 1 is present in this asn1crypto.keys.PublicKeyInfo"

### ISSUE THREAD

**Issue by Samira-El** [boto/botocore#2131]
**Describe the bug**
* We have several jobs running on 3 ec2 instances that perform data ingestion, one step of this process is to upload encrypted 
 & compressed csv files from local disk to an s3 bucket.
* The connection to s3 bucket is done by passing credentials: AWS key, secret.
* We started getting this issue more and more these days.

**Steps to reproduce**
Can't reproduce it, because it happens only from time to time, like 0-5 times a day.
But the code is [here](https://github.com/transferwise/pipelinewise-target-snowflake/blob/fef6785808f0c8f43b8d327cf1a05fe80edf95aa/target_snowflake/db_sync.py#L428)

**Expected behavior**
I expect to not get these errors when upload operation is issued.

**Debug logs**
I can't enable debug for now, but here are the logs I currently get :

```
Traceback (most recent call last):
  File "/home/.../.virtualenvs/target-snowflake/bin/target-snowflake", line 8, in <module>
    sys.exit(main())
  File "/home/.../.virtualenvs/target-snowflake/lib/python3.6/site-packages/target_snowflake/__init__.py", line 451, in main
    persist_lines(config, singer_messages, table_cache)
  File "/home/.../.virtualenvs/target-snowflake/lib/python3.6/site-packages/target_snowflake/__init__.py", line 312, in persist_lines
    flushed_state = flush_streams(records_to_load, row_count, stream_to_sync, config, state, flushed_state)
  File "/home/.../.virtualenvs/target-snowflake/lib/python3.6/site-packages/target_snowflake/__init__.py", line 369, in flush_streams
    ) for stream in streams_to_flush)
  File "/home/.../.virtualenvs/target-snowflake/lib/python3.6/site-packages/joblib/parallel.py", line 934, in __call__
    self.retrieve()
  File "/home/.../.virtualenvs/target-snowflake/lib/python3.6/site-packages/joblib/parallel.py", line 833, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/.../.virtualenvs/target-snowflake/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 567, in __call__
    return self.func(*args, **kwargs)
  File "/home/.../.virtualenvs/target-snowflake/lib/python3.6/site-packages/joblib/parallel.py", line 225, in __call__
    for func, args, kwargs in self.items]
  File "/home/.../.virtualenvs/target-snowflake/lib/python3.6/site-packages/joblib/parallel.py", line 225, in <listcomp>
    for func, args, kwargs in self.items]
  File "/home/.../.virtualenvs/target-snowflake/lib/python3.6/site-packages/target_snowflake/__init__.py", line 397, in load_stream_batch
    flush_records(stream, records_to_load, row_count[stream], db_sync, temp_dir, no_compression)
  File "/home/.../.virtualenvs/target-snowflake/lib/python3.6/site-packages/target_snowflake/__init__.py", line 428, in flush_records
    s3_key = db_sync.put_to_stage(csv_file, stream, row_count, temp_dir=temp_dir)
  File "/home/.../.virtualenvs/target-snowflake/lib/python3.6/site-packages/target_snowflake/db_sync.py", line 428, in put_to_stage
    self.s3.upload_file(encrypted_file, bucket, s3_key, ExtraArgs=extra_args)
  File "/home/.../.virtualenvs/target-snowflake/lib/python3.6/site-packages/boto3/s3/inject.py", line 131, in upload_file
    extra_args=ExtraArgs, callback=Callback)
  File "/home/.../.virtualenvs/target-snowflake/lib/python3.6/site-packages/boto3/s3/transfer.py", line 279, in upload_file
    future.result()
  File "/home/.../.virtualenvs/target-snowflake/lib/python3.6/site-packages/s3transfer/futures.py", line 106, in result
    return self._coordinator.result()
  File "/home/.../.virtualenvs/target-snowflake/lib/python3.6/site-packages/s3transfer/futures.py", line 265, in result
    raise self._exception
  File "/home/.../.virtualenvs/target-snowflake/lib/python3.6/site-packages/s3transfer/tasks.py", line 126, in __call__
    return self._execute_main(kwargs)
  File "/home/.../.virtualenvs/target-snowflake/lib/python3.6/site-packages/s3transfer/tasks.py", line 150, in _execute_main
    return_value = self._main(**kwargs)
  File "/home/.../.virtualenvs/target-snowflake/lib/python3.6/site-packages/s3transfer/upload.py", line 692, in _main
    client.put_object(Bucket=bucket, Key=key, Body=body, **extra_args)
  File "/home/.../.virtualenvs/target-snowflake/lib/python3.6/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/.../.virtualenvs/target-snowflake/lib/python3.6/site-packages/botocore/client.py", line 648, in _make_api_call
    operation_model, request_dict, request_context)
  File "/home/.../.virtualenvs/target-snowflake/lib/python3.6/site-packages/botocore/client.py", line 667, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/home/.../.virtualenvs/target-snowflake/lib/python3.6/site-packages/botocore/endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "/home/.../.virtualenvs/target-snowflake/lib/python3.6/site-packages/botocore/endpoint.py", line 137, in _send_request
    success_response, exception):
  File "/home/.../.virtualenvs/target-snowflake/lib/python3.6/site-packages/botocore/endpoint.py", line 231, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "/home/.../.virtualenvs/target-snowflake/lib/python3.6/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/home/.../.virtualenvs/target-snowflake/lib/python3.6/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/home/.../.virtualenvs/target-snowflake/lib/python3.6/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/home/.../.virtualenvs/target-snowflake/lib/python3.6/site-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/home/.../.virtualenvs/target-snowflake/lib/python3.6/site-packages/botocore/retryhandler.py", line 251, in __call__
    caught_exception)
  File "/home/.../.virtualenvs/target-snowflake/lib/python3.6/site-packages/botocore/retryhandler.py", line 269, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/home/.../.virtualenvs/target-snowflake/lib/python3.6/site-packages/botocore/retryhandler.py", line 317, in __call__
    caught_exception)
  File "/home/.../.virtualenvs/target-snowflake/lib/python3.6/site-packages/botocore/retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "/home/.../.virtualenvs/target-snowflake/lib/python3.6/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
  File "/home/.../.virtualenvs/target-snowflake/lib/python3.6/site-packages/botocore/endpoint.py", line 200, in _do_get_response
    http_response = self._send(request)
  File "/home/.../.virtualenvs/target-snowflake/lib/python3.6/site-packages/botocore/endpoint.py", line 244, in _send
    return self.http_session.send(request)
  File "/home/.../.virtualenvs/target-snowflake/lib/python3.6/site-packages/botocore/httpsession.py", line 299, in send
    raise HTTPClientError(error=e)
botocore.exceptions.HTTPClientError: An HTTP Client raised and unhandled exception: 'No field numbered 1 is present in this asn1crypto.keys.PublicKeyInfo'
```

Really appreciate any guidance on what's going wrong!
Thanks.

**Comment by swetashre** [comment]
Thank you for your post. It looks like the error is coming from asn1crypto. 
https://github.com/wbond/asn1crypto/blob/704889494451461ffdb75d192c2a2db1258660db/asn1crypto/core.py#L3524

Are you using asn1crypto in your code ? You can confirm from the debug log from where this exception is originally coming that leads to this botocore exception. Then you can figure it out which parameter is leading to this asn1crypto exception.
