### ISSUE TITLE
Returning an Expiration of less than 15 minutes from now in botocore.credentials.RefreshableCredentials raises TypeError in dateutil.parser

### ISSUE THREAD

**Issue by mathewmoon** [boto/botocore#2164]
**Describe the bug**
botocore does not catch or raise its own exception in the case of RefreshableCredentials having an Expiration of less than 15 minutes from current time. The exception raised is buried in dateutil.parser._parser. It seems like botocore is passing the datetime object from the load() method directly to dateutil.parser.parse without casting it to a string in the case of the time being less than 15 minutes from now. This makes it virtually impossible to do unit tests via CI/CD for a CredentialProvider that has to make sure the temporary IAM credentials are refreshed BEFORE other events (a Cognito IdToken expiring for instance) happen. We also don't get a exception that clearly states what the issue is from botocore.

**Steps to reproduce**
Insert a credential provider into the chain and return a RefreshableCredentials object from CredentialProvider.load() with an Expiration of less than 15 minutes from now.

**Expected behavior**
Botocore accepts the Expiration time.

**Debug logs**
Traceback (most recent call last):
  File "./test.py", line 9, in <module>
    print(s3.list_buckets())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/botocore/client.py", line 337, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/botocore/client.py", line 642, in _make_api_call
    http, parsed_response = self._make_request(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/botocore/client.py", line 662, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/botocore/endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/botocore/endpoint.py", line 132, in _send_request
    request = self.create_request(request_dict, operation_model)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/botocore/endpoint.py", line 115, in create_request
    self._event_emitter.emit(event_name, request=request,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/botocore/signers.py", line 90, in handler
    return self.sign(operation_name, request)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/botocore/signers.py", line 152, in sign
    auth = self.get_auth_instance(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/botocore/signers.py", line 232, in get_auth_instance
    frozen_credentials = self._credentials.get_frozen_credentials()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/botocore/credentials.py", line 605, in get_frozen_credentials
    self._refresh()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/botocore/credentials.py", line 500, in _refresh
    self._protected_refresh(is_mandatory=is_mandatory_refresh)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/botocore/credentials.py", line 531, in _protected_refresh
    self._set_from_data(metadata)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/botocore/credentials.py", line 566, in _set_from_data
    self._expiry_time = parse(data['expiry_time'])
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/dateutil/parser/_parser.py", line 1374, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/dateutil/parser/_parser.py", line 646, in parse
    res, skipped_tokens = self._parse(timestr, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/dateutil/parser/_parser.py", line 725, in _parse
    l = _timelex.split(timestr)         # Splits the timestr into tokens
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/dateutil/parser/_parser.py", line 207, in split
    return list(cls(s))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/dateutil/parser/_parser.py", line 75, in __init__
    raise TypeError('Parser must be a string or character stream, not '```
import botocore.session
botocore.session.Session().set_debug_logger('')
```

Code is part of a python module.
Full code at https://github.com/QuiNovas/cognito-assume-role.

**Comment by mathewmoon** [comment]
I found a work around to the issue I was having. The problem isn't with the amount of time set on the credentials. The issue is that when the function returned by _create_credentials_fetcher() is run from the load() method the Expiration has to be a datetime.datetime object, but when credentials are being refreshed Expiration is expected to be a string to be passed to dateutil.parser.parse(). It would be very helpful if there were some documentation that outlined this. Even if just in the docstrings for RefreshableCredentials and CredentialProvider.load

**Comment by swetashre** [comment]
@mathewmoon - Thank you for your post. Yes, you are right. The expiry_time should be in string format otherwise the parse function will give error. 
Marking this as documentation update.
