### ISSUE TITLE
get_session_embed_url() method is missing from QuickSight client

### ISSUE THREAD

**Issue by alexhung** [boto/botocore#2183]
**Describe the bug**
The documentation states clearly that `get_session_embed_url()` method exist (https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/quicksight.html#QuickSight.Client.get_session_embed_url). The botocore model data file confirms this: https://github.com/boto/botocore/blob/1.18.17/botocore/data/quicksight/2018-04-01/service-2.json#L984

However the client instance raises this error when `get_session_embed_url()` is invoked:

```
AttributeError: 'QuickSight' object has no attribute 'get_session_embed_url'
```

My code is executed in a lambda via `sam local invoke`.

**Steps to reproduce**

Create a new QuickSight client and calls the method:

```
client = boto3.client("quicksight")

params = {
  # Omitted for brevity
}
client.get_session_embed_url(**params)
```

**Expected behavior**

Client calls the corresponding `GetSessionEmbedUrl()` SDK API and returns the response.

**Debug logs**

```
Invoking session_url.handler (python3.8)
Skip pulling image and use local one: amazon/aws-sam-cli-emulation-image-python3.8:rapid-1.6.2.

Mounting /.../.aws-sam/build/GetSessionEmbeddedUrlFunction as /var/task:ro,delegated inside runtime container
START RequestId: a6603595-6fd7-1e86-1172-aa82367d2bee Version: $LATEST
2020-10-16 17:51:26,992 - botocore.hooks - DEBUG - Changing event name from creating-client-class.iot-data to creating-client-class.iot-data-plane
[DEBUG]	2020-10-16T17:51:26.992Z	a6603595-6fd7-1e86-1172-aa82367d2bee	Changing event name from creating-client-class.iot-data to creating-client-class.iot-data-plane
2020-10-16 17:51:26,994 - botocore.hooks - DEBUG - Changing event name from before-call.apigateway to before-call.api-gateway
[DEBUG]	2020-10-16T17:51:26.994Z	a6603595-6fd7-1e86-1172-aa82367d2bee	Changing event name from before-call.apigateway to before-call.api-gateway
2020-10-16 17:51:26,995 - botocore.hooks - DEBUG - Changing event name from request-created.machinelearning.Predict to request-created.machine-learning.Predict
[DEBUG]	2020-10-16T17:51:26.995Z	a6603595-6fd7-1e86-1172-aa82367d2bee	Changing event name from request-created.machinelearning.Predict to request-created.machine-learning.Predict
2020-10-16 17:51:26,997 - botocore.hooks - DEBUG - Changing event name from before-parameter-build.autoscaling.CreateLaunchConfiguration to before-parameter-build.auto-scaling.CreateLaunchConfiguration
[DEBUG]	2020-10-16T17:51:26.997Z	a6603595-6fd7-1e86-1172-aa82367d2bee	Changing event name from before-parameter-build.autoscaling.CreateLaunchConfiguration to before-parameter-build.auto-scaling.CreateLaunchConfiguration
2020-10-16 17:51:26,997 - botocore.hooks - DEBUG - Changing event name from before-parameter-build.route53 to before-parameter-build.route-53
[DEBUG]	2020-10-16T17:51:26.997Z	a6603595-6fd7-1e86-1172-aa82367d2bee	Changing event name from before-parameter-build.route53 to before-parameter-build.route-53
2020-10-16 17:51:26,998 - botocore.hooks - DEBUG - Changing event name from request-created.cloudsearchdomain.Search to request-created.cloudsearch-domain.Search
[DEBUG]	2020-10-16T17:51:26.998Z	a6603595-6fd7-1e86-1172-aa82367d2bee	Changing event name from request-created.cloudsearchdomain.Search to request-created.cloudsearch-domain.Search
2020-10-16 17:51:26,999 - botocore.hooks - DEBUG - Changing event name from docs.*.autoscaling.CreateLaunchConfiguration.complete-section to docs.*.auto-scaling.CreateLaunchConfiguration.complete-section
[DEBUG]	2020-10-16T17:51:26.999Z	a6603595-6fd7-1e86-1172-aa82367d2bee	Changing event name from docs.*.autoscaling.CreateLaunchConfiguration.complete-section to docs.*.auto-scaling.CreateLaunchConfiguration.complete-section
2020-10-16 17:51:27,002 - botocore.hooks - DEBUG - Changing event name from before-parameter-build.logs.CreateExportTask to before-parameter-build.cloudwatch-logs.CreateExportTask
[DEBUG]	2020-10-16T17:51:27.2Z	a6603595-6fd7-1e86-1172-aa82367d2bee	Changing event name from before-parameter-build.logs.CreateExportTask to before-parameter-build.cloudwatch-logs.CreateExportTask
2020-10-16 17:51:27,002 - botocore.hooks - DEBUG - Changing event name from docs.*.logs.CreateExportTask.complete-section to docs.*.cloudwatch-logs.CreateExportTask.complete-section
2020-10-16 17:51:27,002 - botocore.hooks - DEBUG - Changing event name from before-parameter-build.cloudsearchdomain.Search to before-parameter-build.cloudsearch-domain.Search
2020-10-16 17:51:27,002 - botocore.hooks - DEBUG - Changing event name from docs.*.cloudsearchdomain.Search.complete-section to docs.*.cloudsearch-domain.Search.complete-section
[DEBUG]	2020-10-16T17:51:27.2Z	a6603595-6fd7-1e86-1172-aa82367d2bee	Changing event name from docs.*.logs.CreateExportTask.complete-section to docs.*.cloudwatch-logs.CreateExportTask.complete-section
[DEBUG]	2020-10-16T17:51:27.2Z	a6603595-6fd7-1e86-1172-aa82367d2bee	Changing event name from before-parameter-build.cloudsearchdomain.Search to before-parameter-build.cloudsearch-domain.Search
[DEBUG]	2020-10-16T17:51:27.2Z	a6603595-6fd7-1e86-1172-aa82367d2bee	Changing event name from docs.*.cloudsearchdomain.Search.complete-section to docs.*.cloudsearch-domain.Search.complete-section
2020-10-16 17:51:27,005 - botocore.credentials - DEBUG - Looking for credentials via: env
2020-10-16 17:51:27,005 - botocore.credentials - INFO - Found credentials in environment variables.
[DEBUG]	2020-10-16T17:51:27.5Z	a6603595-6fd7-1e86-1172-aa82367d2bee	Looking for credentials via: env
[INFO]	2020-10-16T17:51:27.5Z	a6603595-6fd7-1e86-1172-aa82367d2bee	Found credentials in environment variables.
2020-10-16 17:51:27,006 - botocore.loaders - DEBUG - Loading JSON file: /var/runtime/botocore/data/endpoints.json
[DEBUG]	2020-10-16T17:51:27.6Z	a6603595-6fd7-1e86-1172-aa82367d2bee	Loading JSON file: /var/runtime/botocore/data/endpoints.json
2020-10-16 17:51:27,012 - botocore.hooks - DEBUG - Event choose-service-name: calling handler <function handle_service_name_alias at 0x7fd6dfb5ce50>
[DEBUG]	2020-10-16T17:51:27.12Z	a6603595-6fd7-1e86-1172-aa82367d2bee	Event choose-service-name: calling handler <function handle_service_name_alias at 0x7fd6dfb5ce50>
2020-10-16 17:51:27,027 - botocore.loaders - DEBUG - Loading JSON file: /var/runtime/botocore/data/quicksight/2018-04-01/service-2.json
[DEBUG]	2020-10-16T17:51:27.27Z	a6603595-6fd7-1e86-1172-aa82367d2bee	Loading JSON file: /var/runtime/botocore/data/quicksight/2018-04-01/service-2.json
2020-10-16 17:51:27,035 - botocore.hooks - DEBUG - Event creating-client-class.quicksight: calling handler <function add_generate_presigned_url at 0x7fd6dfbabd30>
[DEBUG]	2020-10-16T17:51:27.35Z	a6603595-6fd7-1e86-1172-aa82367d2bee	Event creating-client-class.quicksight: calling handler <function add_generate_presigned_url at 0x7fd6dfbabd30>
[DEBUG]	2020-10-16T17:51:27.35Z	a6603595-6fd7-1e86-1172-aa82367d2bee	Creating a regex based endpoint for quicksight, us-west-2
2020-10-16 17:51:27,035 - botocore.regions - DEBUG - Creating a regex based endpoint for quicksight, us-west-2
[DEBUG]	2020-10-16T17:51:27.38Z	a6603595-6fd7-1e86-1172-aa82367d2bee	Setting quicksight timeout as (60, 60)
2020-10-16 17:51:27,038 - botocore.endpoint - DEBUG - Setting quicksight timeout as (60, 60)
2020-10-16 17:51:27,040 - botocore.loaders - DEBUG - Loading JSON file: /var/runtime/botocore/data/_retry.json
[DEBUG]	2020-10-16T17:51:27.40Z	a6603595-6fd7-1e86-1172-aa82367d2bee	Loading JSON file: /var/runtime/botocore/data/_retry.json
[DEBUG]	2020-10-16T17:51:27.40Z	a6603595-6fd7-1e86-1172-aa82367d2bee	Registering retry handlers for service: quicksight
2020-10-16 17:51:27,040 - botocore.client - DEBUG - Registering retry handlers for service: quicksight
[ERROR] AttributeError: 'QuickSight' object has no attribute 'get_session_embed_url'
Traceback (most recent call last):
  File "/var/task/session_url.py", line 103, in handler
    session_embed_url = quicksight_session.get_session_embed_url(**get_session_kwargs)
  File "/var/runtime/botocore/client.py", line 573, in __getattr__
    raise AttributeError(
END RequestId: a6603595-6fd7-1e86-1172-aa82367d2bee
REPORT RequestId: a6603595-6fd7-1e86-1172-aa82367d2bee	Init Duration: 275.60 ms	Duration: 57.51 ms	Billed Duration: 100 ms	Memory Size: 128 MB	Max Memory Used: 37 MB

{"errorType":"AttributeError","errorMessage":"'QuickSight' object has no attribute 'get_session_embed_url'","stackTrace":["  File \"/var/task/session_url.py\", line 103, in handler\n    session_embed_url = quicksight_session.get_session_embed_url(**get_session_kwargs)\n","  File \"/var/runtime/botocore/client.py\", line 573, in __getattr__\n    raise AttributeError(\n"]}
```

**Comment by alexhung** [comment]
I print out the content of Boto model data file in `/var/runtime/botocore/data/quicksight/2018-04-01/service-2.json` from the Docker image and `GetSessionEmbedUrl` is not in the file.

I've since deleted both the SAM build image and emulation image, rebuild and invoke the code (which causes SAM to fetch both images from Docker hub) and the method is still missing in the data file.

**Comment by alexhung** [comment]
The method is added to the json file on July 22: https://github.com/boto/botocore/commit/898350538eff4c7bccc5bb29267e9cdc7b2ca05c

**Comment by swetashre** [comment]
@alexhung - Thank you for your post. Which botocore version are you using ? Please make sure your code is using botocore version >1.17.26.

**Comment by alexhung** [comment]
@swetashre I was using the version that comes with SAM Docker image, e.g. boto3 is not in the `requirements.txt`. This turns out to cause this issue since the version of boto3 in `aws-sam-cli-emulation-image-python3.8` image does not contain a version of boto3 that has the method defined.

My current workaround is to include boto3 in my `requirements.txt` to override the version from Docker image. I'm using `boto3==1.15.17` which is working for me.

I still expect the version included in the Docker image will be up-to-dated, as would others SAM users I suspect.

**Comment by swetashre** [comment]
@alexhung - I am glad you got it working. I don't know much about sam-cli. This is [aws-sam-cli](https://github.com/aws/aws-sam-cli) repo. You can post in that repo if you have any further queries. 

I am closing this issue as we can't do anything on our end to fix this.

**Comment by ghorwitchsmith** [comment]
Hi, I get this issue using boto3-1.17.71 botocore-1.20.71, is there a solution to this?

**Comment by Manuelacosta98** [comment]
@ghorwitchsmith  @swetashre any news about this bug? I dont know why is close is happening still with version:

boto3: 1.17.90
botocore: 1.20.90

Thanks a lot. let us know if this need a PR
