### ISSUE TITLE
apigatewaymanagementapi error in post_to_connection

### ISSUE THREAD

**Issue by victor5114** [boto/botocore#2218]
**Describe the bug**
I've setup a API Gateway Websocket Endpoint and I'm trying to send messages back to clients from inside a Cloudwatch event triggered Lambda with using `boto3.client('apigatewaymanagementapi')` I get the following error 
```
botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "https://execute-api.eu-west-1.amazonaws.com/@connections/V-M0CclhjoECETA%3D"
```

**Steps to reproduce**
The code looks like this 
```python
def lambda_handler(event, context):
    body = event['body']

    table = dynamodb.Table(CONN_STATUS_TABLENAME)
    scan = table.query(
        IndexName='topicIndex',
        KeyConditionExpression=Key('topicSubscription').eq(body['payload']['topic'])
    )

    api_gateway_client = boto3.client('apigatewaymanagementapi')

    for item in scan['Items']:
        api_gateway_client.post_to_connection(ConnectionId=item['connectionId'],
                                              Data=json.dumps(body['payload']['data']))

    return {
        'statusCode': 200,
        'headers': {'Content-Type': 'application/json'},
        'body': json.dumps({'message': 'hello'})
    }
```

**Expected behavior**
I would expect my endpoint to be the formatted as follow : `https://<apigateway_id>.execute-api.eu-west-1.amazonaws.com/<stage>/@connections` but it seems that boto is not supporting new staged version of API Gateway endpoint.

**Debug logs**
Traceback (most recent call last):
```--
  | 2020-11-14T01:45:13.656+01:00 | File "/var/task/urllib3/connection.py", line 170, in _new_conn
  | 2020-11-14T01:45:13.656+01:00 | (self._dns_host, self.port), self.timeout, **extra_kw
  | 2020-11-14T01:45:13.656+01:00 | File "/var/task/urllib3/util/connection.py", line 73, in create_connection
  | 2020-11-14T01:45:13.656+01:00 | for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  | 2020-11-14T01:45:13.656+01:00 | File "/var/lang/lib/python3.7/socket.py", line 752, in getaddrinfo
  | 2020-11-14T01:45:13.656+01:00 | for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
  | 2020-11-14T01:45:13.656+01:00 | socket.gaierror: [Errno -5] No address associated with hostname
  | 2020-11-14T01:45:13.656+01:00 | During handling of the above exception, another exception occurred:
  | 2020-11-14T01:45:13.656+01:00 | Traceback (most recent call last):
  | 2020-11-14T01:45:13.656+01:00 | File "/var/runtime/botocore/httpsession.py", line 263, in send
  | 2020-11-14T01:45:13.656+01:00 | chunked=self._chunked(request.headers),
  | 2020-11-14T01:45:13.656+01:00 | File "/var/task/urllib3/connectionpool.py", line 756, in urlopen
  | 2020-11-14T01:45:13.656+01:00 | method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  | 2020-11-14T01:45:13.656+01:00 | File "/var/task/urllib3/util/retry.py", line 506, in increment
  | 2020-11-14T01:45:13.656+01:00 | raise six.reraise(type(error), error, _stacktrace)
  | 2020-11-14T01:45:13.656+01:00 | File "/var/task/urllib3/packages/six.py", line 735, in reraise
  | 2020-11-14T01:45:13.656+01:00 | raise value
  | 2020-11-14T01:45:13.656+01:00 | File "/var/task/urllib3/connectionpool.py", line 706, in urlopen
  | 2020-11-14T01:45:13.656+01:00 | chunked=chunked,
  | 2020-11-14T01:45:13.656+01:00 | File "/var/task/urllib3/connectionpool.py", line 382, in _make_request
  | 2020-11-14T01:45:13.656+01:00 | self._validate_conn(conn)
  | 2020-11-14T01:45:13.656+01:00 | File "/var/task/urllib3/connectionpool.py", line 1010, in _validate_conn
  | 2020-11-14T01:45:13.656+01:00 | conn.connect()
  | 2020-11-14T01:45:13.656+01:00 | File "/var/task/urllib3/connection.py", line 353, in connect
  | 2020-11-14T01:45:13.656+01:00 | conn = self._new_conn()
  | 2020-11-14T01:45:13.656+01:00 | File "/var/task/urllib3/connection.py", line 182, in _new_conn
  | 2020-11-14T01:45:13.656+01:00 | self, "Failed to establish a new connection: %s" % e
  | 2020-11-14T01:45:13.656+01:00 | urllib3.exceptions.NewConnectionError: <botocore.awsrequest.AWSHTTPSConnection object at 0x7f82a1ef25d0>: Failed to establish a new connection: [Errno -5] No address associated with hostname
  | 2020-11-14T01:45:13.656+01:00 | During handling of the above exception, another exception occurred:
  | 2020-11-14T01:45:13.656+01:00 | Traceback (most recent call last):
  | 2020-11-14T01:45:13.656+01:00 | File "/var/runtime/botocore/retryhandler.py", line 269, in _should_retry
  | 2020-11-14T01:45:13.656+01:00 | return self._checker(attempt_number, response, caught_exception)
  | 2020-11-14T01:45:13.656+01:00 | File "/var/runtime/botocore/retryhandler.py", line 317, in __call__
  | 2020-11-14T01:45:13.656+01:00 | caught_exception)
  | 2020-11-14T01:45:13.656+01:00 | File "/var/runtime/botocore/retryhandler.py", line 223, in __call__
  | 2020-11-14T01:45:13.656+01:00 | attempt_number, caught_exception)
  | 2020-11-14T01:45:13.656+01:00 | File "/var/runtime/botocore/retryhandler.py", line 359, in _check_caught_exception
  | 2020-11-14T01:45:13.656+01:00 | raise caught_exception
  | 2020-11-14T01:45:13.656+01:00 | File "/var/runtime/botocore/endpoint.py", line 200, in _do_get_response
  | 2020-11-14T01:45:13.656+01:00 | http_response = self._send(request)
  | 2020-11-14T01:45:13.656+01:00 | File "/var/runtime/botocore/endpoint.py", line 269, in _send
  | 2020-11-14T01:45:13.656+01:00 | return self.http_session.send(request)
  | 2020-11-14T01:45:13.656+01:00 | File "/var/runtime/botocore/httpsession.py", line 283, in send
  | 2020-11-14T01:45:13.656+01:00 | raise EndpointConnectionError(endpoint_url=request.url, error=e)
  | 2020-11-14T01:45:13.656+01:00 | botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "https://execute-api.eu-west-1.amazonaws.com/@connections/V-M0CclhjoECETA%3D"
--
```

**Comment by swetashre** [comment]
@victor5114 - Thank you for your post. I am able to reproduce the issue. The endpoint will be of the form ```https://{api-id}.execute-api.{region}.amazonaws.com/{stage},``` or will be the endpoint corresponding to your API's custom domain and base path, if applicable.
In the mean time you can try by passing the exact ```endpoint_url``` during client creation. 
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/core/session.html

**Comment by victor5114** [comment]
@swetashre Thank you so much ! It works indeed specifying the endpoint_url during client creation. Still I believe that the override of endpoint_url should be mentioned somewhere in API Gateway Management documentation as the aforementioned endpoint is always api-id/region/stage specific and thus shall always be overriden, right ?

**Comment by swetashre** [comment]
@victor5114 - Glad it worked for you. I agree. We will look to update our documentation. Marking this as documentation.

**Comment by swetashre** [comment]
We have added to the documentation about how to use endpoint url while using this service. 
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/apigatewaymanagementapi.html

I am closing this as this has been fixed.
