### ISSUE TITLE
Disable fetching instance metadata while using stubs

### ISSUE THREAD

**Issue by pglass** [boto/botocore#2275]
**What issue did you see ?**

While using the [botocore.Stubber](https://botocore.amazonaws.com/v1/documentation/api/latest/reference/stubber.html#botocore.stub.Stubber) in my unit tests I noticed some hangs/delays in running my tests, which seem to be due to connection timeouts while botocore tries to retrieve instance metadata. 

I don't need or want to retrieve any instance metadata in unit tests, and actually I would like to disable anything that might result in botocore clients potentially using/retrieving valid credentials. What is the best way to do this?

**Steps to reproduce**

Run the following code, which is identical to [this example](https://botocore.amazonaws.com/v1/documentation/api/latest/reference/stubber.html#botocore.stub.Stubber) with debug logs enabled. On my laptop, it will show a `Connection to 169.254.169.254 timed out` error, which is non-fatal but does cause a slight delay until the connection timeout (and if I were to run real world unit tests on an EC2 instance in AWS, it's possible to accidentally retrieve valid credentials from the EC2 instance do damage to real resources).

```python
import datetime
import botocore.session
from botocore.stub import Stubber

session = botocore.session.get_session()
session.set_debug_logger()
s3 = session.create_client('s3')
stubber = Stubber(s3)

response = {
    'IsTruncated': False,
    'Name': 'test-bucket',
    'MaxKeys': 1000, 'Prefix': '',
    'Contents': [{
        'Key': 'test.txt',
        'ETag': '"abc123"',
        'StorageClass': 'STANDARD',
        'LastModified': datetime.datetime(2016, 1, 20, 22, 9),
        'Owner': {'ID': 'abc123', 'DisplayName': 'myname'},
        'Size': 14814
    }],
    'EncodingType': 'url',
    'ResponseMetadata': {
        'RequestId': 'abc123',
        'HTTPStatusCode': 200,
        'HostId': 'abc123'
    },
    'Marker': ''
}

expected_params = {'Bucket': 'test-bucket'}

stubber.add_response('list_objects', response, expected_params)
stubber.activate()

service_response = s3.list_objects(Bucket='test-bucket')
assert service_response == response
```

**Debug logs**

```
2021-01-20 17:01:10,007 - botocore.utils - DEBUG - IMDS ENDPOINT: http://169.254.169.254/
2021-01-20 17:01:10,016 - botocore.credentials - DEBUG - Looking for credentials via: env
2021-01-20 17:01:10,016 - botocore.credentials - DEBUG - Looking for credentials via: assume-role
2021-01-20 17:01:10,016 - botocore.credentials - DEBUG - Looking for credentials via: assume-role-with-web-identity
2021-01-20 17:01:10,016 - botocore.credentials - DEBUG - Looking for credentials via: sso
2021-01-20 17:01:10,016 - botocore.credentials - DEBUG - Looking for credentials via: shared-credentials-file
2021-01-20 17:01:10,016 - botocore.credentials - DEBUG - Looking for credentials via: custom-process
2021-01-20 17:01:10,017 - botocore.credentials - DEBUG - Looking for credentials via: config-file
2021-01-20 17:01:10,017 - botocore.credentials - DEBUG - Looking for credentials via: ec2-credentials-file
2021-01-20 17:01:10,017 - botocore.credentials - DEBUG - Looking for credentials via: boto-config
2021-01-20 17:01:10,017 - botocore.credentials - DEBUG - Looking for credentials via: container-role
2021-01-20 17:01:10,017 - botocore.credentials - DEBUG - Looking for credentials via: iam-role
2021-01-20 17:01:11,028 - botocore.utils - DEBUG - Caught retryable HTTP exception while making metadata service request to http://169.254.169.254/latest/api/token: Connect timeout on endpoint URL: "http://169.254.169.254/latest/api/token"
Traceback (most recent call last):
  File "/Users/pglass/code/boto-test/venv/lib/python3.8/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/Users/pglass/code/boto-test/venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/Users/pglass/code/boto-test/venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/pglass/code/boto-test/venv/lib/python3.8/site-packages/botocore/httpsession.py", line 254, in send
    urllib_response = conn.urlopen(
  File "/Users/pglass/code/boto-test/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/Users/pglass/code/boto-test/venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 506, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/pglass/code/boto-test/venv/lib/python3.8/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/Users/pglass/code/boto-test/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/Users/pglass/code/boto-test/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Users/pglass/code/boto-test/venv/lib/python3.8/site-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/http/client.py", line 1230, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/pglass/code/boto-test/venv/lib/python3.8/site-packages/botocore/awsrequest.py", line 91, in _send_request
    rval = super(AWSConnection, self)._send_request(
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/http/client.py", line 1276, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/http/client.py", line 1225, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Users/pglass/code/boto-test/venv/lib/python3.8/site-packages/botocore/awsrequest.py", line 119, in _send_output
    self.send(msg)
  File "/Users/pglass/code/boto-test/venv/lib/python3.8/site-packages/botocore/awsrequest.py", line 203, in send
    return super(AWSConnection, self).send(str)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/http/client.py", line 944, in send
    self.connect()
  File "/Users/pglass/code/boto-test/venv/lib/python3.8/site-packages/urllib3/connection.py", line 200, in connect
    conn = self._new_conn()
  File "/Users/pglass/code/boto-test/venv/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<botocore.awsrequest.AWSHTTPConnection object at 0x10ef7ca00>, 'Connection to 169.254.169.254 timed out. (connect timeout=1)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/pglass/code/boto-test/venv/lib/python3.8/site-packages/botocore/utils.py", line 368, in _fetch_metadata_token
    response = self._session.send(request.prepare())
  File "/Users/pglass/code/boto-test/venv/lib/python3.8/site-packages/botocore/httpsession.py", line 287, in send
    raise ConnectTimeoutError(endpoint_url=request.url, error=e)
botocore.exceptions.ConnectTimeoutError: Connect timeout on endpoint URL: "http://169.254.169.254/latest/api/token"
2021-01-20 17:01:12,061 - botocore.utils - DEBUG - Caught retryable HTTP exception while making metadata service request to http://169.254.169.254/latest/meta-data/iam/security-credentials/: Connect timeout on endpoint URL: "http://169.254.169.254/latest/meta-data/iam/security-credentials/"
Traceback (most recent call last):
  File "/Users/pglass/code/boto-test/venv/lib/python3.8/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/Users/pglass/code/boto-test/venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/Users/pglass/code/boto-test/venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/pglass/code/boto-test/venv/lib/python3.8/site-packages/botocore/httpsession.py", line 254, in send
    urllib_response = conn.urlopen(
  File "/Users/pglass/code/boto-test/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/Users/pglass/code/boto-test/venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 506, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/pglass/code/boto-test/venv/lib/python3.8/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/Users/pglass/code/boto-test/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/Users/pglass/code/boto-test/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Users/pglass/code/boto-test/venv/lib/python3.8/site-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/http/client.py", line 1230, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/pglass/code/boto-test/venv/lib/python3.8/site-packages/botocore/awsrequest.py", line 91, in _send_request
    rval = super(AWSConnection, self)._send_request(
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/http/client.py", line 1276, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/http/client.py", line 1225, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Users/pglass/code/boto-test/venv/lib/python3.8/site-packages/botocore/awsrequest.py", line 119, in _send_output
    self.send(msg)
  File "/Users/pglass/code/boto-test/venv/lib/python3.8/site-packages/botocore/awsrequest.py", line 203, in send
    return super(AWSConnection, self).send(str)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/http/client.py", line 944, in send
    self.connect()
  File "/Users/pglass/code/boto-test/venv/lib/python3.8/site-packages/urllib3/connection.py", line 200, in connect
    conn = self._new_conn()
  File "/Users/pglass/code/boto-test/venv/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<botocore.awsrequest.AWSHTTPConnection object at 0x10efab5e0>, 'Connection to 169.254.169.254 timed out. (connect timeout=1)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/pglass/code/boto-test/venv/lib/python3.8/site-packages/botocore/utils.py", line 416, in _get_request
    response = self._session.send(request.prepare())
  File "/Users/pglass/code/boto-test/venv/lib/python3.8/site-packages/botocore/httpsession.py", line 287, in send
    raise ConnectTimeoutError(endpoint_url=request.url, error=e)
botocore.exceptions.ConnectTimeoutError: Connect timeout on endpoint URL: "http://169.254.169.254/latest/meta-data/iam/security-credentials/"
2021-01-20 17:01:12,063 - botocore.utils - DEBUG - Max number of attempts exceeded (1) when attempting to retrieve data from metadata service.
2021-01-20 17:01:12,066 - botocore.loaders - DEBUG - Loading JSON file: /Users/pglass/code/boto-test/venv/lib/python3.8/site-packages/botocore/data/endpoints.json
2021-01-20 17:01:12,075 - botocore.hooks - DEBUG - Event choose-service-name: calling handler <function handle_service_name_alias at 0x10eec2700>
2021-01-20 17:01:12,113 - botocore.loaders - DEBUG - Loading JSON file: /Users/pglass/code/boto-test/venv/lib/python3.8/site-packages/botocore/data/s3/2006-03-01/service-2.json
2021-01-20 17:01:12,123 - botocore.hooks - DEBUG - Event creating-client-class.s3: calling handler <function add_generate_presigned_post at 0x10ee6edc0>
2021-01-20 17:01:12,123 - botocore.hooks - DEBUG - Event creating-client-class.s3: calling handler <function add_generate_presigned_url at 0x10ee6eb80>
2021-01-20 17:01:12,125 - botocore.endpoint - DEBUG - Setting s3 timeout as (60, 60)
2021-01-20 17:01:12,126 - botocore.loaders - DEBUG - Loading JSON file: /Users/pglass/code/boto-test/venv/lib/python3.8/site-packages/botocore/data/_retry.json
2021-01-20 17:01:12,126 - botocore.client - DEBUG - Registering retry handlers for service: s3
2021-01-20 17:01:12,128 - botocore.hooks - DEBUG - Event before-parameter-build.s3.ListObjects: calling handler <bound method Stubber._assert_expected_params of <botocore.stub.Stubber object at 0x10ef19c70>>
2021-01-20 17:01:12,128 - botocore.hooks - DEBUG - Event before-parameter-build.s3.ListObjects: calling handler <function set_list_objects_encoding_type_url at 0x10ef03dc0>
2021-01-20 17:01:12,128 - botocore.hooks - DEBUG - Event before-parameter-build.s3.ListObjects: calling handler <function validate_bucket_name at 0x10ef00af0>
2021-01-20 17:01:12,128 - botocore.hooks - DEBUG - Event before-parameter-build.s3.ListObjects: calling handler <bound method S3RegionRedirector.redirect_from_cache of <botocore.utils.S3RegionRedirector object at 0x1105bcf40>>
2021-01-20 17:01:12,128 - botocore.hooks - DEBUG - Event before-parameter-build.s3.ListObjects: calling handler <bound method S3ArnParamHandler.handle_arn of <botocore.utils.S3ArnParamHandler object at 0x1105ec040>>
2021-01-20 17:01:12,128 - botocore.hooks - DEBUG - Event before-parameter-build.s3.ListObjects: calling handler <function generate_idempotent_uuid at 0x10ef00940>
2021-01-20 17:01:12,129 - botocore.hooks - DEBUG - Event before-call.s3.ListObjects: calling handler <bound method Stubber._get_response_handler of <botocore.stub.Stubber object at 0x10ef19c70>>
2021-01-20 17:01:12,129 - botocore.hooks - DEBUG - Event after-call.s3.ListObjects: calling handler <function decode_list_object at 0x10ef03e50>
```

**Comment by swetashre** [comment]
@pglass - Thank you for your post. Irrespective of anything when we create a client with boto3, botocore will look for valid sets of credential. So it will look in every possible places in [this order](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/credentials.html) and then it will try to fetch from instance metadata if the credentials has not been found in other places. 
That's why you are hitting that error after creating the client. But it won't impact the stubber as Stubber stubs out requests so you don't have to hit an endpoint.

**Comment by pglass** [comment]
@swetashre Understood. Is there a way to configure the session/client so that it does not look for any credentials? I'd like to avoid unintentionally using valid credentials in unit tests.

**Comment by swetashre** [comment]
@pglass - You can pass dummy credentials while creating client so that it won't look for any credentials. Something like this:
```python
s3 = boto3.client('s3',aws_access_key_id = 'foo',aws_secret_access_key='bar')
```
