### ISSUE TITLE
Recently started getting  "No module named 'botocore.docs'"

### ISSUE THREAD

**Issue by datacubed** [boto/botocore#2357]
**Describe the bug**
Getting " No module named 'botocore.docs'" error.

**Steps to reproduce**
start python3 shell, run "import boto3", get error.

**Expected behavior**
No error.

**Debug logs**
Full stack trace by adding 
```

>>> import boto3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/boto3/__init__.py", line 16, in <module>
    from boto3.session import Session
  File "/usr/local/lib/python3.6/dist-packages/boto3/session.py", line 17, in <module>
    import botocore.session
  File "/usr/local/lib/python3.6/dist-packages/botocore/session.py", line 31, in <module>
    import botocore.client
  File "/usr/local/lib/python3.6/dist-packages/botocore/client.py", line 16, in <module>
    from botocore import waiter, xform_name
  File "/usr/local/lib/python3.6/dist-packages/botocore/waiter.py", line 18, in <module>
    from botocore.docs.docstring import WaiterDocstring
ModuleNotFoundError: No module named 'botocore.docs'
```

**Comment by kdaily** [comment]
Hi @datacubed,

I can't reproduce with the latest `boto3==1.17.53`. Can you provide more details about the version you're using, operating system and environment, and how you installed? Thanks!
