### ISSUE TITLE
get_object_lock_configuration computes wrong signature when using v2 authentication

### ISSUE THREAD

**Issue by lucasso** [boto/botocore#2468]
**Describe the bug**
wrong StringToSign is produced by HmacV1Auth class when signing GetObjectLockConfiguration request

**Steps to reproduce**
```
import logging, botocore, botocore.session
session = botocore.session.get_session()
session.set_stream_logger('botocore', logging.DEBUG)
cl = session.create_client('s3', config=botocore.config.Config(signature_version="s3"))
cl.get_object_lock_configuration(Bucket="aaa")
```
gives **SignatureDoesNotMatch**
`botocore.exceptions.ClientError: An error occurred (SignatureDoesNotMatch) when calling the GetObjectLockConfiguration operation: The request signature we calculated does not match the signature you provided. Check your key and signing method.`

When using `signature_version="s3v4"` code works correctly and gives **AccessDenied**
 `botocore.exceptions.ClientError: An error occurred (AccessDenied) ` as expected (because "aaa" bucket is old but not mine)

The problem is that word "?object-lock" is not included in StringToSign by botocore, but it is included by AWS when computing signature. I've created a pull request which fixes this issue (see link below). Please review and merge.

**Expected behavior**
AccessDenied error instead of SignatureDoesNotMatch error

**Debug logs**
```
2021-08-26 07:33:19,183 - botocore.hooks - DEBUG - Event before-parameter-build.s3.GetObjectLockConfiguration: calling handler <function validate_bucket_name at 0x7f80a2691d50>
2021-08-26 07:33:19,183 - botocore.hooks - DEBUG - Event before-parameter-build.s3.GetObjectLockConfiguration: calling handler <bound method S3RegionRedirector.redirect_from_cache of <botocore.utils.S3RegionRedirector object at 0x7f80a0b84590>>
2021-08-26 07:33:19,183 - botocore.hooks - DEBUG - Event before-parameter-build.s3.GetObjectLockConfiguration: calling handler <bound method S3ArnParamHandler.handle_arn of <botocore.utils.S3ArnParamHandler object at 0x7f80a0b845d0>>
2021-08-26 07:33:19,184 - botocore.hooks - DEBUG - Event before-parameter-build.s3.GetObjectLockConfiguration: calling handler <function generate_idempotent_uuid at 0x7f80a2691bd0>
2021-08-26 07:33:19,184 - botocore.hooks - DEBUG - Event before-call.s3.GetObjectLockConfiguration: calling handler <function add_expect_header at 0x7f80a26970d0>
2021-08-26 07:33:19,184 - botocore.hooks - DEBUG - Event before-call.s3.GetObjectLockConfiguration: calling handler <bound method S3RegionRedirector.set_request_url of <botocore.utils.S3RegionRedirector object at 0x7f80a0b84590>>
2021-08-26 07:33:19,184 - botocore.hooks - DEBUG - Event before-call.s3.GetObjectLockConfiguration: calling handler <function inject_api_version_header_if_needed at 0x7f80a2698250>
2021-08-26 07:33:19,184 - botocore.endpoint - DEBUG - Making request for OperationModel(name=GetObjectLockConfiguration) with params: {'body': '', 'url': u'https://s3.amazonaws.com/aaa?object-lock', 'headers': {'User-Agent': 'Botocore/1.20.112 Python/2.7.17 Linux/4.19.9-1.el7.elrepo.x86_64'}, 'context': {'auth_type': None, 'client_region': 'us-east-1', 'signing': {'bucket': 'aaa'}, 'has_streaming_input': False, 'client_config': <botocore.config.Config object at 0x7f80a0c17510>}, 'query_string': {}, 'url_path': u'/aaa?object-lock', 'method': u'GET'}
2021-08-26 07:33:19,184 - botocore.hooks - DEBUG - Event request-created.s3.GetObjectLockConfiguration: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x7f80a0c174d0>>
2021-08-26 07:33:19,184 - botocore.hooks - DEBUG - Event choose-signer.s3.GetObjectLockConfiguration: calling handler <function set_operation_specific_signer at 0x7f80a2691ad0>
2021-08-26 07:33:19,184 - botocore.hooks - DEBUG - Event before-sign.s3.GetObjectLockConfiguration: calling handler <bound method S3EndpointSetter.set_endpoint of <botocore.utils.S3EndpointSetter object at 0x7f80a0b84610>>
2021-08-26 07:33:19,185 - botocore.utils - DEBUG - Defaulting to S3 virtual host style addressing with path style addressing fallback.
2021-08-26 07:33:19,185 - botocore.utils - DEBUG - Checking for DNS compatible bucket for: https://s3.amazonaws.com/aaa?object-lock
2021-08-26 07:33:19,185 - botocore.utils - DEBUG - URI updated to: https://aaa.s3.amazonaws.com/?object-lock
2021-08-26 07:33:19,185 - botocore.auth - DEBUG - Calculating signature using hmacv1 auth.
2021-08-26 07:33:19,185 - botocore.auth - DEBUG - HTTP request method: GET
2021-08-26 07:33:19,185 - botocore.auth - DEBUG - StringToSign:
GET


Thu, 26 Aug 2021 07:33:19 GMT
/aaa/
2021-08-26 07:33:19,185 - botocore.endpoint - DEBUG - Sending http request: <AWSPreparedRequest stream_output=False, method=GET, url=https://aaa.s3.amazonaws.com/?object-lock, headers={'Date': 'Thu, 26 Aug 2021 07:33:19 GMT', 'Authorization': 'AWS ..(removed)..', 'User-Agent': 'Botocore/1.20.112 Python/2.7.17 Linux/4.19.9-1.el7.elrepo.x86_64'}>
2021-08-26 07:33:19,185 - botocore.httpsession - DEBUG - Certificate path: /opt/rh/python27/root/usr/lib/python2.7/site-packages/botocore/cacert.pem
2021-08-26 07:33:19,793 - botocore.parsers - DEBUG - Response headers: {'x-amz-id-2': 'MGJaow/WWc4TAzSqDbuKM/D6xOs2OlgI2OfNuygRsEG0fAty5MoLgpWG6P0GOVbh3jOQVHrunNQ=', 'Server': 'AmazonS3', 'Transfer-Encoding': 'chunked', 'x-amz-request-id': '8YHVANAZHCFSHKCY', 'Date': 'Thu, 26 Aug 2021 07:33:18 GMT', 'Content-Type': 'application/xml'}
2021-08-26 07:33:19,793 - botocore.parsers - DEBUG - Response body:
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message><AWSAccessKeyId>...(removed)...</AWSAccessKeyId><StringToSign>GET


Thu, 26 Aug 2021 07:33:19 GMT
/aaa/?object-lock</StringToSign><SignatureProvided>M1BYkvOvkrp0H9E1EZ4sdmKVb2I=</SignatureProvided><StringToSignBytes>47 45 54 0a 0a 0a 54 68 75 2c 20 32 36 20 41 75 67 20 32 30 32 31 20 30 37 3a 33 33 3a 31 39 20 47 4d 54 0a 2f 61 61 61 2f 3f 6f 62 6a 65 63 74 2d 6c 6f 63 6b</StringToSignBytes><RequestId>8YHVANAZHCFSHKCY</RequestId><HostId>MGJaow/WWc4TAzSqDbuKM/D6xOs2OlgI2OfNuygRsEG0fAty5MoLgpWG6P0GOVbh3jOQVHrunNQ=</HostId></Error>
2021-08-26 07:33:19,796 - botocore.hooks - DEBUG - Event needs-retry.s3.GetObjectLockConfiguration: calling handler <botocore.retryhandler.RetryHandler object at 0x7f80a0b84510>
2021-08-26 07:33:19,796 - botocore.retryhandler - DEBUG - No retry needed.
2021-08-26 07:33:19,796 - botocore.hooks - DEBUG - Event needs-retry.s3.GetObjectLockConfiguration: calling handler <bound method S3RegionRedirector.redirect_from_error of <botocore.utils.S3RegionRedirector object at 0x7f80a0b84590>>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/botocore/client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (SignatureDoesNotMatch) when calling the GetObjectLockConfiguration operation: The request signature we calculated does not match the signature you provided. Check your key and signing method.
```

**Comment by stobrien89** [comment]
Hi @lucasso,

I reviewed this with the team today and they are willing to accept a contribution for this.  The only thing that's missing would be a unit tests (basically just demonstrating that this works for the specified command).

**Comment by lucasso** [comment]
Hi @stobrien89,
ok I will try to add a simple unittest. However best verification of this fix was already made by me manually on AWS and some old bucket by executing "steps to reproduce" of this issue description and verifying that "Access Denied" error vanished.

**Comment by lucasso** [comment]
Working on a unittest. I should finish in a week.

**Comment by stobrien89** [comment]
Thanks for the update @lucasso!  We'll keep an eye out for the pull request.

**Comment by lucasso** [comment]
Unittest added in a pull request. Please check if it is enough.
