### ISSUE TITLE
Bug in auth.py causing pipeline to fail

### ISSUE THREAD

**Issue by f1pratyush** [boto/botocore#2525]
**Describe the bug**
Package awscli has a dependency on botocore/auth.py. While running `$(aws ecr get-login)`, it throws an error.

**Steps to reproduce**
Install awscli using pip3
Run $(aws ecr get-login)

**Expected behavior**
Should execute login to AWS ECR.

**Debug logs**

```
$ $(aws ecr get-login --no-include-email --region ap-south-1)
Traceback (most recent call last):
  File "/usr/local/bin/aws", line 19, in <module>
    import awscli.clidriver
  File "/usr/local/lib/python3.5/dist-packages/awscli/clidriver.py", line 17, in <module>
    import botocore.session
  File "/usr/local/lib/python3.5/dist-packages/botocore/session.py", line 30, in <module>
    import botocore.client
  File "/usr/local/lib/python3.5/dist-packages/botocore/client.py", line 16, in <module>
    from botocore.args import ClientArgsCreator
  File "/usr/local/lib/python3.5/dist-packages/botocore/args.py", line 26, in <module>
    from botocore.signers import RequestSigner
  File "/usr/local/lib/python3.5/dist-packages/botocore/signers.py", line 19, in <module>
    import botocore.auth
  File "/usr/local/lib/python3.5/dist-packages/botocore/auth.py", line 121
    pairs.append(f'{quoted_key}={quoted_value}')
                                              ^
SyntaxError: invalid syntax
```

**Comment by nateprewitt** [comment]
Hi @f1pratyush,

Thanks for opening this issue. As @durzo has pointed out the AWS CLI, Boto3, and Botocore all dropped support for Python 3.5 back in February of 2021. This just happens to be the first introduction of a Python 3.6 specific feature.

Our recommendation is to either update to a modern version of pip (>9.0.2) that will automatically install the last supported version of the CLI, or manually pin to `awscli<1.19`.

For anyone arriving at this issue using Python 2.7, I’ve added a similar comment [here](https://github.com/boto/botocore/pull/2478#issuecomment-939678100).

Please let us know if you have any other questions.
