### ISSUE TITLE
1.21.63: install failis

### ISSUE THREAD

**Issue by kloczek** [boto/botocore#2536]
Looks like `sertptools` install command fails on missin file
```console
+ /usr/bin/python3 setup.py install -O1 --skip-build --root /home/tkloczko/rpmbuild/BUILDROOT/python-boto3-1.18.63-2.fc35.x86_64
Traceback (most recent call last):
  File "setup.py", line 29, in <module>
  File "setup.py", line 23, in get_version
FileNotFoundError: [Errno 2] No such file or directory: 'boto3/__init__.py'
```
I'm using as source tar ball generated from git tag.

**Comment by kloczek** [comment]
I'm not genrerating sdist tar ball.
Just "setup.py build" -> "setup.py install".

**Comment by kloczek** [comment]
Just tested 1.21.64 and looks like there is no that issue.
After that I've repeated test with 1.21.63 and in the same build env still that issue is present.

As it works now I'm closing that ticket.
