### ISSUE TITLE
ImportWarning due to vendored six in Python 3.10

### ISSUE THREAD

**Issue by bmw** [boto/botocore#2548]
**Describe the bug**
The vendored version of six in botocore causes ImportWarnings to be raised in Python 3.10.

**Steps to reproduce**
Using Python 3.10.0 and botocore 1.22.7:
```
$ python -Werror -c 'import botocore.session'                    
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 939, in _find_spec
AttributeError: '_SixMetaPathImporter' object has no attribute 'find_spec'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/private/var/folders/tr/_jqrlt554c107b5lcxl3td_40000gn/T/tmp.LwoO2GPSyX/venv/lib/python3.10/site-packages/botocore/session.py", line 28, in <module>
    import botocore.configloader
  File "/private/var/folders/tr/_jqrlt554c107b5lcxl3td_40000gn/T/tmp.LwoO2GPSyX/venv/lib/python3.10/site-packages/botocore/configloader.py", line 19, in <module>
    from botocore.compat import six
  File "/private/var/folders/tr/_jqrlt554c107b5lcxl3td_40000gn/T/tmp.LwoO2GPSyX/venv/lib/python3.10/site-packages/botocore/compat.py", line 27, in <module>
    from dateutil.tz import tzlocal
  File "/private/var/folders/tr/_jqrlt554c107b5lcxl3td_40000gn/T/tmp.LwoO2GPSyX/venv/lib/python3.10/site-packages/dateutil/tz/__init__.py", line 2, in <module>
    from .tz import *
  File "/private/var/folders/tr/_jqrlt554c107b5lcxl3td_40000gn/T/tmp.LwoO2GPSyX/venv/lib/python3.10/site-packages/dateutil/tz/tz.py", line 21, in <module>
    from six.moves import _thread
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1002, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 941, in _find_spec
  File "<frozen importlib._bootstrap>", line 914, in _find_spec_legacy
ImportWarning: _SixMetaPathImporter.find_spec() not found; falling back to find_module()
```

**Expected behavior**
I think botocore shouldn't cause warnings to be raised as it causes problems for the packages that depend on it if they error on warnings which is a common practice during testing.

This problem seems to be fixed in newer versions of six.

**Comment by nateprewitt** [comment]
Hi @bmw, thanks for opening this! We're aware there are some latent issues with our six usage that are surfacing in 3.10. We're currently trying to get to a point where we can minimize, or completely remove our use of six in the library. It's no longer strictly needed after dropping Python 2.7 support, and we have a proposal for its removal in #2512. That would be the best place to track progress.

Please let us know if you have any other questions in the interim.

**Comment by nateprewitt** [comment]
We've updated our vendored copy of six in the meantime and it should be available in the next release of botocore. That should resolve the warnings for the time being.
