### ISSUE TITLE
DeprecationWarning due to ssl.PROTOCOL_SSLv23 use in Python 3.10

### ISSUE THREAD

**Issue by bmw** [boto/botocore#2550]
**Describe the bug**
The use of `ssl.PROTOCOL_SSLv23` from the Python standard library causes DeprecationWarnings to be raised from botocore in Python 3.10.

**Steps to reproduce**
Using Python 3.10.0 and botocore 1.22.7:
```
python -W'error::DeprecationWarning' -c 'import botocore.session; botocore.session.get_session().create_client("route53")'          
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/private/var/folders/tr/_jqrlt554c107b5lcxl3td_40000gn/T/tmp.LwoO2GPSyX/venv/lib/python3.10/site-packages/botocore/session.py", line 833, in create_client
    credentials = self.get_credentials()
  File "/private/var/folders/tr/_jqrlt554c107b5lcxl3td_40000gn/T/tmp.LwoO2GPSyX/venv/lib/python3.10/site-packages/botocore/session.py", line 435, in get_credentials
    self._credentials = self._components.get_component(
  File "/private/var/folders/tr/_jqrlt554c107b5lcxl3td_40000gn/T/tmp.LwoO2GPSyX/venv/lib/python3.10/site-packages/botocore/session.py", line 944, in get_component
    self._components[name] = factory()
  File "/private/var/folders/tr/_jqrlt554c107b5lcxl3td_40000gn/T/tmp.LwoO2GPSyX/venv/lib/python3.10/site-packages/botocore/session.py", line 149, in _create_credential_resolver
    return botocore.credentials.create_credential_resolver(
  File "/private/var/folders/tr/_jqrlt554c107b5lcxl3td_40000gn/T/tmp.LwoO2GPSyX/venv/lib/python3.10/site-packages/botocore/credentials.py", line 80, in create_credential_resolver
    container_provider = ContainerProvider()
  File "/private/var/folders/tr/_jqrlt554c107b5lcxl3td_40000gn/T/tmp.LwoO2GPSyX/venv/lib/python3.10/site-packages/botocore/credentials.py", line 1832, in __init__
    fetcher = ContainerMetadataFetcher()
  File "/private/var/folders/tr/_jqrlt554c107b5lcxl3td_40000gn/T/tmp.LwoO2GPSyX/venv/lib/python3.10/site-packages/botocore/utils.py", line 2281, in __init__
    session = botocore.httpsession.URLLib3Session(
  File "/private/var/folders/tr/_jqrlt554c107b5lcxl3td_40000gn/T/tmp.LwoO2GPSyX/venv/lib/python3.10/site-packages/botocore/httpsession.py", line 216, in __init__
    self._manager = PoolManager(**self._get_pool_manager_kwargs())
  File "/private/var/folders/tr/_jqrlt554c107b5lcxl3td_40000gn/T/tmp.LwoO2GPSyX/venv/lib/python3.10/site-packages/botocore/httpsession.py", line 235, in _get_pool_manager_kwargs
    'ssl_context': self._get_ssl_context(),
  File "/private/var/folders/tr/_jqrlt554c107b5lcxl3td_40000gn/T/tmp.LwoO2GPSyX/venv/lib/python3.10/site-packages/botocore/httpsession.py", line 244, in _get_ssl_context
    return create_urllib3_context()
  File "/private/var/folders/tr/_jqrlt554c107b5lcxl3td_40000gn/T/tmp.LwoO2GPSyX/venv/lib/python3.10/site-packages/botocore/httpsession.py", line 62, in create_urllib3_context
    context = SSLContext(ssl_version or ssl.PROTOCOL_SSLv23)
  File "/Users/bmw/.pyenv/versions/3.10.0/lib/python3.10/ssl.py", line 495, in __new__
    self = _SSLContext.__new__(cls, protocol)
DeprecationWarning: ssl.PROTOCOL_TLS is deprecated
```

**Expected behavior**
I think botocore shouldn't cause warnings to be raised as it causes problems for the packages that depend on it if they error on warnings which is a common practice during testing.

The problematic code in the traceback here is the use of ssl.PROTOCOL_SSLv23 at https://github.com/boto/botocore/blob/3a830887451f3a096bd69965d6e79fdcda95954f/botocore/httpsession.py#L62

since [ssl.PROTOCOL_SSLv23 is an alias for  ssl.PROTOCOL_TLS](https://docs.python.org/3/library/ssl.html#ssl.PROTOCOL_SSLv23) and [ssl.PROTOCOL_TLS was deprecated in Python 3.10](https://docs.python.org/3/library/ssl.html#ssl.PROTOCOL_TLS).

I'll also add that I initially hit this while using `boto3` with the simple code:
```
import boto3
boto3.client("route53")
```

**Comment by bmw** [comment]
Based on a quick look at docs for [ssl.PROTOCOL_TLS_CLIENT](https://docs.python.org/3/library/ssl.html#ssl.PROTOCOL_TLS_CLIENT) which is the preferred alternative and the relevant botocore code, this doesn't look like a security issue. The docs say it enables CERT_REQUIRED which [botocore already does by default](https://github.com/boto/botocore/blob/1.22.7/botocore/httpsession.py#L65) and check_hostname which [botocore disables in favor of its own implementation](https://github.com/boto/botocore/blob/1.22.7/botocore/httpsession.py#L86-L88).

**Comment by nateprewitt** [comment]
Hi @bmw, this is actually vendored directly from [urllib3](https://github.com/urllib3/urllib3/blob/1.26.x/src/urllib3/util/ssl_.py#L250-L352). They're still using the deprecated alias, so we'll need to wait till it's addressed upstream. I agree there isn't a security concern with the existing usage, it's just added noise to the warnings for now.

**Comment by nateprewitt** [comment]
We've upgraded our vendored copy of the `create_urllib3_context` function to support the correct aliases and match our currently supported versions of urllib3.
