### ISSUE TITLE
SSO executable not found

### ISSUE THREAD

**Issue by jowparks** [boto/botocore#2585]
**Describe the bug**
SSO login and cached credentials broken with 
```
boto3                      1.20.30    The AWS SDK for Python
botocore                   1.23.30    Low-level, data-driven core of boto 3.
```

**Steps to reproduce**
Have profile for sso configured
Run aws login from cli ( ie `aws sso login --profile sso-non-prd`)
Export AWS_PROFILE=sso-non-prd
Run python command that executes:
`boto3.client("s3")`

**Expected behavior**
Client should instantiate

**Debug logs**
```
-------------------------------------------------------------------------------------------------- Captured log call ---------------------------------------------------------------------------------------------------
2022-01-06 14:27:06 WARNING Refreshing temporary credentials failed during mandatory refresh period.
Traceback (most recent call last):
  File "/Users/joe.parks/Library/Caches/pypoetry/virtualenvs/snowflake-rdp-broker-r-r8Q6G1-py3.9/lib/python3.9/site-packages/botocore/credentials.py", line 540, in _protected_refresh
    metadata = self._refresh_using()
  File "/Users/joe.parks/Library/Caches/pypoetry/virtualenvs/snowflake-rdp-broker-r-r8Q6G1-py3.9/lib/python3.9/site-packages/botocore/credentials.py", line 681, in fetch_credentials
    return self._get_cached_credentials()
  File "/Users/joe.parks/Library/Caches/pypoetry/virtualenvs/snowflake-rdp-broker-r-r8Q6G1-py3.9/lib/python3.9/site-packages/botocore/credentials.py", line 691, in _get_cached_credentials
    response = self._get_credentials()
  File "/Users/joe.parks/Library/Caches/pypoetry/virtualenvs/snowflake-rdp-broker-r-r8Q6G1-py3.9/lib/python3.9/site-packages/botocore/credentials.py", line 2045, in _get_credentials
    client = self._client_creator('sso', config=config)
  File "/Users/joe.parks/Library/Caches/pypoetry/virtualenvs/snowflake-rdp-broker-r-r8Q6G1-py3.9/lib/python3.9/site-packages/botocore/session.py", line 841, in create_client
    client = client_creator.create_client(
  File "/Users/joe.parks/Library/Caches/pypoetry/virtualenvs/snowflake-rdp-broker-r-r8Q6G1-py3.9/lib/python3.9/site-packages/botocore/client.py", line 83, in create_client
    service_model = self._load_service_model(service_name, api_version)
  File "/Users/joe.parks/Library/Caches/pypoetry/virtualenvs/snowflake-rdp-broker-r-r8Q6G1-py3.9/lib/python3.9/site-packages/botocore/client.py", line 150, in _load_service_model
    json_model = self._loader.load_service_model(service_name, 'service-2',
  File "/Users/joe.parks/Library/Caches/pypoetry/virtualenvs/snowflake-rdp-broker-r-r8Q6G1-py3.9/lib/python3.9/site-packages/botocore/loaders.py", line 132, in _wrapper
    data = func(self, *args, **kwargs)
  File "/Users/joe.parks/Library/Caches/pypoetry/virtualenvs/snowflake-rdp-broker-r-r8Q6G1-py3.9/lib/python3.9/site-packages/botocore/loaders.py", line 381, in load_service_model
    api_version = self.determine_latest_version(
  File "/Users/joe.parks/Library/Caches/pypoetry/virtualenvs/snowflake-rdp-broker-r-r8Q6G1-py3.9/lib/python3.9/site-packages/botocore/loaders.py", line 132, in _wrapper
    data = func(self, *args, **kwargs)
  File "/Users/joe.parks/Library/Caches/pypoetry/virtualenvs/snowflake-rdp-broker-r-r8Q6G1-py3.9/lib/python3.9/site-packages/botocore/loaders.py", line 311, in determine_latest_version
    return max(self.list_api_versions(service_name, type_name))
  File "/Users/joe.parks/Library/Caches/pypoetry/virtualenvs/snowflake-rdp-broker-r-r8Q6G1-py3.9/lib/python3.9/site-packages/botocore/loaders.py", line 132, in _wrapper
    data = func(self, *args, **kwargs)
  File "/Users/joe.parks/Library/Caches/pypoetry/virtualenvs/snowflake-rdp-broker-r-r8Q6G1-py3.9/lib/python3.9/site-packages/botocore/loaders.py", line 332, in list_api_versions
    for dirname in os.listdir(possible_path):
FileNotFoundError: [Errno 2] No such file or directory: '/Users/joe.parks/Library/Caches/pypoetry/virtualenvs/snowflake-rdp-broker-r-r8Q6G1-py3.9/lib/python3.9/site-packages/boto3/data/sso'
```
Full stack trace by adding 
```
-------------------------------------------------------------------------------------------------- Captured log call ---------------------------------------------------------------------------------------------------
2022-01-06 14:42:29 DEBUG Event before-parameter-build.s3.GetObject: calling handler <function sse_md5 at 0x15815e280>
2022-01-06 14:42:29 DEBUG Event before-parameter-build.s3.GetObject: calling handler <function validate_bucket_name at 0x15815e1f0>
2022-01-06 14:42:29 DEBUG Event before-parameter-build.s3.GetObject: calling handler <bound method S3RegionRedirector.redirect_from_cache of <botocore.utils.S3RegionRedirector object at 0x15bebc490>>
2022-01-06 14:42:29 DEBUG Event before-parameter-build.s3.GetObject: calling handler <bound method S3ArnParamHandler.handle_arn of <botocore.utils.S3ArnParamHandler object at 0x15bebc4c0>>
2022-01-06 14:42:29 DEBUG Event before-parameter-build.s3.GetObject: calling handler <function generate_idempotent_uuid at 0x15815e040>
2022-01-06 14:42:29 DEBUG Event before-call.s3.GetObject: calling handler <function add_expect_header at 0x15815e550>
2022-01-06 14:42:29 DEBUG Event before-call.s3.GetObject: calling handler <bound method S3RegionRedirector.set_request_url of <botocore.utils.S3RegionRedirector object at 0x15bebc490>>
2022-01-06 14:42:29 DEBUG Event before-call.s3.GetObject: calling handler <function inject_api_version_header_if_needed at 0x1581608b0>
2022-01-06 14:42:29 DEBUG Making request for OperationModel(name=GetObject) with params: {'url_path': '/some_bucket/some/local/file.tsv', 'query_string': {}, 'method': 'GET', 'headers': {'User-Agent': 'Boto3/1.20.30 Python/3.9.5 Darwin/20.6.0 Botocore/1.23.30'}, 'body': b'', 'url': 'https://s3.amazonaws.com/some_bucket/some/local/file.tsv', 'context': {'client_region': 'us-east-1', 'client_config': <botocore.config.Config object at 0x15be82430>, 'has_streaming_input': False, 'auth_type': None, 'signing': {'bucket': 'some_bucket'}}}
2022-01-06 14:42:29 DEBUG Event request-created.s3.GetObject: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x15be82460>>
2022-01-06 14:42:29 DEBUG Event choose-signer.s3.GetObject: calling handler <bound method S3EndpointSetter.set_signer of <botocore.utils.S3EndpointSetter object at 0x15bebc580>>
2022-01-06 14:42:29 DEBUG Event choose-signer.s3.GetObject: calling handler <bound method ClientCreator._default_s3_presign_to_sigv2 of <botocore.client.ClientCreator object at 0x15b87f100>>
2022-01-06 14:42:29 DEBUG Event choose-signer.s3.GetObject: calling handler <function set_operation_specific_signer at 0x158155ee0>
2022-01-06 14:42:29 DEBUG Event before-sign.s3.GetObject: calling handler <bound method S3EndpointSetter.set_endpoint of <botocore.utils.S3EndpointSetter object at 0x15bebc580>>
2022-01-06 14:42:29 DEBUG Defaulting to S3 virtual host style addressing with path style addressing fallback.
2022-01-06 14:42:29 DEBUG Checking for DNS compatible bucket for: https://s3.amazonaws.com/some_bucket/some/local/file.tsv
2022-01-06 14:42:29 DEBUG Not changing URI, bucket is not DNS compatible: some_bucket
2022-01-06 14:42:29 DEBUG Event choose-service-name: calling handler <function handle_service_name_alias at 0x15813ab80>
2022-01-06 14:42:29 WARNING Refreshing temporary credentials failed during mandatory refresh period.
Traceback (most recent call last):
  File "/Users/joe.parks/Library/Caches/pypoetry/virtualenvs/snowflake-rdp-broker-r-r8Q6G1-py3.9/lib/python3.9/site-packages/botocore/credentials.py", line 540, in _protected_refresh
    metadata = self._refresh_using()
  File "/Users/joe.parks/Library/Caches/pypoetry/virtualenvs/snowflake-rdp-broker-r-r8Q6G1-py3.9/lib/python3.9/site-packages/botocore/credentials.py", line 681, in fetch_credentials
    return self._get_cached_credentials()
  File "/Users/joe.parks/Library/Caches/pypoetry/virtualenvs/snowflake-rdp-broker-r-r8Q6G1-py3.9/lib/python3.9/site-packages/botocore/credentials.py", line 691, in _get_cached_credentials
    response = self._get_credentials()
  File "/Users/joe.parks/Library/Caches/pypoetry/virtualenvs/snowflake-rdp-broker-r-r8Q6G1-py3.9/lib/python3.9/site-packages/botocore/credentials.py", line 2045, in _get_credentials
    client = self._client_creator('sso', config=config)
  File "/Users/joe.parks/Library/Caches/pypoetry/virtualenvs/snowflake-rdp-broker-r-r8Q6G1-py3.9/lib/python3.9/site-packages/botocore/session.py", line 841, in create_client
    client = client_creator.create_client(
  File "/Users/joe.parks/Library/Caches/pypoetry/virtualenvs/snowflake-rdp-broker-r-r8Q6G1-py3.9/lib/python3.9/site-packages/botocore/client.py", line 83, in create_client
    service_model = self._load_service_model(service_name, api_version)
  File "/Users/joe.parks/Library/Caches/pypoetry/virtualenvs/snowflake-rdp-broker-r-r8Q6G1-py3.9/lib/python3.9/site-packages/botocore/client.py", line 150, in _load_service_model
    json_model = self._loader.load_service_model(service_name, 'service-2',
  File "/Users/joe.parks/Library/Caches/pypoetry/virtualenvs/snowflake-rdp-broker-r-r8Q6G1-py3.9/lib/python3.9/site-packages/botocore/loaders.py", line 132, in _wrapper
    data = func(self, *args, **kwargs)
  File "/Users/joe.parks/Library/Caches/pypoetry/virtualenvs/snowflake-rdp-broker-r-r8Q6G1-py3.9/lib/python3.9/site-packages/botocore/loaders.py", line 381, in load_service_model
    api_version = self.determine_latest_version(
  File "/Users/joe.parks/Library/Caches/pypoetry/virtualenvs/snowflake-rdp-broker-r-r8Q6G1-py3.9/lib/python3.9/site-packages/botocore/loaders.py", line 132, in _wrapper
    data = func(self, *args, **kwargs)
  File "/Users/joe.parks/Library/Caches/pypoetry/virtualenvs/snowflake-rdp-broker-r-r8Q6G1-py3.9/lib/python3.9/site-packages/botocore/loaders.py", line 311, in determine_latest_version
    return max(self.list_api_versions(service_name, type_name))
  File "/Users/joe.parks/Library/Caches/pypoetry/virtualenvs/snowflake-rdp-broker-r-r8Q6G1-py3.9/lib/python3.9/site-packages/botocore/loaders.py", line 132, in _wrapper
    data = func(self, *args, **kwargs)
  File "/Users/joe.parks/Library/Caches/pypoetry/virtualenvs/snowflake-rdp-broker-r-r8Q6G1-py3.9/lib/python3.9/site-packages/botocore/loaders.py", line 332, in list_api_versions
    for dirname in os.listdir(possible_path):
FileNotFoundError: [Errno 2] No such file or directory: '/Users/joe.parks/Library/Caches/pypoetry/virtualenvs/snowflake-rdp-broker-r-r8Q6G1-py3.9/lib/python3.9/site-packages/boto3/data/sso'

```
to your code.

**Comment by tim-finnigan** [comment]
Hi @jowparks, thanks for reaching out. How did you configure SSO originally? Did you use this documentation for reference? https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sso.html
