### ISSUE TITLE
Cannot connect to S3 bucket with transfer acceleration enabled

### ISSUE THREAD

**Issue by vsakkas** [boto/botocore#2653]
**Describe the bug**
Trying to do any sort of operation on an S3 bucket with the transfer acceleration feature, such as downloading or uploading a file fails with the error:
```
Cannot connect to host s3-accelerate.amazonaws.com:80 ssl:default
```

**Environment**
- **OS** Manjaro, but also reproducible on Ubuntu 18.04
- **Python** 3.7.4

**Steps to reproduce**
1. Using the AWS Dashboard, enable the transfer acceleration feature.
2. Download the following packages (this can be done with `pip install aioboto3==8.3.0`):
```
aioboto3==8.3.0
aiobotocore==1.2.2
aiohttp==3.8.1
aioitertools==0.10.0
aiosignal==1.2.0
async-timeout==4.0.2
asynctest==0.13.0
attrs==21.4.0
boto3==1.16.52
botocore==1.19.52
charset-normalizer==2.0.12
frozenlist==1.3.0
idna==3.3
jmespath==0.10.0
multidict==6.0.2
python-dateutil==2.8.2
s3transfer==0.3.7
six==1.16.0
typing-extensions==4.1.1
urllib3==1.26.9
wrapt==1.14.0
yarl==1.7.2
```
3. Use the following snippet to verify that downloading a file works **without** the transfer acceleration feature enabled:
```python
import asyncio

import aioboto3
from botocore.config import Config

BUCKET_NAME = ""
FILE_NAME = ""
DESTINATION_NAME = ""


async def main():
    async with aioboto3.client("s3", config=Config(s3={"use_accelerate_endpoint": False})) as s3_client:
         await s3_client.download_file(BUCKET_NAME, FILE_NAME, DESTINATION_NAME)

    print("Done!")


if __name__ == "__main__":
    asyncio.run(main())
```
The above code works without any issues for an existing bucket with an existing file.

4. Change the `False` flag to `True` in order to use the transfer acceleration feature. Rerun the code.
5. The following error is produced:
```
Traceback (most recent call last):
  File "/home/botocore-bug-report/.venv/lib/python3.7/site-packages/aiohttp/connector.py", line 1154, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "/home/botocore-bug-report/.venv/lib/python3.7/site-packages/aiohttp/connector.py", line 880, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "/home/botocore-bug-report/.venv/lib/python3.7/site-packages/aiohttp/resolver.py", line 38, in resolve
    flags=socket.AI_ADDRCONFIG,
  File "/home/.pyenv/versions/3.7.4/lib/python3.7/asyncio/base_events.py", line 784, in getaddrinfo
    None, getaddr_func, host, port, family, type, proto, flags)
  File "/home/.pyenv/versions/3.7.4/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/.pyenv/versions/3.7.4/lib/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -5] No address associated with hostname

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/botocore-bug-report/main.py", line 23, in <module>
    asyncio.run(main())
  File "/home/.pyenv/versions/3.7.4/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/home/.pyenv/versions/3.7.4/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "/home/botocore-bug-report/main.py", line 16, in main
    await s3_client.download_file(BUCKET_NAME, FILE_NAME, DESTINATION_NAME)
  File "/home/botocore-bug-report/.venv/lib/python3.7/site-packages/aioboto3/s3/inject.py", line 61, in download_file
    await download_fileobj(self, Bucket, Key, open_file, ExtraArgs=ExtraArgs, Callback=Callback, Config=Config)
  File "/home/botocore-bug-report/.venv/lib/python3.7/site-packages/aioboto3/s3/inject.py", line 107, in download_fileobj
    resp = await self.get_object(Bucket=Bucket, Key=Key, **ExtraArgs)
  File "/home/botocore-bug-report/.venv/lib/python3.7/site-packages/aiobotocore/client.py", line 141, in _make_api_call
    operation_model, request_dict, request_context)
  File "/home/botocore-bug-report/.venv/lib/python3.7/site-packages/aiobotocore/client.py", line 160, in _make_request
    return await self._endpoint.make_request(operation_model, request_dict)
  File "/home/botocore-bug-report/.venv/lib/python3.7/site-packages/aiobotocore/endpoint.py", line 91, in _send_request
    exception):
  File "/home/botocore-bug-report/.venv/lib/python3.7/site-packages/aiobotocore/endpoint.py", line 200, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "/home/botocore-bug-report/.venv/lib/python3.7/site-packages/aiobotocore/hooks.py", line 29, in _emit
    response = handler(**kwargs)
  File "/home/botocore-bug-report/.venv/lib/python3.7/site-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/home/botocore-bug-report/.venv/lib/python3.7/site-packages/botocore/retryhandler.py", line 251, in __call__
    caught_exception)
  File "/home/botocore-bug-report/.venv/lib/python3.7/site-packages/botocore/retryhandler.py", line 277, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/home/botocore-bug-report/.venv/lib/python3.7/site-packages/botocore/retryhandler.py", line 317, in __call__
    caught_exception)
  File "/home/botocore-bug-report/.venv/lib/python3.7/site-packages/botocore/retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "/home/botocore-bug-report/.venv/lib/python3.7/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
  File "/home/botocore-bug-report/.venv/lib/python3.7/site-packages/aiobotocore/endpoint.py", line 156, in _do_get_response
    http_response = await self._send(request)
  File "/home/botocore-bug-report/.venv/lib/python3.7/site-packages/aiobotocore/endpoint.py", line 242, in _send
    request.method, url=url, headers=headers_, data=data, proxy=proxy)
  File "/home/botocore-bug-report/.venv/lib/python3.7/site-packages/aiohttp/client.py", line 536, in _request
    req, traces=traces, timeout=real_timeout
  File "/home/botocore-bug-report/.venv/lib/python3.7/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/botocore-bug-report/.venv/lib/python3.7/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/home/botocore-bug-report/.venv/lib/python3.7/site-packages/aiohttp/connector.py", line 1166, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host s3-accelerate.amazonaws.com:443 ssl:default [No address associated with hostname]
```

The important thing here is the `Cannot connect to host s3-accelerate.amazonaws.com:443 ssl:default` message.
According to the AWS dashboard (and [documentation](https://docs.aws.amazon.com/AmazonS3/latest/userguide/transfer-acceleration.html)), the endpoint should have this format:
```
bucket-name.s3-accelerate.amazonaws.com
```

When creating the client, it is also possible to provide the `endpoint_url` and `region_name` parameters, but neither of those can help resolve this issue (the same error is produced).

**Expected behavior**
File should have been downloaded, just like without the transfer acceleration enaled.

**Workaround**

After some digging in the botocore code, I've tracked down a function called `switch_host_s3_accelerate` which seems to be the culprint, as it receives the correct endpoint URL for my S3 bucket and replaces it with `s3-accelerate.amazonaws.com` which is the invalid one.

The following code fixes the issue by patching the culprit function with a somewhat modified one:
```python
import asyncio
from urllib.parse import urlparse

import aioboto3
from botocore import utils
from botocore.compat import urlsplit
from botocore.config import Config

BUCKET_NAME = ""
FILE_NAME = ""
DESTINATION_NAME = ""

def switch_host_s3_accelerate(request, operation_name, **kwargs):
    parts = urlsplit(request.url).netloc.split('.')
    parts = [p for p in parts if p in utils.S3_ACCELERATE_WHITELIST]
    endpoint = 'https://s3-accelerate.'
    if len(parts) > 0:
        endpoint += '.'.join(parts) + '.'
    endpoint += 'amazonaws.com'

    # This is the patch to the original function.
    o = urlparse(request.url)
    endpoint = o.scheme + '://' + ".".join(list(dict.fromkeys((o.hostname.split('.')))))

    if operation_name in ['ListBuckets', 'CreateBucket', 'DeleteBucket']:
        return
    utils._switch_hosts(request, endpoint,  use_new_scheme=False)


async def main():
    # Replace function with our own.
    utils.switch_host_s3_accelerate = switch_host_s3_accelerate

    async with await aioboto3.client("s3", config=Config(s3={"use_accelerate_endpoint": True})) as s3_client:
        await s3_client.download_file(BUCKET_NAME, FILE_NAME, DESTINATION_NAME)

    print("Done!")


if __name__ == "__main__":
    asyncio.run(main())
```

**Comment by kdaily** [comment]
Hi @vsakkas,

Thanks for posting.

I'm going to try and reproduce. However, we do not maintain or support `aioboto3`. Do you get this behavior when using the supported `boto3` package?
