### ISSUE TITLE
credentials.load_credentials fails on credential_process errors

### ISSUE THREAD

**Issue by kddejong** [boto/botocore#2779]
### Describe the bug

When using `credential_process` if that process errors out or returns invalid JSON the entire `load_credentials` process will fail instead of trying another mechanism.  

https://github.com/boto/botocore/blob/develop/botocore/credentials.py#L2092-L2097

### Expected Behavior

I expect `credentials.load_credentials` to return None if the `credential_process` fails or returns invalid JSON.

### Current Behavior

If the `credential_process` doesn't return JSON you will receive the following error
```
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    boto3.client("s3")
  File "/usr/local/lib/python3.8/site-packages/boto3/__init__.py", line 92, in client
    return _get_default_session().client(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/boto3/session.py", line 299, in client
    return self._session.create_client(
  File "/usr/local/lib/python3.8/site-packages/botocore/session.py", line 951, in create_client
    credentials = self.get_credentials()
  File "/usr/local/lib/python3.8/site-packages/botocore/session.py", line 507, in get_credentials
    self._credentials = self._components.get_component(
  File "/usr/local/lib/python3.8/site-packages/botocore/credentials.py", line 2095, in load_credentials
    creds = provider.load()
  File "/usr/local/lib/python3.8/site-packages/botocore/credentials.py", line 1033, in load
    creds_dict = self._retrieve_credentials_using(credential_process)
  File "/usr/local/lib/python3.8/site-packages/botocore/credentials.py", line 1063, in _retrieve_credentials_using
    raise CredentialRetrievalError(
botocore.exceptions.CredentialRetrievalError: Error when retrieving credentials from custom-process: Unsupported version '<Version key not provided>' for credential process provider, supported versions: 1
```

when return empty JSON you will get:
```
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    boto3.client("s3")
  File "/home/vscode/.local/lib/python3.8/site-packages/boto3/__init__.py", line 92, in client
    return _get_default_session().client(*args, **kwargs)
  File "/home/vscode/.local/lib/python3.8/site-packages/boto3/session.py", line 299, in client
    return self._session.create_client(
  File "/home/vscode/.local/lib/python3.8/site-packages/botocore/session.py", line 951, in create_client
    credentials = self.get_credentials()
  File "/home/vscode/.local/lib/python3.8/site-packages/botocore/session.py", line 507, in get_credentials
    self._credentials = self._components.get_component(
  File "/home/vscode/.local/lib/python3.8/site-packages/botocore/credentials.py", line 2095, in load_credentials
    creds = provider.load()
  File "/home/vscode/.local/lib/python3.8/site-packages/botocore/credentials.py", line 1033, in load
    creds_dict = self._retrieve_credentials_using(credential_process)
  File "/home/vscode/.local/lib/python3.8/site-packages/botocore/credentials.py", line 1063, in _retrieve_credentials_using
    raise CredentialRetrievalError(
botocore.exceptions.CredentialRetrievalError: Error when retrieving credentials from custom-process: Unsupported version '<Version key not provided>' for credential process provider, supported versions: 1
```

### Reproduction Steps

Create `~/.aws/config`
```
[default]
region=us-west-2
output=json
credential_process=echo ""
```
or 
```
[default]
region=us-west-2
output=json
credential_process=echo "{}"
```

Setup a boto3.client
```python
import boto3

boto3.client("s3")
```

### Possible Solution

Wrap try/catch around `credential_process` processing.
https://github.com/boto/botocore/blob/develop/botocore/credentials.py#L1060
```python
try:
    parsed = botocore.compat.json.loads(stdout.decode('utf-8'))
except json.decoder.JSONDecodeError:
    raise CredentialRetrievalError(
        provider=self.METHOD,
        error_msg=(
            f"Credential process must return valid json"
        ),
    )
```

https://github.com/boto/botocore/blob/develop/botocore/credentials.py#L2095
```python
try:
    creds = provider.load()
except Exception as exc:
    logger.debug("Credential load for provider %s failed with: %s", provider.METHOD, exc)
```

### Additional Information/Context

When setting up Stubber and using boto3.client the credential process will get executed. I don't believe this should be executed when setting up a client that will be used for testing.

Cross posting with https://github.com/boto/boto3/issues/3456

### SDK version used

1.27.91

### Environment details (OS name and version, etc.)

Mac, Amazon Linux

**Comment by aBurmeseDev** [comment]
Hi @kddejong, thanks for checking in. It looks like you cross-posted in the boto3 repo as well. We will be following up on that issue https://github.com/boto/boto3/issues/3456 and close this one. 

Best,
John
