### ISSUE TITLE
botocore 1.28.0 and higher fails when bucket has a period and FIPS is true in govcloud regions

### ISSUE THREAD

**Issue by slimm609** [boto/botocore#2800]
### Describe the bug

Starting with botocore 1.28.0, calls to s3 to download a file fails if the bucket name contains a period.  

A test bucket name that fails with error "botocore.exceptions.EndpointResolutionError: Path-style addressing cannot be used with FIPS"
```
my.botocore.test.bucket.name
```

### Expected Behavior

Buckets with periods work with FIPS endpoints in govcloud

Botocore 1.27.96 works properly.
```
2022-10-29 04:19:36,136 botocore.hooks [DEBUG] Changing event name from creating-client-class.iot-data to creating-client-class.iot-data-plane
2022-10-29 04:19:36,139 botocore.hooks [DEBUG] Changing event name from before-call.apigateway to before-call.api-gateway
2022-10-29 04:19:36,140 botocore.hooks [DEBUG] Changing event name from request-created.machinelearning.Predict to request-created.machine-learning.Predict
2022-10-29 04:19:36,142 botocore.hooks [DEBUG] Changing event name from before-parameter-build.autoscaling.CreateLaunchConfiguration to before-parameter-build.auto-scaling.CreateLaunchConfiguration
2022-10-29 04:19:36,142 botocore.hooks [DEBUG] Changing event name from before-parameter-build.route53 to before-parameter-build.route-53
2022-10-29 04:19:36,142 botocore.hooks [DEBUG] Changing event name from request-created.cloudsearchdomain.Search to request-created.cloudsearch-domain.Search
2022-10-29 04:19:36,143 botocore.hooks [DEBUG] Changing event name from docs.*.autoscaling.CreateLaunchConfiguration.complete-section to docs.*.auto-scaling.CreateLaunchConfiguration.complete-section
2022-10-29 04:19:36,145 botocore.hooks [DEBUG] Changing event name from before-parameter-build.logs.CreateExportTask to before-parameter-build.cloudwatch-logs.CreateExportTask
2022-10-29 04:19:36,146 botocore.hooks [DEBUG] Changing event name from docs.*.logs.CreateExportTask.complete-section to docs.*.cloudwatch-logs.CreateExportTask.complete-section
2022-10-29 04:19:36,146 botocore.hooks [DEBUG] Changing event name from before-parameter-build.cloudsearchdomain.Search to before-parameter-build.cloudsearch-domain.Search
2022-10-29 04:19:36,146 botocore.hooks [DEBUG] Changing event name from docs.*.cloudsearchdomain.Search.complete-section to docs.*.cloudsearch-domain.Search.complete-section
2022-10-29 04:19:36,163 botocore.loaders [DEBUG] Loading JSON file: /usr/local/lib/python3.7/site-packages/boto3/data/s3/2006-03-01/resources-1.json
2022-10-29 04:19:36,170 botocore.utils [DEBUG] IMDS ENDPOINT: http://169.254.169.254/
2022-10-29 04:19:36,172 botocore.credentials [DEBUG] Looking for credentials via: env
2022-10-29 04:19:36,172 botocore.credentials [DEBUG] Looking for credentials via: assume-role
2022-10-29 04:19:36,172 botocore.credentials [DEBUG] Looking for credentials via: assume-role-with-web-identity
2022-10-29 04:19:36,172 botocore.credentials [DEBUG] Looking for credentials via: sso
2022-10-29 04:19:36,172 botocore.credentials [DEBUG] Looking for credentials via: shared-credentials-file
2022-10-29 04:19:36,172 botocore.credentials [DEBUG] Looking for credentials via: custom-process
2022-10-29 04:19:36,172 botocore.credentials [DEBUG] Looking for credentials via: config-file
2022-10-29 04:19:36,173 botocore.credentials [DEBUG] Looking for credentials via: ec2-credentials-file
2022-10-29 04:19:36,173 botocore.credentials [DEBUG] Looking for credentials via: boto-config
2022-10-29 04:19:36,173 botocore.credentials [DEBUG] Looking for credentials via: container-role
2022-10-29 04:19:36,173 botocore.credentials [DEBUG] Looking for credentials via: iam-role
2022-10-29 04:19:36,174 urllib3.connectionpool [DEBUG] Starting new HTTP connection (1): 169.254.169.254:80
2022-10-29 04:19:36,177 urllib3.connectionpool [DEBUG] http://169.254.169.254:80 "PUT /latest/api/token HTTP/1.1" 200 56
2022-10-29 04:19:36,178 urllib3.connectionpool [DEBUG] Resetting dropped connection: 169.254.169.254
2022-10-29 04:19:36,179 urllib3.connectionpool [DEBUG] http://169.254.169.254:80 "GET /latest/meta-data/iam/security-credentials/ HTTP/1.1" 200 21
2022-10-29 04:19:36,179 urllib3.connectionpool [DEBUG] Resetting dropped connection: 169.254.169.254
2022-10-29 04:19:36,180 urllib3.connectionpool [DEBUG] http://169.254.169.254:80 "GET /latest/meta-data/iam/security-credentials/us-gov-west-1 HTTP/1.1" 200 1054
2022-10-29 04:19:36,183 botocore.credentials [INFO] Found credentials from IAM Role: us-gov-west-1
2022-10-29 04:19:36,185 botocore.loaders [DEBUG] Loading JSON file: /usr/local/lib/python3.7/site-packages/botocore/data/endpoints.json
2022-10-29 04:19:36,205 botocore.loaders [DEBUG] Loading JSON file: /usr/local/lib/python3.7/site-packages/botocore/data/sdk-default-configuration.json
2022-10-29 04:19:36,206 botocore.hooks [DEBUG] Event choose-service-name: calling handler <function handle_service_name_alias at 0x7f3a3c715560>
2022-10-29 04:19:36,225 botocore.loaders [DEBUG] Loading JSON file: /usr/local/lib/python3.7/site-packages/botocore/data/s3/2006-03-01/service-2.json
2022-10-29 04:19:36,244 botocore.hooks [DEBUG] Event creating-client-class.s3: calling handler <function add_generate_presigned_post at 0x7f3a3c726d40>
2022-10-29 04:19:36,244 botocore.hooks [DEBUG] Event creating-client-class.s3: calling handler <function lazy_call.<locals>._handler at 0x7f3a428d8170>
2022-10-29 04:19:36,266 botocore.hooks [DEBUG] Event creating-client-class.s3: calling handler <function add_generate_presigned_url at 0x7f3a3c726b00>
2022-10-29 04:19:36,269 botocore.endpoint [DEBUG] Setting s3 timeout as (60, 60)
2022-10-29 04:19:36,270 botocore.loaders [DEBUG] Loading JSON file: /usr/local/lib/python3.7/site-packages/botocore/data/_retry.json
2022-10-29 04:19:36,271 botocore.client [DEBUG] Registering retry handlers for service: s3
2022-10-29 04:19:36,272 boto3.resources.factory [DEBUG] Loading s3:s3
2022-10-29 04:19:36,274 botocore.hooks [DEBUG] Event choose-service-name: calling handler <function handle_service_name_alias at 0x7f3a3c715560>
2022-10-29 04:19:36,275 botocore.hooks [DEBUG] Event creating-client-class.s3: calling handler <function add_generate_presigned_post at 0x7f3a3c726d40>
2022-10-29 04:19:36,276 botocore.hooks [DEBUG] Event creating-client-class.s3: calling handler <function lazy_call.<locals>._handler at 0x7f3a428d8170>
2022-10-29 04:19:36,276 botocore.hooks [DEBUG] Event creating-client-class.s3: calling handler <function add_generate_presigned_url at 0x7f3a3c726b00>
2022-10-29 04:19:36,278 botocore.endpoint [DEBUG] Setting s3 timeout as (60, 60)
2022-10-29 04:19:36,279 botocore.client [DEBUG] Registering retry handlers for service: s3
2022-10-29 04:19:36,280 boto3.resources.factory [DEBUG] Loading s3:Bucket
2022-10-29 04:19:36,280 boto3.resources.model [DEBUG] Renaming Bucket attribute name
2022-10-29 04:19:36,282 botocore.hooks [DEBUG] Event creating-resource-class.s3.Bucket: calling handler <function lazy_call.<locals>._handler at 0x7f3a3c44da70>
2022-10-29 04:19:36,299 botocore.loaders [DEBUG] Loading JSON file: /usr/local/lib/python3.7/site-packages/botocore/data/s3/2006-03-01/paginators-1.json
2022-10-29 04:19:36,299 boto3.resources.collection [DEBUG] Calling paginated s3:list_objects with {'Bucket': 'my.botocore.test.bucket.name', 'Prefix': 'myfolder'}
2022-10-29 04:19:36,300 botocore.hooks [DEBUG] Event before-parameter-build.s3.ListObjects: calling handler <function set_list_objects_encoding_type_url at 0x7f3a3c4d2f80>
2022-10-29 04:19:36,300 botocore.hooks [DEBUG] Event before-parameter-build.s3.ListObjects: calling handler <function validate_bucket_name at 0x7f3a3c4cccb0>
2022-10-29 04:19:36,300 botocore.hooks [DEBUG] Event before-parameter-build.s3.ListObjects: calling handler <bound method S3RegionRedirector.redirect_from_cache of <botocore.utils.S3RegionRedirector object at 0x7f3a3b1bfbd0>>
2022-10-29 04:19:36,300 botocore.hooks [DEBUG] Event before-parameter-build.s3.ListObjects: calling handler <bound method S3ArnParamHandler.handle_arn of <botocore.utils.S3ArnParamHandler object at 0x7f3a3b20c350>>
2022-10-29 04:19:36,300 botocore.hooks [DEBUG] Event before-parameter-build.s3.ListObjects: calling handler <function generate_idempotent_uuid at 0x7f3a3c4ccb00>
2022-10-29 04:19:36,301 botocore.hooks [DEBUG] Event before-call.s3.ListObjects: calling handler <function add_expect_header at 0x7f3a3c4d2050>
2022-10-29 04:19:36,301 botocore.hooks [DEBUG] Event before-call.s3.ListObjects: calling handler <bound method S3RegionRedirector.set_request_url of <botocore.utils.S3RegionRedirector object at 0x7f3a3b1bfbd0>>
2022-10-29 04:19:36,301 botocore.hooks [DEBUG] Event before-call.s3.ListObjects: calling handler <function add_recursion_detection_header at 0x7f3a3c4c88c0>
2022-10-29 04:19:36,301 botocore.hooks [DEBUG] Event before-call.s3.ListObjects: calling handler <function inject_api_version_header_if_needed at 0x7f3a3c4d43b0>
2022-10-29 04:19:36,302 botocore.endpoint [DEBUG] Making request for OperationModel(name=ListObjects) with params: {'url_path': '/my.botocore.test.bucket.name', 'query_string': {'prefix': 'myfolder', 'encoding-type': 'url'}, 'method': 'GET', 'headers': {'User-Agent': 'Boto3/1.25.4 Python/3.7.10 Linux/4.14.154-128.181.amzn2.x86_64 Botocore/1.27.96 Resource'}, 'body': b'', 'url': 'https://s3-fips.us-gov-west-1.amazonaws.com/my.botocore.test.bucket.name?prefix=myfolder&encoding-type=url', 'context': {'client_region': 'us-gov-west-1', 'client_config': <botocore.config.Config object at 0x7f3a3b988dd0>, 'has_streaming_input': False, 'auth_type': None, 'encoding_type_auto_set': True, 'signing': {'bucket': 'my.botocore.test.bucket.name'}}}
2022-10-29 04:19:36,302 botocore.hooks [DEBUG] Event request-created.s3.ListObjects: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x7f3a3b988d90>>
2022-10-29 04:19:36,302 botocore.hooks [DEBUG] Event choose-signer.s3.ListObjects: calling handler <bound method S3EndpointSetter.set_signer of <botocore.utils.S3EndpointSetter object at 0x7f3a419fc310>>
2022-10-29 04:19:36,302 botocore.hooks [DEBUG] Event choose-signer.s3.ListObjects: calling handler <bound method ClientCreator._default_s3_presign_to_sigv2 of <botocore.client.ClientCreator object at 0x7f3a3c01b750>>
2022-10-29 04:19:36,302 botocore.hooks [DEBUG] Event choose-signer.s3.ListObjects: calling handler <function set_operation_specific_signer at 0x7f3a3c4cc9e0>
2022-10-29 04:19:36,303 botocore.hooks [DEBUG] Event before-sign.s3.ListObjects: calling handler <bound method S3EndpointSetter.set_endpoint of <botocore.utils.S3EndpointSetter object at 0x7f3a419fc310>>
2022-10-29 04:19:36,303 botocore.utils [DEBUG] Defaulting to S3 virtual host style addressing with path style addressing fallback.
2022-10-29 04:19:36,303 botocore.utils [DEBUG] Checking for DNS compatible bucket for: https://s3-fips.us-gov-west-1.amazonaws.com/my.botocore.test.bucket.name?prefix=myfolder&encoding-type=url
2022-10-29 04:19:36,303 botocore.utils [DEBUG] Not changing URI, bucket is not DNS compatible: my.botocore.test.bucket.name
2022-10-29 04:19:36,303 botocore.auth [DEBUG] Calculating signature using v4 auth.
2022-10-29 04:19:36,304 botocore.auth [DEBUG] CanonicalRequest:
GET
/my.botocore.test.bucket.name
encoding-type=url&prefix=myfolder
host:s3-fips.us-gov-west-1.amazonaws.com
x-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date:20221029T041936Z

host;x-amz-content-sha256;x-amz-date;x-amz-security-token
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
2022-10-29 04:19:36,304 botocore.auth [DEBUG] StringToSign:
AWS4-HMAC-SHA256
20221029T041936Z
20221029/us-gov-west-1/s3/aws4_request
2b8084e13337713cbbe2b5b823ebdf5157c56dade51edca48da4838149c4d5b1
2022-10-29 04:19:36,304 botocore.auth [DEBUG] Signature:
9f3c99f9ea8f32140ec19d1da260d28409fffbf9cc869bae410d54119fc8c7b5
2022-10-29 04:19:36,304 botocore.hooks [DEBUG] Event request-created.s3.ListObjects: calling handler <function add_retry_headers at 0x7f3a3c4d4a70>
2022-10-29 04:19:36,304 botocore.endpoint [DEBUG] Sending http request: <AWSPreparedRequest stream_output=False, method=GET, url=https://s3-fips.us-gov-west-1.amazonaws.com/my.botocore.test.bucket.name?prefix=myfolder&encoding-type=url, headers={'User-Agent': b'Boto3/1.25.4 Python/3.7.10 Linux/4.14.154-128.181.amzn2.x86_64 Botocore/1.27.96 Resource', 'X-Amz-Date': b'20221029T041936Z', 'X-Amz-Security-Token': b'xDovEp5wJ/+riOrLq2Vjc=', 'X-Amz-Content-SHA256': b'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855', 'Authorization': b'AWS4-HMAC-SHA256 Credential=AFI/20221029/us-gov-west-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date;x-amz-security-token, Signature=9f3c99f9ea8f32140ec19d1da260d28409fffbf9cc869bae410d54119fc8c7b5', 'amz-sdk-invocation-id': b'c1795726-339a-4ea9-bb43-bdb576f1d66c', 'amz-sdk-request': b'attempt=1'}>
2022-10-29 04:19:36,305 botocore.httpsession [DEBUG] Certificate path: /usr/local/lib/python3.7/site-packages/certifi/cacert.pem
2022-10-29 04:19:36,305 urllib3.connectionpool [DEBUG] Starting new HTTPS connection (1): s3-fips.us-gov-west-1.amazonaws.com:443
2022-10-29 04:19:36,364 urllib3.connectionpool [DEBUG] https://s3-fips.us-gov-west-1.amazonaws.com:443 "GET /my.botocore.test.bucket.name?prefix=myfolder&encoding-type=url HTTP/1.1" 200 None
2022-10-29 04:19:36,364 botocore.parsers [DEBUG] Response headers: {'x-amz-id-2': 'yAzWVDc+64S8=', 'x-amz-request-id': '46FZ4YGD7NYJCGWM', 'Date': 'Sat, 29 Oct 2022 04:19:37 GMT', 'x-amz-bucket-region': 'us-gov-west-1', 'Content-Type': 'application/xml', 'Transfer-Encoding': 'chunked', 'Server': 'AmazonS3'}
2022-10-29 04:19:36,365 botocore.parsers [DEBUG] Response body:
```

### Current Behavior

botocore 1.28.4
```
2022-10-29 04:18:07,855 botocore.hooks [DEBUG] Changing event name from creating-client-class.iot-data to creating-client-class.iot-data-plane
2022-10-29 04:18:07,857 botocore.hooks [DEBUG] Changing event name from before-call.apigateway to before-call.api-gateway
2022-10-29 04:18:07,857 botocore.hooks [DEBUG] Changing event name from request-created.machinelearning.Predict to request-created.machine-learning.Predict
2022-10-29 04:18:07,859 botocore.hooks [DEBUG] Changing event name from before-parameter-build.autoscaling.CreateLaunchConfiguration to before-parameter-build.auto-scaling.CreateLaunchConfiguration
2022-10-29 04:18:07,859 botocore.hooks [DEBUG] Changing event name from before-parameter-build.route53 to before-parameter-build.route-53
2022-10-29 04:18:07,860 botocore.hooks [DEBUG] Changing event name from request-created.cloudsearchdomain.Search to request-created.cloudsearch-domain.Search
2022-10-29 04:18:07,860 botocore.hooks [DEBUG] Changing event name from docs.*.autoscaling.CreateLaunchConfiguration.complete-section to docs.*.auto-scaling.CreateLaunchConfiguration.complete-section
2022-10-29 04:18:07,863 botocore.hooks [DEBUG] Changing event name from before-parameter-build.logs.CreateExportTask to before-parameter-build.cloudwatch-logs.CreateExportTask
2022-10-29 04:18:07,863 botocore.hooks [DEBUG] Changing event name from docs.*.logs.CreateExportTask.complete-section to docs.*.cloudwatch-logs.CreateExportTask.complete-section
2022-10-29 04:18:07,863 botocore.hooks [DEBUG] Changing event name from before-parameter-build.cloudsearchdomain.Search to before-parameter-build.cloudsearch-domain.Search
2022-10-29 04:18:07,863 botocore.hooks [DEBUG] Changing event name from docs.*.cloudsearchdomain.Search.complete-section to docs.*.cloudsearch-domain.Search.complete-section
2022-10-29 04:18:07,877 botocore.loaders [DEBUG] Loading JSON file: /usr/local/lib/python3.7/site-packages/boto3/data/s3/2006-03-01/resources-1.json
2022-10-29 04:18:07,883 botocore.utils [DEBUG] IMDS ENDPOINT: http://169.254.169.254/
2022-10-29 04:18:07,886 botocore.credentials [DEBUG] Looking for credentials via: env
2022-10-29 04:18:07,886 botocore.credentials [DEBUG] Looking for credentials via: assume-role
2022-10-29 04:18:07,886 botocore.credentials [DEBUG] Looking for credentials via: assume-role-with-web-identity
2022-10-29 04:18:07,887 botocore.credentials [DEBUG] Looking for credentials via: sso
2022-10-29 04:18:07,887 botocore.credentials [DEBUG] Looking for credentials via: shared-credentials-file
2022-10-29 04:18:07,887 botocore.credentials [DEBUG] Looking for credentials via: custom-process
2022-10-29 04:18:07,887 botocore.credentials [DEBUG] Looking for credentials via: config-file
2022-10-29 04:18:07,887 botocore.credentials [DEBUG] Looking for credentials via: ec2-credentials-file
2022-10-29 04:18:07,887 botocore.credentials [DEBUG] Looking for credentials via: boto-config
2022-10-29 04:18:07,887 botocore.credentials [DEBUG] Looking for credentials via: container-role
2022-10-29 04:18:07,887 botocore.credentials [DEBUG] Looking for credentials via: iam-role
2022-10-29 04:18:07,888 urllib3.connectionpool [DEBUG] Starting new HTTP connection (1): 169.254.169.254:80
2022-10-29 04:18:07,892 urllib3.connectionpool [DEBUG] http://169.254.169.254:80 "PUT /latest/api/token HTTP/1.1" 200 56
2022-10-29 04:18:07,893 urllib3.connectionpool [DEBUG] Resetting dropped connection: 169.254.169.254
2022-10-29 04:18:07,894 urllib3.connectionpool [DEBUG] http://169.254.169.254:80 "GET /latest/meta-data/iam/security-credentials/ HTTP/1.1" 200 21
2022-10-29 04:18:07,895 urllib3.connectionpool [DEBUG] Resetting dropped connection: 169.254.169.254
2022-10-29 04:18:07,896 urllib3.connectionpool [DEBUG] http://169.254.169.254:80 "GET /latest/meta-data/iam/security-credentials/us-gov-west-1 HTTP/1.1" 200 1054
2022-10-29 04:18:07,899 botocore.credentials [INFO] Found credentials from IAM Role: us-gov-west-1
2022-10-29 04:18:07,900 botocore.loaders [DEBUG] Loading JSON file: /usr/local/lib/python3.7/site-packages/botocore/data/endpoints.json
2022-10-29 04:18:07,920 botocore.loaders [DEBUG] Loading JSON file: /usr/local/lib/python3.7/site-packages/botocore/data/sdk-default-configuration.json
2022-10-29 04:18:07,921 botocore.hooks [DEBUG] Event choose-service-name: calling handler <function handle_service_name_alias at 0x7f6a3a621290>
2022-10-29 04:18:07,934 botocore.loaders [DEBUG] Loading JSON file: /usr/local/lib/python3.7/site-packages/botocore/data/s3/2006-03-01/service-2.json
2022-10-29 04:18:07,961 botocore.loaders [DEBUG] Loading JSON file: /usr/local/lib/python3.7/site-packages/botocore/data/s3/2006-03-01/endpoint-rule-set-1.json.gz
2022-10-29 04:18:07,967 botocore.loaders [DEBUG] Loading JSON file: /usr/local/lib/python3.7/site-packages/botocore/data/partitions.json
2022-10-29 04:18:07,970 botocore.hooks [DEBUG] Event creating-client-class.s3: calling handler <function add_generate_presigned_post at 0x7f6a3a6ad7a0>
2022-10-29 04:18:07,970 botocore.hooks [DEBUG] Event creating-client-class.s3: calling handler <function lazy_call.<locals>._handler at 0x7f6a40800170>
2022-10-29 04:18:07,986 botocore.hooks [DEBUG] Event creating-client-class.s3: calling handler <function add_generate_presigned_url at 0x7f6a3a6ad560>
2022-10-29 04:18:07,988 botocore.endpoint [DEBUG] Setting s3 timeout as (60, 60)
2022-10-29 04:18:07,991 botocore.loaders [DEBUG] Loading JSON file: /usr/local/lib/python3.7/site-packages/botocore/data/_retry.json
2022-10-29 04:18:07,991 botocore.client [DEBUG] Registering retry handlers for service: s3
2022-10-29 04:18:07,992 botocore.utils [DEBUG] Registering S3 region redirector handler
2022-10-29 04:18:07,993 boto3.resources.factory [DEBUG] Loading s3:s3
2022-10-29 04:18:07,994 botocore.hooks [DEBUG] Event choose-service-name: calling handler <function handle_service_name_alias at 0x7f6a3a621290>
2022-10-29 04:18:07,995 botocore.hooks [DEBUG] Event creating-client-class.s3: calling handler <function add_generate_presigned_post at 0x7f6a3a6ad7a0>
2022-10-29 04:18:07,995 botocore.hooks [DEBUG] Event creating-client-class.s3: calling handler <function lazy_call.<locals>._handler at 0x7f6a40800170>
2022-10-29 04:18:07,995 botocore.hooks [DEBUG] Event creating-client-class.s3: calling handler <function add_generate_presigned_url at 0x7f6a3a6ad560>
2022-10-29 04:18:07,997 botocore.endpoint [DEBUG] Setting s3 timeout as (60, 60)
2022-10-29 04:18:07,999 botocore.client [DEBUG] Registering retry handlers for service: s3
2022-10-29 04:18:07,999 botocore.utils [DEBUG] Registering S3 region redirector handler
2022-10-29 04:18:08,000 boto3.resources.factory [DEBUG] Loading s3:Bucket
2022-10-29 04:18:08,000 boto3.resources.model [DEBUG] Renaming Bucket attribute name
2022-10-29 04:18:08,001 botocore.hooks [DEBUG] Event creating-resource-class.s3.Bucket: calling handler <function lazy_call.<locals>._handler at 0x7f6a3a352dd0>
2022-10-29 04:18:08,012 botocore.loaders [DEBUG] Loading JSON file: /usr/local/lib/python3.7/site-packages/botocore/data/s3/2006-03-01/paginators-1.json
2022-10-29 04:18:08,013 boto3.resources.collection [DEBUG] Calling paginated s3:list_objects with {'Bucket': 'my.botocore.test.bucket.name', 'Prefix': 'myfolder'}
2022-10-29 04:18:08,013 botocore.hooks [DEBUG] Event before-endpoint-resolution.s3: calling handler <function customize_endpoint_resolver_builtins at 0x7f6a3a3e2dd0>
2022-10-29 04:18:08,013 botocore.hooks [DEBUG] Event before-endpoint-resolution.s3: calling handler <bound method S3RegionRedirectorv2.redirect_from_cache of <botocore.utils.S3RegionRedirectorv2 object at 0x7f6a38fd0fd0>>
2022-10-29 04:18:08,014 botocore.regions [DEBUG] Calling endpoint provider with parameters: {'Bucket': 'my.botocore.test.bucket.name', 'Region': 'us-gov-west-1', 'UseFIPS': True, 'UseDualStack': False, 'ForcePathStyle': False, 'Accelerate': False, 'UseGlobalEndpoint': False, 'DisableMultiRegionAccessPoints': False, 'UseArnRegion': True}
Traceback (most recent call last):
  File "test.py", line 22, in <module>
    download()
  File "test.py", line 15, in download
    for obj in objects:
  File "/usr/local/lib/python3.7/site-packages/boto3/resources/collection.py", line 81, in __iter__
    for page in self.pages():
  File "/usr/local/lib/python3.7/site-packages/boto3/resources/collection.py", line 171, in pages
    for page in pages:
  File "/usr/local/lib/python3.7/site-packages/botocore/paginate.py", line 269, in __iter__
    response = self._make_request(current_kwargs)
  File "/usr/local/lib/python3.7/site-packages/botocore/paginate.py", line 357, in _make_request
    return self._method(**current_kwargs)
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 507, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 900, in _make_api_call
    operation_model, api_params, request_context
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 1045, in _resolve_endpoint_ruleset
    request_context=request_context,
  File "/usr/local/lib/python3.7/site-packages/botocore/regions.py", line 502, in construct_endpoint
    **provider_params
  File "/usr/local/lib/python3.7/site-packages/botocore/endpoint_provider.py", line 730, in resolve_endpoint
    endpoint = self.ruleset.evaluate(input_parameters)
  File "/usr/local/lib/python3.7/site-packages/botocore/endpoint_provider.py", line 710, in evaluate
    evaluation = rule.evaluate(input_parameters.copy(), self.rule_lib)
  File "/usr/local/lib/python3.7/site-packages/botocore/endpoint_provider.py", line 561, in evaluate
    rule_result = rule.evaluate(scope_vars.copy(), rule_lib)
  File "/usr/local/lib/python3.7/site-packages/botocore/endpoint_provider.py", line 561, in evaluate
    rule_result = rule.evaluate(scope_vars.copy(), rule_lib)
  File "/usr/local/lib/python3.7/site-packages/botocore/endpoint_provider.py", line 561, in evaluate
    rule_result = rule.evaluate(scope_vars.copy(), rule_lib)
  [Previous line repeated 8 more times]
  File "/usr/local/lib/python3.7/site-packages/botocore/endpoint_provider.py", line 537, in evaluate
    raise EndpointResolutionError(msg=error)
botocore.exceptions.EndpointResolutionError: Path-style addressing cannot be used with FIPS
```

### Reproduction Steps

Create a test bucket with periods in the name.

Create a random folder and put a few random files

update the bucket name and file prefix. 

```python
import os
import boto3
import logging
boto3.set_stream_logger('')

os.environ["AWS_USE_FIPS_ENDPOINT"] = "true"
BUCKET_NAME = "my.botocore.test.bucket.name"
FILE_PREFIX = "myfolder"

def download():
    s3_resource = boto3.resource("s3", region_name="us-gov-west-1")
    s3 = boto3.client("s3", region_name="us-gov-west-1")
    obj_bucket = s3_resource.Bucket(BUCKET_NAME)
    objects = obj_bucket.objects.filter(Prefix=FILE_PREFIX)
    for obj in objects:
        print(obj)
        path, filename = os.path.split(obj.key)
        s3.download_file(BUCKET_NAME, obj.key, filename)


if __name__ == "__main__":
    download()
```

### Additional Information/Context

It looks like this error only happens in govcloud. In commercial, the FIPS endpoint only supports virtual-style URLs but in govcloud, path-style is supported. 

You can see this because in commercial there are no addresses for the FIPS s3 endpoint which indicates that it only supports virtual as path-based would need a valid endpoint that does not exist.  However, in govcloud the FIPS endpoint does exist so it can support path-based queries.  

(removed unneeded additional data from the query)

 dig s3-fips.us-east-1.amazonaws.com
```
;; QUESTION SECTION:
;s3-fips.us-east-1.amazonaws.com. IN	A

;; AUTHORITY SECTION:
s3-fips.us-east-1.amazonaws.com. 300 IN	SOA	ns-550.awsdns-04.net. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 300

;; SERVER: 1.1.1.1#53(1.1.1.1)
```

dig s3-fips.us-gov-east-1.amazonaws.com
```
;; QUESTION SECTION:
;s3-fips.us-gov-east-1.amazonaws.com. IN	A

;; ANSWER SECTION:
s3-fips.us-gov-east-1.amazonaws.com. 5 IN A	108.175.52.52

;; SERVER: 1.1.1.1#53(1.1.1.1)
```

### SDK version used

1.28.4

### Environment details (OS name and version, etc.)

amazon linux 2 AMI with latest updates.

**Comment by jonemo** [comment]
This has been fixed in botocore version 1.29.58. The reproduction script above now results in a request to 

```
https://s3-fips.us-gov-west-1.amazonaws.com/my.botocore.test.bucket.name?prefix=myfolder&encoding-type=url
```
