### ISSUE TITLE
cgi dependency is deprecated in Python 3.11, slated for removal in Python 3.13

### ISSUE THREAD

**Issue by bmw** [boto/botocore#2803]
### Describe the bug

Python 3.11 deprecated the cgi module which botocore uses [here](https://github.com/boto/botocore/blob/3d3f40ca854b90e5bb8eae88686bc3c6dcb85839/botocore/utils.py#L15). See https://github.com/python/cpython/issues/91217.

### Expected Behavior

botocore doesn't use deprecated code

### Current Behavior

botocore uses deprecated code resulting in deprecation warnings when run on Python 3.11

### Reproduction Steps

```
$ python -Werror -c 'import botocore.session'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/private/var/folders/tr/_jqrlt554c107b5lcxl3td_40000gn/T/tmp.HC2Evak2iS/venv/lib/python3.11/site-packages/botocore/session.py", line 26, in <module>
    import botocore.client
  File "/private/var/folders/tr/_jqrlt554c107b5lcxl3td_40000gn/T/tmp.HC2Evak2iS/venv/lib/python3.11/site-packages/botocore/client.py", line 17, in <module>
    from botocore import waiter, xform_name
  File "/private/var/folders/tr/_jqrlt554c107b5lcxl3td_40000gn/T/tmp.HC2Evak2iS/venv/lib/python3.11/site-packages/botocore/waiter.py", line 18, in <module>
    from botocore.docs.docstring import WaiterDocstring
  File "/private/var/folders/tr/_jqrlt554c107b5lcxl3td_40000gn/T/tmp.HC2Evak2iS/venv/lib/python3.11/site-packages/botocore/docs/__init__.py", line 15, in <module>
    from botocore.docs.service import ServiceDocumenter
  File "/private/var/folders/tr/_jqrlt554c107b5lcxl3td_40000gn/T/tmp.HC2Evak2iS/venv/lib/python3.11/site-packages/botocore/docs/service.py", line 14, in <module>
    from botocore.docs.client import ClientDocumenter, ClientExceptionsDocumenter
  File "/private/var/folders/tr/_jqrlt554c107b5lcxl3td_40000gn/T/tmp.HC2Evak2iS/venv/lib/python3.11/site-packages/botocore/docs/client.py", line 14, in <module>
    from botocore.docs.example import ResponseExampleDocumenter
  File "/private/var/folders/tr/_jqrlt554c107b5lcxl3td_40000gn/T/tmp.HC2Evak2iS/venv/lib/python3.11/site-packages/botocore/docs/example.py", line 13, in <module>
    from botocore.docs.shape import ShapeDocumenter
  File "/private/var/folders/tr/_jqrlt554c107b5lcxl3td_40000gn/T/tmp.HC2Evak2iS/venv/lib/python3.11/site-packages/botocore/docs/shape.py", line 19, in <module>
    from botocore.utils import is_json_value_header
  File "/private/var/folders/tr/_jqrlt554c107b5lcxl3td_40000gn/T/tmp.HC2Evak2iS/venv/lib/python3.11/site-packages/botocore/utils.py", line 15, in <module>
    import cgi
  File "/Users/bmw/.pyenv/versions/3.11.0rc2/lib/python3.11/cgi.py", line 57, in <module>
    warnings._deprecated(__name__, remove=(3,13))
  File "/Users/bmw/.pyenv/versions/3.11.0rc2/lib/python3.11/warnings.py", line 514, in _deprecated
    warn(msg, DeprecationWarning, stacklevel=3)
DeprecationWarning: 'cgi' is deprecated and slated for removal in Python 3.13
```

### SDK version used

1.28.5

### Environment details (OS name and version, etc.)

macOS and linux

**Comment by tim-finnigan** [comment]
Thanks for bringing this to our attention. The deprecation warning you referenced notes: 
>`DeprecationWarning: 'cgi' is deprecated and slated for removal in Python 3.13`

And here's more context in the [Python documentation](https://docs.python.org/3/library/cgi.html):
> Deprecated since version 3.11, will be removed in version 3.13: This function, like the rest of the [cgi](https://docs.python.org/3/library/cgi.html#module-cgi) module, is deprecated. It can be replaced with the functionality in the [email](https://docs.python.org/3/library/email.html#module-email) package, which implements the same MIME RFCs.

It looks like only the cgi command used is `parse_header()` [here](https://github.com/boto/botocore/blob/a210b26b4d71f752a91247389e735f314f993bf7/botocore/utils.py#L3013). So it shouldn't be too difficult to implement an alternative before Python 3.13.

**Comment by wimglenn** [comment]
@tim-finnigan  https://github.com/boto/botocore/pull/2794

**Comment by wimglenn** [comment]
@bmw  This can be closed.
