### ISSUE TITLE
"EOF occurred in violation of protocol" occurred when calling s3:PutObject with "--checksum-algorithm" in Python Docker image in Amazon Linux 2

### ISSUE THREAD

**Issue by lcy0321** [boto/botocore#2843]
### Describe the bug

Error occurred when calling `s3:PutObject` with "--checksum-algorithm" for a 100 Kib file in the Python 3.11 image in the Amazon Linux 2 EC2 instance.

### Expected Behavior

The file can be uploaded to the specified S3 bucket with checksum-algorithm enabled.

### Current Behavior

Receive the following error, and the file fails to be uploaded.
```log
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 396, in _make_request
    conn.request_chunked(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 275, in request_chunked
    self.send(to_send)
  File "/usr/local/lib/python3.11/site-packages/botocore/awsrequest.py", line 218, in send
    return super().send(str)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/http/client.py", line 998, in send
    self.sock.sendall(data)
  File "/usr/local/lib/python3.11/ssl.py", line 1241, in sendall
    v = self.send(byte_view[count:])
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/ssl.py", line 1210, in send
    return self._sslobj.write(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2393)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/botocore/httpsession.py", line 455, in send
    urllib_response = conn.urlopen(
                      ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/retry.py", line 525, in increment
    raise six.reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 396, in _make_request
    conn.request_chunked(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 275, in request_chunked
    self.send(to_send)
  File "/usr/local/lib/python3.11/site-packages/botocore/awsrequest.py", line 218, in send
    return super().send(str)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/http/client.py", line 998, in send
    self.sock.sendall(data)
  File "/usr/local/lib/python3.11/ssl.py", line 1241, in sendall
    v = self.send(byte_view[count:])
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/ssl.py", line 1210, in send
    return self._sslobj.write(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:2393)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/botocore/endpoint.py", line 281, in _do_get_response
    http_response = self._send(request)
                    ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/botocore/endpoint.py", line 377, in _send
    return self.http_session.send(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/botocore/httpsession.py", line 482, in send
    raise SSLError(endpoint_url=request.url, error=e)
botocore.exceptions.SSLError: SSL validation failed for https://test-bucket-name.s3.amazonaws.com/100k.txt EOF occurred in violation of protocol (_ssl.c:2393)
```

### Reproduction Steps

1. Launch an Amazon Linux 2 EC2 attached with a role that can put-object to S3 buckets

    ```text
    $ uname -r
    5.10.157-139.675.amzn2.x86_64
    ```

2. Install Docker with `sudo yum install docker`

   ```text
    $ docker --version
    Docker version 20.10.17, build 100c701
   ```

3. Launch the "python:3.11" image.

4. Install `awscli` with `sudo pip install awscli`

    ```text
    $ aws --version
    aws-cli/1.27.42 Python/3.11.1 Linux/5.10.157-139.675.amzn2.x86_64 botocore/1.29.42
    ```

5. Create a 100 KiB file with `fallocate -l 100K 100k.txt`
6. Upload the file to a S3 bucket with checksum-algorithm enabled.

    ```text
    aws --debug s3api put-object --bucket test-bucket-name --key 100k.txt --body ./100k.txt --checksum-algorithm SHA256
    ```

### Additional Information/Context

- The same error occurs when using boto3 in the same environment.
- This error does not occur outside the docker image.
- This error does not occur in the same Docker image in Ubuntu 20.04.5 LTS
- This error does not occur when the parameter `ChecksumAlgorithm` is not given.
- This error does not occur when the file is only 1 KiB.

### SDK version used

aws-cli/1.27.42 Python/3.11.1 Linux/5.10.157-139.675.amzn2.x86_64 botocore/1.29.42

### Environment details (OS name and version, etc.)

5.10.157-139.675.amzn2.x86_64

**Comment by tim-finnigan** [comment]
Hi @lcy0321 thanks for reaching out. There is an AWS CLI troubleshooting guide for SSL certificate errors that I recommend reviewing: https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-troubleshooting.html#tshoot-certificate-verify-failed

Have you also tried [installing the AWS CLI v2](https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html) to test this? And which boto3 version were you using when you ran into this issue?

There was a related issue here recently (https://github.com/boto/boto3/issues/3359) in which the author was also using the SHA256 Checksum Algorithm. This user later commented here describing what was causing the issue: https://github.com/boto/boto3/issues/3359#issuecomment-1200006400. I'm not sure if that would explain the issue you're seeing, but if the error does not occur on small files as you mentioned then it could relate to multipart uploads.

**Comment by tim-finnigan** [comment]
At what file size do you observe the issue occurring? Can you confirm that the issue still occurs with v2 of the AWS CLI?
