### ISSUE TITLE
AlgorithmSpecification unknown on valid python code

### ISSUE THREAD

**Issue by desinurch** [boto/botocore#3011]
### Describe the bug

Following the code in https://docs.aws.amazon.com/sagemaker/latest/dg/train-remote-decorator-invocation.html

```
from sagemaker.remote_function import remote
import numpy as np

@remote(instance_type="ml.m5.large")
def matrix_multiply(a, b):
    return np.matmul(a, b)
    
a = np.array([[1, 0],
             [0, 1]])
b = np.array([1, 2])

assert (matrix_multiply(a, b) == np.array([1,2])).all()
```

### Expected Behavior

Code running

### Current Behavior

```
Traceback (most recent call last):
  File "remote-decorator.py", line 22, in <module>
    matrix_multiply(a,b)
  File "/opt/homebrew/anaconda3/envs/sm/lib/python3.8/site-packages/sagemaker/remote_function/client.py", line 312, in wrapper
    job = _Job.start(job_settings, func, args, kwargs)
  File "/opt/homebrew/anaconda3/envs/sm/lib/python3.8/site-packages/sagemaker/remote_function/job.py", line 768, in start
    job_settings.sagemaker_session.sagemaker_client.create_training_job(**extended_request)
  File "/opt/homebrew/anaconda3/envs/sm/lib/python3.8/site-packages/botocore/client.py", line 535, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/homebrew/anaconda3/envs/sm/lib/python3.8/site-packages/botocore/client.py", line 936, in _make_api_call
    request_dict = self._convert_to_request_dict(
  File "/opt/homebrew/anaconda3/envs/sm/lib/python3.8/site-packages/botocore/client.py", line 1007, in _convert_to_request_dict
    request_dict = self._serializer.serialize_to_request(
  File "/opt/homebrew/anaconda3/envs/sm/lib/python3.8/site-packages/botocore/validate.py", line 381, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Unknown parameter in AlgorithmSpecification: "ContainerEntrypoint", must be one of: TrainingImage, TrainingImageConfig, AlgorithmName, TrainingInputMode, MetricDefinitions, EnableSageMakerMetricsTimeSeries
Unknown parameter in AlgorithmSpecification: "ContainerArguments", must be one of: TrainingImage, TrainingImageConfig, AlgorithmName, TrainingInputMode, MetricDefinitions, EnableSageMakerMetricsTimeSeries
```

### Reproduction Steps

Install new conda environment
Install sagemaker by
```
pip install sagemaker
```
Result:
```
Installing collected packages: pytz, zipp, urllib3, tzdata, tblib, smdebug-rulesconfig, six, rpds-py, PyYAML, protobuf, ppft, pox, platformdirs, pkgutil-resolve-name, packaging, numpy, jmespath, dill, contextlib2, cloudpickle, attrs, schema, referencing, python-dateutil, multiprocess, importlib-resources, importlib-metadata, google-pasta, pathos, pandas, jsonschema-specifications, botocore, s3transfer, jsonschema, boto3, sagemaker
Successfully installed PyYAML-6.0.1 attrs-23.1.0 boto3-1.28.37 botocore-1.31.37 cloudpickle-2.2.1 contextlib2-21.6.0 dill-0.3.7 google-pasta-0.2.0 importlib-metadata-6.8.0 importlib-resources-6.0.1 jmespath-1.0.1 jsonschema-4.19.0 jsonschema-specifications-2023.7.1 multiprocess-0.70.15 numpy-1.24.4 packaging-23.1 pandas-2.0.3 pathos-0.3.1 pkgutil-resolve-name-1.3.10 platformdirs-3.10.0 pox-0.3.3 ppft-1.7.6.7 protobuf-4.24.2 python-dateutil-2.8.2 pytz-2023.3 referencing-0.30.2 rpds-py-0.10.0 s3transfer-0.6.2 sagemaker-2.182.0 schema-0.7.5 six-1.16.0 smdebug-rulesconfig-1.0.1 tblib-1.7.0 tzdata-2023.3 urllib3-1.26.16 zipp-3.16.2
```
Run the above code

### SDK version used

latest

### Environment details (OS name and version, etc.)

MacOS, Anaconda

**Comment by RyanFitzSimmonsAK** [comment]
Hi @desinurch, thanks for reaching out.  Can you check on what version of botocore and boto3 you're currently using inside your Conda environment?  You can get the versions with `boto3.__version__` and `botocore.__version__` respectively.  If those versions look up to date, then please provide debug logs by adding `boto3.set_stream_logger('')` to the top of the script, and redacting any sensitive information.  Thanks!

**Comment by desinurch** [comment]
Hi @RyanFitzSimmonsAK thanks for investigating!

Here are the versions:
```
$ python                                                                                                                               (sm) 
Python 3.8.17 (default, Jul  5 2023, 15:35:58) 
[Clang 14.0.6 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import boto3
>>> boto3.__version__
'1.28.37'
>>> import botocore
>>> botocore.__version__
'1.31.37'
```

Here is the log:
[remote-decorator.log](https://github.com/boto/botocore/files/12484780/remote-decorator.log)

**Comment by RyanFitzSimmonsAK** [comment]
Hi @desinurch, thanks for following-up.  It looks like the Sagemaker Python SDK is loading a custom model file, rather than using the one provided by botocore.  

`DEBUG:botocore.loaders:Loading JSON file: /Users/ddd/.aws/models/sagemaker/2017-07-24/service-2.json`

The problem likely is that they have not updated their model file to include the `ContainerEntrypoint` and `ContainerArguments` parameters.  I will reach out to the service team, and update you when I know more.  Thanks!

**Comment by desinurch** [comment]
@RyanFitzSimmonsAK yes it seems the model file is cached on my local, the cause was the command:
```
aws configure add-model --service-model file://service.json
```
Then SageMaker Python SDK will prefer the cached version. Deleting this will suffice for the botocore to work, thanks a lot for finding the cause!

**Comment by RyanFitzSimmonsAK** [comment]
Glad you got it working.  Out of curiosity, were you following the Sagemaker Python SDK developer guide when you used that command?  If so, could you point me to the page where you were directed to use that command?

**Comment by desinurch** [comment]
I believe this was a leftover when I was testing other tools, e.g, SageMaker experiments, not from the SageMaker Python SDK docs. Thanks again and sorry for the inconvenience!
