### ISSUE TITLE
MPU error with some unicode characters

### ISSUE THREAD

**Issue by Pofilo** [boto/botocore#3047]
### Describe the bug

Create a MPU with key "object\u001e" but botocore fails as not being able to read the XML response from the server.

### Expected Behavior

Being able to create a MPU with an object name "object\u001e" without any errors (as the backend is able to create such a MPU).

### Current Behavior

Debug logs (with bucket renamed as `mybucket`):

```
botocore.hooks DEBUG: Event request-created.s3.CreateMultipartUpload: calling handler <function add_retry_headers at 0x7f3237d63e20>
botocore.endpoint DEBUG: Sending http request: <AWSPreparedRequest stream_output=False, method=POST, url=https://s3.eu-west-3.amazonaws.com/mybucket/object%1E?uploads, headers={'User-Agent': b'Boto3/1.28.78 md/Botocore#1.31.78 ua/2.0 os/linux#5.15.0-87-generic md/arch#x86_64 lang/python#3.10.11 md/pyimpl#CPython cfg/retry-mode#legacy Botocore/1.31.78', 'X-Amz-Date': b'20231106T132945Z', 'X-Amz-Content-SHA256': b'xx', 'Authorization': b'AWS4-HMAC-SHA256 Credential=xxx/20231106/eu-west-3/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=xxx', 'amz-sdk-invocation-id': b'xxx', 'amz-sdk-request': b'attempt=1', 'Content-Length': '0'}>
botocore.httpsession DEBUG: Certificate path: /tmp/botompu/lib/python3.10/site-packages/certifi/cacert.pem
urllib3.connectionpool DEBUG: Starting new HTTPS connection (1): s3.eu-west-3.amazonaws.com:443
urllib3.connectionpool DEBUG: https://s3.eu-west-3.amazonaws.com:443 "POST /mybucket/object%1E?uploads HTTP/1.1" 200 None
botocore.parsers DEBUG: Response headers: {'x-amz-id-2': 'xxx', 'x-amz-request-id': 'xxx', 'Date': 'Mon, 06 Nov 2023 13:29:47 GMT', 'x-amz-server-side-encryption': 'AES256', 'Transfer-Encoding': 'chunked', 'Server': 'AmazonS3'}
botocore.parsers DEBUG: Response body:
b'<?xml version="1.0" encoding="UTF-8"?>\n<InitiateMultipartUploadResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Bucket>mybucket</Bucket><Key>object&#x1e;</Key><UploadId>xxxx</UploadId></InitiateMultipartUploadResult>'
Traceback (most recent call last):
  File "/tmp/botompu/lib/python3.10/site-packages/botocore/parsers.py", line 505, in _parse_xml_string_to_dom
    parser.feed(xml_string)
xml.etree.ElementTree.ParseError: reference to invalid character number: line 2, column 112

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "example.py", line 374, in create_multipart_upload
    response = self.boto.create_multipart_upload(
  File "/tmp/botompu/lib/python3.10/site-packages/botocore/client.py", line 535, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/tmp/botompu/lib/python3.10/site-packages/botocore/client.py", line 963, in _make_api_call
    http, parsed_response = self._make_request(
  File "/tmp/botompu/lib/python3.10/site-packages/botocore/client.py", line 986, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/tmp/botompu/lib/python3.10/site-packages/botocore/endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
  File "/tmp/botompu/lib/python3.10/site-packages/botocore/endpoint.py", line 199, in _send_request
    success_response, exception = self._get_response(
  File "/tmp/botompu/lib/python3.10/site-packages/botocore/endpoint.py", line 241, in _get_response
    success_response, exception = self._do_get_response(
  File "/tmp/botompu/lib/python3.10/site-packages/botocore/endpoint.py", line 308, in _do_get_response
    parsed_response = parser.parse(
  File "/tmp/botompu/lib/python3.10/site-packages/botocore/parsers.py", line 252, in parse
    parsed = self._do_parse(response, shape)
  File "/tmp/botompu/lib/python3.10/site-packages/botocore/parsers.py", line 883, in _do_parse
    self._add_modeled_parse(response, shape, final_parsed)
  File "/tmp/botompu/lib/python3.10/site-packages/botocore/parsers.py", line 893, in _add_modeled_parse
    self._parse_payload(response, shape, member_shapes, final_parsed)
  File "/tmp/botompu/lib/python3.10/site-packages/botocore/parsers.py", line 934, in _parse_payload
    original_parsed = self._initial_body_parse(response['body'])
  File "/tmp/botompu/lib/python3.10/site-packages/botocore/parsers.py", line 1033, in _initial_body_parse
    return self._parse_xml_string_to_dom(xml_string)
  File "/tmp/botompu/lib/python3.10/site-packages/botocore/parsers.py", line 508, in _parse_xml_string_to_dom
    raise ResponseParserError(
botocore.parsers.ResponseParserError: Unable to parse response (reference to invalid character number: line 2, column 112), invalid XML received. Further retries may succeed:
b'<?xml version="1.0" encoding="UTF-8"?>\n<InitiateMultipartUploadResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Bucket>mybucket</Bucket><Key>object&#x1e;</Key><UploadId>xxxx</UploadId></InitiateMultipartUploadResult>'
```

We can see that the backend is creating the MPU successfully (200) but botocore fails to parse the XML response.

### Reproduction Steps

Code to reproduce the error (simple call to `create_multipart_upload`):
```python
bucket = "mybucket"
key = "object\u001e"  # of course "object" is working
boto = boto3.client(...)
response = boto.create_multipart_upload(
    Bucket=bucket,
    Key=key,
)
```

### SDK version used

1.31.78

### Environment details (OS name and version, etc.)

Ubuntu 20.04

**Comment by RyanFitzSimmonsAK** [comment]
Hi @Pofilo, thanks for reaching out.  `\u001e` is an ASCII control character, which are mentioned in the [S3 User Guide](https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-keys.html) as characters that might require special handling and should be avoided.  The [object metadata page](https://docs.aws.amazon.com/AmazonS3/latest/userguide/UsingMetadata.html) of the S3 User Guide also mentions that when using the API, in general, you should use US-ASCII characters.  Hope that helps, and please let me know if you have any follow-up questions.
