### ISSUE TITLE
EC2 describe-images paginator failure

### ISSUE THREAD

**Issue by sunkuamzn** [boto/botocore#3051]
### Describe the bug

EC2 describe-images paginator fails when PageSize is specified. describe-instances works fine. Did not check other paginators.

### Expected Behavior

describe-images paginator to not fail

### Current Behavior

```
>>> import boto3
>>> boto3.__version__
'1.28.82'
>>> client = boto3.client('ec2', region_name='eu-north-1')
>>> paginator = client.get_paginator('describe_images')
>>> imgs = paginator.paginate(PaginationConfig={'MaxItems': 512})              <---------- WORKS
>>> imgs = paginator.paginate(PaginationConfig={'PageSize': 512})              <---------- FAILS
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/private/tmp/venv/lib/python3.11/site-packages/botocore/client.py", line 1129, in paginate
    return Paginator.paginate(self, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/tmp/venv/lib/python3.11/site-packages/botocore/paginate.py", line 656, in paginate
    page_params = self._extract_paging_params(kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/tmp/venv/lib/python3.11/site-packages/botocore/paginate.py", line 685, in _extract_paging_params
    if limit_key_shape.type_name == 'string':
       ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'type_name'

>>> imgs = paginator.paginate(PaginationConfig={'MaxItems': 512, 'PageSize': 512})              <---------- FAILS
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/private/tmp/venv/lib/python3.11/site-packages/botocore/client.py", line 1129, in paginate
    return Paginator.paginate(self, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/tmp/venv/lib/python3.11/site-packages/botocore/paginate.py", line 656, in paginate
    page_params = self._extract_paging_params(kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/tmp/venv/lib/python3.11/site-packages/botocore/paginate.py", line 685, in _extract_paging_params
    if limit_key_shape.type_name == 'string':
       ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'type_name'
```

describe-instances paginator always works
```
>>> paginator = client.get_paginator('describe_instances')
>>> paginator = client.get_paginator('describe_instances')
>>> imgs = paginator.paginate(PaginationConfig={'MaxItems': 512, 'PageSize': 512})               <---------- WORKS
>>> imgs = paginator.paginate(PaginationConfig={'PageSize': 512})              <---------- WORKS
```

### Reproduction Steps

See Current Behavior

### SDK version used

1.28.82

### Environment details (OS name and version, etc.)

MacOS 13.5

**Comment by tim-finnigan** [comment]
Hi @sunkuamzn thanks for reaching out. I tested this on boto3 1.28.76 / botocore 1.31.76 and it seemed to work as expected: 

```python3
import boto3
import botocore
print(boto3.__version__)
print(botocore.__version__)

client = boto3.client('ec2', region_name='eu-north-1')

paginator = client.get_paginator('describe_images')

page_iterator = paginator.paginate(
    PaginationConfig={'PageSize': 512})

for page in page_iterator:
    print(page)
```

Can you try reinstalling boto3/botocore? If you're still seeing the issue please share your full debug logs (with any sensitive info redacted) by adding `boto3.set_stream_logger('')` to your script.

**Comment by sunkuamzn** [comment]
I still see the same failure. Tried on two fresh venvs with the latest boto3

```
>>> boto3.set_stream_logger('')
>>> 
>>> import boto3
>>> import botocore
>>> print(boto3.__version__)
1.29.1
>>> print(botocore.__version__)
1.32.1
>>> 
>>> client = boto3.client('ec2', region_name='eu-north-1')
2023-11-16 14:04:17,773 botocore.hooks [DEBUG] Event choose-service-name: calling handler <function handle_service_name_alias at 0x10825f420>
2023-11-16 14:04:17,795 botocore.hooks [DEBUG] Event creating-client-class.ec2: calling handler <function add_generate_presigned_url at 0x1081dcf40>
2023-11-16 14:04:17,795 botocore.configprovider [DEBUG] Looking for endpoint for ec2 via: environment_service
2023-11-16 14:04:17,795 botocore.configprovider [DEBUG] Looking for endpoint for ec2 via: environment_global
2023-11-16 14:04:17,795 botocore.configprovider [DEBUG] Looking for endpoint for ec2 via: config_service
2023-11-16 14:04:17,795 botocore.configprovider [DEBUG] Looking for endpoint for ec2 via: config_global
2023-11-16 14:04:17,796 botocore.configprovider [DEBUG] No configured endpoint found.
2023-11-16 14:04:17,797 botocore.endpoint [DEBUG] Setting ec2 timeout as (60, 60)
2023-11-16 14:04:17,798 botocore.client [DEBUG] Registering retry handlers for service: ec2
>>> 
>>> paginator = client.get_paginator('describe_images')
>>> 
>>> page_iterator = paginator.paginate(
...     PaginationConfig={'PageSize': 512})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Volumes/workplace/libfabric-ci/src/venv/lib/python3.11/site-packages/botocore/client.py", line 1132, in paginate
    return Paginator.paginate(self, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/workplace/libfabric-ci/src/venv/lib/python3.11/site-packages/botocore/paginate.py", line 656, in paginate
    page_params = self._extract_paging_params(kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/workplace/libfabric-ci/src/venv/lib/python3.11/site-packages/botocore/paginate.py", line 685, in _extract_paging_params
    if limit_key_shape.type_name == 'string':
       ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'type_name'
```

**Comment by tim-finnigan** [comment]
I'm still not able to reproduce this issue. Does the behavior change when you use other regions or boto3/botocore versions? Or when you pass any filters as documented in https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ec2/paginator/DescribeImages.html?

The [paginator model](https://github.com/boto/botocore/blob/ced307172e0c3718f084b6022c2d254cb860848d/botocore/data/ec2/2016-11-15/paginators-1.json#L791) appears to be consistent with other paginator models. Have you modified the models are you loading custom ones via `AWS_DATA_PATH` / `~/.aws/models`?

**Comment by sunkuamzn** [comment]
I created a brand new virtual environment and installed the latest `botocore` and `boto3` 1.33.8

```
Python 3.11.3 (main, Apr  7 2023, 19:29:16) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import boto3
>>> import botocore
>>> print(boto3.__version__)
1.33.8
>>> print(botocore.__version__)
1.33.8
>>> 
>>> client = boto3.client('ec2', region_name='eu-north-1')
>>> 
>>> paginator = client.get_paginator('describe_images')
>>> 
>>> page_iterator = paginator.paginate(
...     PaginationConfig={'PageSize': 512})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Volumes/workplace/libfabric-ci/src/venv/lib/python3.11/site-packages/botocore/client.py", line 1160, in paginate
    return Paginator.paginate(self, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/workplace/libfabric-ci/src/venv/lib/python3.11/site-packages/botocore/paginate.py", line 656, in paginate
    page_params = self._extract_paging_params(kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/workplace/libfabric-ci/src/venv/lib/python3.11/site-packages/botocore/paginate.py", line 685, in _extract_paging_params
    if limit_key_shape.type_name == 'string':
       ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'type_name'
>>> 
>>> for page in page_iterator:
...     print(page)
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'page_iterator' is not defined
>>> 
```

**Comment by sunkuamzn** [comment]
Found a custom model in `~/.aws/models` and removing it fixed the issue.
