### ISSUE TITLE
botocore using deprecated datetime.datetime.utcnow() call

### ISSUE THREAD

**Issue by paulschreiber** [boto/botocore#3088]
### Describe the bug

botocore is using `datetime.datetime.utcnow()`, which is deprecated. It generates this warning:
```
 DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
    datetime_now = datetime.datetime.utcnow()
```

### Expected Behavior

No warnings

### Current Behavior

DeprecationWarning

### Reproduction Steps

n/a

### Possible Solution

Use datetime.datetime.now(datetime.UTC)

### SDK version used

1.34.2

### Environment details (OS name and version, etc.)

Python 3.12.0

**Comment by nateprewitt** [comment]
Hi @paulschreiber,

Thanks for reaching out. We're currently tracking this in boto/boto3#3889. Unfortunately, this isn't as straight forward as replacing a function call. We already attempted this in https://github.com/boto/botocore/pull/3003/commits/96ca907d74d27ebb5ad715db4a75228fdc029a20 when 3.12 support was released and needed to roll it back due to breaking date serialization changes.

We're currently looking at removing the warnings long term in a backwards compatible manner, but don't have a timeline to provide. The `utcnow` deprecation is currently slated sometime after Python 3.16, so it's at least few years out. We'll work on getting it addressed more timely.

**Comment by iam-decoder** [comment]
After upgrading from python 3.11.11 to python 3.13, I get errors because of this:

```
    <class 'TypeError'> - account.py#453: issubclass() arg 2 must be a class, a tuple of classes, or a union
    Traceback (most recent call last):
      File "/path/to/my/code/models/account.py", line 453, in __verify_account_creds
        ....client('sts').get_caller_identity()
          ~~~~~~~~~~~~~~~~~~~^^
      File "/path/to/lib/python3.13/site-packages/botocore/client.py", line 570, in _api_call
        return self._make_api_call(operation_name, kwargs)
               ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
      File "/path/to/lib/python3.13/site-packages/botocore/context.py", line 124, in wrapper
        return func(*args, **kwargs)
      File "/path/to/lib/python3.13/site-packages/botocore/client.py", line 1013, in _make_api_call
        http, parsed_response = self._make_request(
                                ~~~~~~~~~~~~~~~~~~^
            operation_model, request_dict, request_context
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        )
        ^
      File "/Users/trneal2001/git/ami_bakery/.venv/lib/python3.13/site-packages/botocore/client.py", line 1037, in _make_request
        return self._endpoint.make_request(operation_model, request_dict)
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/trneal2001/git/ami_bakery/.venv/lib/python3.13/site-packages/botocore/endpoint.py", line 119, in make_request
        return self._send_request(request_dict, operation_model)
               ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/trneal2001/git/ami_bakery/.venv/lib/python3.13/site-packages/botocore/endpoint.py", line 196, in _send_request
        request = self.create_request(request_dict, operation_model)
      File "/Users/trneal2001/git/ami_bakery/.venv/lib/python3.13/site-packages/botocore/endpoint.py", line 132, in create_request
        self._event_emitter.emit(
        ~~~~~~~~~~~~~~~~~~~~~~~~^
            event_name,
            ^^^^^^^^^^^
            request=request,
            ^^^^^^^^^^^^^^^^
            operation_name=operation_model.name,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        )
        ^
      File "/Users/trneal2001/git/ami_bakery/.venv/lib/python3.13/site-packages/botocore/hooks.py", line 412, in emit
        return self._emitter.emit(aliased_event_name, **kwargs)
               ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/trneal2001/git/ami_bakery/.venv/lib/python3.13/site-packages/botocore/hooks.py", line 256, in emit
        return self._emit(event_name, kwargs)
               ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
      File "/Users/trneal2001/git/ami_bakery/.venv/lib/python3.13/site-packages/botocore/hooks.py", line 239, in _emit
        response = handler(**kwargs)
      File "/Users/trneal2001/git/ami_bakery/.venv/lib/python3.13/site-packages/botocore/signers.py", line 106, in handler
        return self.sign(operation_name, request)
               ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/trneal2001/git/ami_bakery/.venv/lib/python3.13/site-packages/botocore/signers.py", line 198, in sign
        auth.add_auth(request)
        ~~~~~~~~~~~~~^^^^^^^^^
      File "/Users/trneal2001/git/ami_bakery/.venv/lib/python3.13/site-packages/botocore/auth.py", line 426, in add_auth
        datetime_now = datetime.datetime.utcnow()
    TypeError: issubclass() arg 2 must be a class, a tuple of classes, or a union
```

ultimately, if I go to `botocore/auth.py", line 426, in add_auth` and change the line from:
```
datetime_now = datetime.datetime.utcnow()
```

to 

```
datetime_now = datetime.datetime.now(tz=datetime.timezone.utc)
```

the error goes away entirely. I assume there are plenty more spots that this needs to be updated, but I think before botocore is marked as 'supporting' Python 3.12+, this should absolutely be fixed.
