### ISSUE TITLE
Detected blocking call inside the event loop

### ISSUE THREAD

**Issue by chemelli74** [boto/botocore#3222]
### Describe the bug

Home Assistant since a few version detects blocking calls.

One is related to `botocore `and surfaces via [aiobotocore](https://github.com/aio-libs/aiobotocore).
I opened a PR to fix it, but I was redirected here ( <https://github.com/aio-libs/aiobotocore/pull/1120> )

### Expected Behavior

Avoid blocking calls inside the event loop

### Current Behavior

There are blocking calls inside the event loop

### Reproduction Steps

1. Install Home Assistant >= 2024.6.0
2. Configure AWS integration
4. Check log

### Possible Solution

None

### Additional Information/Context

2024-07-17 18:41:54.986 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to listdir with args ('/usr/local/lib/python3.12/site-packages/botocore/data/sns',) inside the event loop by integration 'aws' at homeassistant/components/aws/notify.py, line 38: return await session.get_available_regions(service) (offender: /usr/local/lib/python3.12/site-packages/botocore/loaders.py, line 363: for dirname in os.listdir(possible_path):), please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+aws%22
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#listdir
Traceback (most recent call last):
2024-07-17 18:41:54.994 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open with args ('/usr/local/lib/python3.12/site-packages/botocore/data/sns/2010-03-31/service-2.json.gz', 'rb') inside the event loop by integration 'aws' at homeassistant/components/aws/notify.py, line 38: return await session.get_available_regions(service) (offender: /usr/local/lib/python3.12/gzip.py, line 192: fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')), please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+aws%22
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run

### SDK version used

1.34.131

### Environment details (OS name and version, etc.)

Home Assistant Core (docker container): Alpine Linux v3.20.1

**Comment by tim-finnigan** [comment]
Thanks for reaching out. Boto3/Botocore does not use an event loop, that is all on the aiobotocore side. (Documentation on the Boto3 event system can be found [here]( https://boto3.amazonaws.com/v1/documentation/api/latest/guide/events.html)).

Regarding the discussion in https://github.com/aio-libs/aiobotocore/pull/1120 around the service models, the team has already made optimizations to reduce the size of the models. There are also open issues like https://github.com/boto/botocore/issues/2365 and https://github.com/boto/boto3/issues/3197 tracking the request to implement further improvements. On the topic of multithreading you can refer to the documentation for [sessions](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/session.html#multithreading-or-multiprocessing-with-sessions) (not thread safe) and [clients](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/clients.html#multithreading-or-multiprocessing-with-clients).

We cannot guarantee compatibility with third-party software like Home Assistant or aiobotocore. For requests that directly involve Boto3/Botocore you can +1 (👍) existing issues or share a code snippet and logs to highlight the problem you're experiencing.
