### ISSUE TITLE
ParamValidationError for invalid bucket name when Config.parameter_validation is False

### ISSUE THREAD

**Issue by cbodley** [boto/botocore#3234]
### Describe the bug

Setting `parameter_validation=False` in [botocore.config.Config](https://botocore.amazonaws.com/v1/documentation/api/latest/reference/config.html) does not disable validation of bucket names.

### Expected Behavior

expected boto to issue the request with the given bucket name

### Current Behavior

`client.create_bucket(Bucket='test;bucket')` raises `botocore.exceptions.ParamValidationError`:
```
Traceback (most recent call last):
  File "/home/cbodley/test.py", line 9, in <module>
    client.create_bucket(Bucket='test;bucket')
  File "/usr/lib/python3.12/site-packages/botocore/client.py", line 565, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/botocore/client.py", line 958, in _make_api_call
    api_params = self._emit_api_params(
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/botocore/client.py", line 1077, in _emit_api_params
    self.meta.events.emit(
  File "/usr/lib/python3.12/site-packages/botocore/hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/botocore/hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
               ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/botocore/handlers.py", line 287, in validate_bucket_name
    raise ParamValidationError(report=error_msg)
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid bucket name "test;bucket": Bucket name must match the regex "^[a-zA-Z0-9.\-_]{1,255}$" or be an ARN matching the regex "^arn:(aws).*:(s3|s3-object-lambda):[a-z\-0-9]*:[0-9]{12}:accesspoint[/:][a-zA-Z0-9\-.]{1,63}$|^arn:(aws).*:s3-outposts:[a-z\-0-9]+:[0-9]{12}:outpost[/:][a-zA-Z0-9\-]{1,63}[/:]accesspoint[/:][a-zA-Z0-9\-]{1,63}$"
```

### Reproduction Steps

```py
import botocore
import boto3

cfg = botocore.config.Config(parameter_validation=False,
                             s3={"addressing_style": "path"})
client = boto3.client(service_name='s3',
                      endpoint_url='http://localhost:8000',
                      config=cfg)
client.create_bucket(Bucket='test;bucket')
```

### Possible Solution

avoid calling `validate_bucket_name()` when `Config.parameter_validation` is False

### Additional Information/Context

testing against s3-compatible Ceph server which optionally supports 'relaxed' bucket naming requirements

### SDK version used

1.34.153

### Environment details (OS name and version, etc.)

Fedora 40, python 3.12

**Comment by tim-finnigan** [comment]
Thanks for reaching out. This came up before in the Boto3 repo: https://github.com/boto/boto3/issues/2891

As mentioned [there](https://github.com/boto/boto3/issues/2891#issuecomment-859789338):
>Unfortunately the parameter validation flag unfortunately does not apply to S3 validation. Those validators are part of a customization. If you can provide more details on what your use case would be, we can discuss if this is a useful feature request for others as well.

**Comment by timj** [comment]
How do we disable bucket name validation then? Our Ceph buckets are of the form "x:y" and we currently have to disable the checks by doing:

```python
>>> from botocore.handlers import validate_bucket_name
>>> client.meta.events.unregister("before-parameter-build.s3", validate_bucket_name)
```
but this can't be done if we are using s3fs where the client object is internal and whose creation is deferred until needed.

See https://github.com/fsspec/s3fs/issues/893

**Comment by tim-finnigan** [comment]
Converting to a feature request — not sure if there's a good workaround for third-party use cases here.
