### ISSUE TITLE
Not well-formed (invalid token): line 2, column 344955

### ISSUE THREAD

**Issue by gotlium** [boto/botocore#440]
2015-01-26 10:41:00,033 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
    Traceback (most recent call last):
      File "/root/src/awscli/awscli/clidriver.py", line 197, in main
        return command_table[parsed_args.command](remaining, parsed_args)
      File "/root/src/awscli/awscli/clidriver.py", line 357, in __call__
        return command_table[parsed_args.operation](remaining, parsed_globals)
      File "/root/src/awscli/awscli/clidriver.py", line 492, in __call__
        self._operation_object, call_parameters, parsed_globals)
      File "/root/src/awscli/awscli/clidriver.py", line 594, in invoke
        parsed_globals)
      File "/root/src/awscli/awscli/clidriver.py", line 607, in _display_response
        formatter(operation, response)
      File "/root/src/awscli/awscli/formatter.py", line 58, in __call__
        response_data = response.build_full_result()
      File "/usr/local/lib/python2.7/dist-packages/botocore/paginate.py", line 215, in build_full_result
        for _, page in self:
      File "/usr/local/lib/python2.7/dist-packages/botocore/paginate.py", line 70, in __iter__
        response = self._make_request(current_kwargs)
      File "/usr/local/lib/python2.7/dist-packages/botocore/paginate.py", line 390, in _make_request
        return self._operation.call(self._endpoint, **current_kwargs)
      File "/usr/local/lib/python2.7/dist-packages/botocore/operation.py", line 90, in call
        response = endpoint.make_request(self.model, request_dict)
      File "/usr/local/lib/python2.7/dist-packages/botocore/endpoint.py", line 110, in make_request
        return self._send_request(prepared_request, operation_model)
      File "/usr/local/lib/python2.7/dist-packages/botocore/endpoint.py", line 171, in _send_request
        request, operation_model, attempts)
      File "/usr/local/lib/python2.7/dist-packages/botocore/endpoint.py", line 204, in _get_response
        operation_model.output_shape)),
      File "/usr/local/lib/python2.7/dist-packages/botocore/parsers.py", line 210, in parse
        parsed = self._do_parse(response, shape)
      File "/usr/local/lib/python2.7/dist-packages/botocore/parsers.py", line 548, in _do_parse
        self._parse_payload(response, shape, member_shapes, final_parsed)
      File "/usr/local/lib/python2.7/dist-packages/botocore/parsers.py", line 581, in _parse_payload
        original_parsed = self._initial_body_parse(response['body'])
      File "/usr/local/lib/python2.7/dist-packages/botocore/parsers.py", line 655, in _initial_body_parse
        return self._parse_xml_string_to_dom(xml_string)
      File "/usr/local/lib/python2.7/dist-packages/botocore/parsers.py", line 337, in _parse_xml_string_to_dom
        parser.feed(xml_string)
    ParseError: not well-formed (invalid token): line 2, column 344955
    2015-01-26 10:41:00,033 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255

    not well-formed (invalid token): line 2, column 344955

this is a problem with uploaded file name

    wpz1trtj.bmpҰഷ￻￿㵰ഷ￻￿&#xt

**Comment by jamesls** [comment]
Can you show a sample code that demonstrates this issue?

**Comment by gotlium** [comment]
aws s3api list-objects --region eu-west-1 --bucket media.lpgenerator.ru --output json --query "[sum(Contents[].Size), length(Contents[])]"

xml string

    <Owner><ID>5d63b45b47d6889d1b24546db5b1e6f296ad67c639d8bdbe2a8eae8ac1fa5932</ID> 
    <DisplayName>archik11</DisplayName></Owner><StorageClass>STANDARD</StorageClass>
    </Contents>
    <Contents><Key>images/119083/
    wpz1trtj.bmpҰഷ￻￿㵰ഷ￻￿&#xt

after removing file from web all is ok

**Comment by jamesls** [comment]
Ah yes.  This issue is because S3 returns an XML document that our XML parser in python cannot parse.       The fix for this is to use an --encoding-type "url" which will urlencode the key names, and then to urldecode the keys on the response.  We do this automatically for the high level `s3 cp/mv/sync` commands, but we don't do this for the low level `s3api list-objects` command.  I think we should just add a customization in the `ListObjects` operation to always apply this option and urldecode the keys before returning to the customer.

**Comment by JordonPhillips** [comment]
We automatically set this encoding if it isn't provided as of #726
