### ISSUE TITLE
route53 client list_resource_record_sets fails with StartRecordType

### ISSUE THREAD

**Issue by phobologic** [boto/botocore#532]
**OS:** OS X Yosemite
**Python:** 2.7.6
**botocore:** 0.106.0

I'm trying to get the SOA records on a route53 hosted zone.  When I try to do so, it fails badly - I get the following response:

```python
{'ResponseMetadata': {'HTTPStatusCode': 400, 'RequestId': '24865775-f4fb-11e4-a914-45b54a9f75e8'}, 'Error': {'Code': 'InvalidInput', 'Type': 'Sender'}}
```

This is further exacerbated in `exceptions.ClientError.__init__` when it looks for ['Error']['Message'] which doesn't exist in the InvalidInput error.

Here's the code I'm using:

```python
>>> from boto3.session import Session
>>> sess = Session(region_name='us-east-1')
>>> r53 = sess.client('route53')
>>> zone = r53.list_hosted_zones_by_name(DNSName='example.com.')['HostedZones'][0]
>>> zid = zone['Id']
>>> r53.list_resource_record_sets(HostedZoneId=zid, StartRecordType='SOA')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mike/venv/stacker/lib/python2.7/site-packages/botocore-0.106.0-py2.7.egg/botocore/client.py", line 199, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/mike/venv/stacker/lib/python2.7/site-packages/botocore-0.106.0-py2.7.egg/botocore/client.py", line 254, in _make_api_call
    raise ClientError(parsed_response, operation_name)
  File "/Users/mike/venv/stacker/lib/python2.7/site-packages/botocore-0.106.0-py2.7.egg/botocore/exceptions.py", line 300, in __init__
    error_message=error_response['Error']['Message'],
KeyError: 'Message'
```

**Comment by kyleknap** [comment]
I can confirm. Thanks for looking into this. Will look into fixing.

**Comment by jamesls** [comment]
Debug logs:

Example error when hosted zone id does not exist:

```
2015-06-17 15:43:19,497 - botocore.parsers - DEBUG - Response headers: {'x-amzn-requestid': 'id', 'date': 'Wed, 17 Jun 2015 22:42:26 GMT', 'content-length': '288', 'content-type': 'text/xml'}
2015-06-17 15:43:19,497 - botocore.parsers - DEBUG - Response body:
<?xml version="1.0"?>
<ErrorResponse xmlns="https://route53.amazonaws.com/doc/2013-04-01/"><Error><Type>Sender</Type><Code>NoSuchHostedZone</Code><Message>No hosted zone found with ID: asdfasdfsd</Message></Error><RequestId>id</RequestId></ErrorResponse>
```

Example error with missing message:


```
2015-06-17 15:42:46,275 - botocore.parsers - DEBUG - Response headers: {'x-amzn-requestid': 'id', 'content-length': '225', 'x-amzn-actiontrace': 'id', 'date': 'Wed, 17 Jun 2015 22:41:53 GMT', 'nncoection': 'close', 'content-type': 'text/xml'}
2015-06-17 15:42:46,275 - botocore.parsers - DEBUG - Response body:
<?xml version="1.0"?>
<ErrorResponse xmlns="https://route53.amazonaws.com/doc/2013-04-01/"><Error><Type>Sender</Type><Code>InvalidInput</Code></Error><RequestId>id</RequestId></ErrorResponse>
```

Looks like neither the XML error response nor the response headers contain an error message in the second case.  I'll go ahead and follow up with the Amazon Route53 team about the missing error message, but in the meantime we can update botocore to handle this gracefully so we don't propogate a KeyError.
