### ISSUE TITLE
Test Failures in 1.3.12

### ISSUE THREAD

**Issue by alunduil** [boto/botocore#738]
Not sure if I'm missing something while running these tests but these are the only failures I'm experiencing while packaging botocore:

```
................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................E.E.....................................................................................................................................................................................................................
======================================================================
ERROR: test_generate_presigned_post (tests.unit.test_signers.TestS3PostPresigner)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/botocore-1.3.12/work/botocore-1.3.12/tests/unit/test_signers.py", line 366, in test_generate_presigned_post
    self.add_auth.assert_called_once()
  File "/usr/lib64/python2.7/site-packages/mock/mock.py", line 721, in __getattr__
    raise AttributeError(name)
AttributeError: assert_called_once

======================================================================
ERROR: test_generate_presigned_post_with_conditions (tests.unit.test_signers.TestS3PostPresigner)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/botocore-1.3.12/work/botocore-1.3.12/tests/unit/test_signers.py", line 388, in test_generate_presigned_post_with_conditions
    self.add_auth.assert_called_once()
  File "/usr/lib64/python2.7/site-packages/mock/mock.py", line 721, in __getattr__
    raise AttributeError(name)
AttributeError: assert_called_once

----------------------------------------------------------------------
Ran 1608 tests in 17.543s

FAILED (errors=2)
```

**Comment by kyleknap** [comment]
All of the tests and CI's that we track are passing on our side. Can you tell us how you are running the tests? It could be a bad patch that is causing the errors for you but not us.

**Comment by alunduil** [comment]
@kyleknap sure thing.  I'm running the tests as part of this ebuild: https://github.com/alunduil/alunduil-overlay/blob/master/dev-python/botocore/botocore-1.3.12.ebuild

I'm using the pypi sdist and not applying any patches.  As you can see I'm keeping it pretty vanilla.  I do run the tests manually:

```
    nosetests tests/unit || die "tests failed under ${EPYTHON}"
```

This is just to ensure that I've done the install correctly and that the units pass appropriately.  Thanks for any pointers.

**Comment by kyleknap** [comment]
Ahh I know what the issue is. What version of mock are you using when you run the tests? You need to make sure you are running 1.0.1 of mock: https://github.com/boto/botocore/blob/develop/requirements.txt#L4.

So if I upgrade to the very latest mock version. I get the same issue as you:
```
$ nosetests tests/unit/
..................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................E.E.....................................................................................................................................................................................................................
======================================================================
ERROR: test_generate_presigned_post (tests.unit.test_signers.TestS3PostPresigner)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/kyleknap/Documents/GitHub/botocore/tests/unit/test_signers.py", line 366, in test_generate_presigned_post
    self.add_auth.assert_called_once()
  File "/Users/kyleknap/Documents/venv/boto3-34/lib/python3.4/site-packages/mock/mock.py", line 721, in __getattr__
    raise AttributeError(name)
AttributeError: assert_called_once

======================================================================
ERROR: test_generate_presigned_post_with_conditions (tests.unit.test_signers.TestS3PostPresigner)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/kyleknap/Documents/GitHub/botocore/tests/unit/test_signers.py", line 388, in test_generate_presigned_post_with_conditions
    self.add_auth.assert_called_once()
  File "/Users/kyleknap/Documents/venv/boto3-34/lib/python3.4/site-packages/mock/mock.py", line 721, in __getattr__
    raise AttributeError(name)
AttributeError: assert_called_once

----------------------------------------------------------------------
Ran 1610 tests in 6.472s

FAILED (errors=2)
```
Then when I switch back to 1.0.1, all of the test pass. So I think that should fix for you. Let me know.

**Comment by alunduil** [comment]
Yep, that was it.  Can we transform this issue into a request for compatibility with newer versions of mock (or dropping it as it's already part of unittest in python-3 and up)?

**Comment by jamesls** [comment]
@kyleknap Actually, I think this is a legitimate test bug.  `assert_called_once` does not exist.  There's an `assert_called_once_with`, but no `assert_called_once`.  Docs: https://docs.python.org/dev/library/unittest.mock.html

Looks like in later version of mock, they provided a helpful error check to ensure we're not using non existent assert methods (https://github.com/testing-cabal/mock/blob/master/mock/mock.py#L717-L718), from: http://bugs.python.org/issue21238

While we could just change this to `assert_called_once_with`, I'd prefer to just fall back to asserting that the `.call_count == 1`.  It'll work with older version of mock, as well as the latest version of mock.

I'll send a PR shortly.
