### ISSUE TITLE
('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

### ISSUE THREAD

**Issue by falknes** [boto/botocore#789]
Once in a while my server, running on AWS EC2, gets RemoteDisconnected exceptions while trying to retrieve data from dynamodb. I have tried to reproduce the issue locally without any luck. Is this a know issue or is it only happening to me? Is there a way to retry when you encounter a ConnectionError without adding my own retry everywhere i do queries agains dynamodb?

Adding tracback information and current setup bellow 

```Python
Error message
botocore.vendored.requests.exceptions:ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
```

```Python
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/botocore/vendored/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/usr/local/lib/python3.5/site-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", line 597, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.5/site-packages/botocore/vendored/requests/packages/urllib3/util/retry.py", line 245, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.5/site-packages/botocore/vendored/requests/packages/urllib3/packages/six.py", line 309, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/site-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/usr/local/lib/python3.5/site-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", line 374, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.5/http/client.py", line 1174, in getresponse
    response.begin()
  File "/usr/local/lib/python3.5/http/client.py", line 282, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.5/http/client.py", line 251, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
    botocore.vendored.requests.packages.urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
```

```Python
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/usr/local/lib/python3.5/site-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", line 374, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.5/http/client.py", line 1174, in getresponse
    response.begin()
  File "/usr/local/lib/python3.5/http/client.py", line 282, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.5/http/client.py", line 251, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
    http.client.RemoteDisconnected: Remote end closed connection without response
```

**Current setup on servers**
- Amazon Linux AMI 2015.09.e x86_64
- python 3.5
- gunicorn==19.4.5
- gevent==1.1rc1
- botocore==1.3.24

**Comment by JordonPhillips** [comment]
We do currently perform an exponential back-off retry when we encounter such errors, so this must be happening several times in a row. Services will occasionally close a connection for one reason or another, but it usually isn't so frequent. Is there anything unusual about the payloads you're sending when this occurs? If you could provide debug logs that would help immensely. (You can enable these with `Session.set_debug_logger()`.

**Comment by dkarchmer** [comment]
I get the same problem while creating new items. It is random and unfrequent, but still an issue as it is unclear how to recover from it. I am currently pushing a code change to simply retry one more time before returning a 500 error. I will enable Session.set_debug_logger()
