### ISSUE TITLE
When a client sets test=True, the same class of error is raised as for a failure?

### ISSUE THREAD

**Issue by pcn** [boto/botocore#842]
Using boto3, if I try to execute a client request with test=True, the exception that's raised at https://github.com/boto/botocore/blob/b0cde71c56752f2eeead039ad2a7a0b14b3b9933/botocore/client.py#L491-L494 looks the same as any other client error, except for the text.

How is one supposed to test code when this raises the same exception for a client error as for a test?

**Comment by pcn** [comment]
```
Traceback (most recent call last):
  File "coatlink.py", line 50, in <module>
    print m[0].attach_classic_link_vpc(DryRun=True, VpcId=stagevpc_id, Groups=m[1])
  File "/Users/peter.norton/.pyenv/versions/aws/lib/python2.7/site-packages/boto3/resources/factory.py", line 481, in do_action
    response = action(self, *args, **kwargs)
  File "/Users/peter.norton/.pyenv/versions/aws/lib/python2.7/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(**params)
  File "/Users/peter.norton/.pyenv/versions/aws/lib/python2.7/site-packages/botocore/client.py", line 228, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/peter.norton/.pyenv/versions/aws/lib/python2.7/site-packages/botocore/client.py", line 492, in _make_api_call
    raise ClientError(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (DryRunOperation) when calling the AttachClassicLinkVpc operation: Request would have succeeded, but DryRun flag is set.
(aws) ip-192-168-10-102:work peter.norton$ less /Users/peter.norton/.pyenv/versions/aws/lib/python2.7/site-packages/botocore/client.py
```

**Comment by JordonPhillips** [comment]
This is an unfortunate side-effect of how EC2 responds to dry run operations, returning an HTTP error even if the dry run would have succeeded. You can check the error code to distinguish:

```python
except ClientError as e:
    if e.response['Error'].get('Code') == 'DryRunOperation':
        # success
    else:
        # failure
```

**Comment by ringerc** [comment]
Still a bug IMO. Boto can adapt this to the appropriate language convention, which in this case is definitely a subclass of `ClientError`
