### ISSUE TITLE
Errors when try to sync upload to bucket with last version

### ISSUE THREAD

**Issue by fredericofs** [boto/botocore#877]
I am having there errors:

```
Content-Type: application/xml
Accept-Ranges: bytes
x-amz-request-id: tx0000000000000025424ca-00570d4891-c9fa396-default
Content-Length: 78
Date: Tue, 12 Apr 2016 19:12:47 GMT
2016-04-12 16:12:48,101 - Thread-3 - botocore.response - DEBUG - Response Body:
b'<?xml version="1.0" encoding="UTF-8"?><Error><Code>AccessDenied</Code></Error>'
2016-04-12 16:12:48,189 - Thread-3 - botocore.hooks - DEBUG - Event needs-retry.s3.PutObject: calling handler <botocore.retryhandler.RetryHandler object at 0xb5f98a90>
2016-04-12 16:12:48,219 - Thread-3 - botocore.retryhandler - DEBUG - No retry needed.
2016-04-12 16:12:48,244 - Thread-3 - botocore.hooks - DEBUG - Event after-call.s3.PutObject: calling handler <awscli.errorhandler.ErrorHandler object at 0xb6150250>
2016-04-12 16:12:48,260 - Thread-3 - awscli.errorhandler - DEBUG - HTTP Response Code: 403
2016-04-12 16:12:48,291 - Thread-3 - awscli.customizations.s3.tasks - DEBUG - A client error (AccessDenied) occurred when calling the PutObject operation: Unknown
Traceback (most recent call last):
  File "/usr/share/awscli/awscli/customizations/s3/tasks.py", line 88, in _execute_task
    getattr(filename, filename.operation_name)()
  File "/usr/share/awscli/awscli/customizations/s3/fileinfo.py", line 221, in upload
    response_data, http = operate(self.service, 'PutObject', params)
  File "/usr/share/awscli/awscli/customizations/s3/utils.py", line 181, in operate
    http_response, response_data = operation.call(**kwargs)
  File "/usr/lib/python3/dist-packages/botocore/operation.py", line 74, in call
    parsed=response[1])
  File "/usr/lib/python3/dist-packages/botocore/session.py", line 654, in emit
    return self._events.emit(event_name, **kwargs)
  File "/usr/lib/python3/dist-packages/botocore/hooks.py", line 148, in emit
    response = handler(**kwargs)
  File "/usr/share/awscli/awscli/errorhandler.py", line 75, in __call__
    http_status_code=http_response.status_code)
awscli.errorhandler.ClientError: A client error (AccessDenied) occurred when calling the PutObject operation: Unknown
2016-04-12 16:12:48,553 - Thread-3 - awscli.customizations.s3.executor - DEBUG - Shutdown request received in worker thread, shutting down worker thread.
2016-04-12 16:12:48,563 - Thread-1 - awscli.customizations.s3.executor - DEBUG - Received print task: {'error': True, 'message': 'upload failed: ./000000000f6b9e16.txt to s3://temakilogs/000000000f6b9e16.txt A client error (AccessDenied) occurred when calling the PutObject operation: Unknown'}
```

**Comment by kyleknap** [comment]
It sounds like you do not have your credentials set correctly or you do not have access to the bucket. Could I get a full debug log and also tell me where your credentials are being pulled from (you can tell this by running ``aws configure list``).

**Comment by kyleknap** [comment]
Closing due to inactivity. Please let us know if you have more information
