### ISSUE TITLE
Botocore throws exception when sending large number of requests (>1000)

### ISSUE THREAD

**Issue by ocervell** [boto/botocore#895]
I am querying Cloudwatch data from my script. 

The code is the following:
```
result = self.cw.get_metric_statistics(Namespace=self.namespace,
                                                       MetricName=self.metric_name,
                                                       StartTime=self.start_time,
                                                       EndTime=self.end_time,
                                                       Period=self.period,
                                                       Dimensions=self.dimensions,
                                                       Statistics=self.statistics)
                # Check HTTP Status Code
                if result['ResponseMetadata']['HTTPStatusCode'] == 200:
                    result['Datapoints'].sort(reverse=True)
                else:
                    raise Exception("Unsuccessful response: ", result['ResponseMetadata']['HTTPStatusCode'])

                return result['Datapoints'][0][self.statistics[0]]
```

After ~1000 successful requests, all the successive requests fail with the following exception.
```
2016-04-25 20:49:49,964 | INFO | connectionpool.py | 735 | Starting new HTTPS connection (1): monitoring.us-east-1.amazonaws.com
2016-04-25 20:49:50,900 | INFO | connectionpool.py | 735 | Starting new HTTPS connection (2): monitoring.us-east-1.amazonaws.com
2016-04-25 20:49:51,243 | INFO | connectionpool.py | 735 | Starting new HTTPS connection (3): monitoring.us-east-1.amazonaws.com
2016-04-25 20:49:56,838 | INFO | connectionpool.py | 735 | Starting new HTTPS connection (4): monitoring.us-east-1.amazonaws.com
2016-04-25 20:50:02,899 | INFO | connectionpool.py | 735 | Starting new HTTPS connection (5): monitoring.us-east-1.amazonaws.com
 File "/home/ubuntu/devops-monitoring/monitoring/collectors/cloud_watch.py", line 41, in _get_point
    Statistics=self.statistics)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 301, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 387, in _make_api_call
    operation_model, request_dict)
  File "/usr/local/lib/python2.7/dist-packages/botocore/endpoint.py", line 117, in make_request
    return self._send_request(request_dict, operation_model)
  File "/usr/local/lib/python2.7/dist-packages/botocore/endpoint.py", line 146, in _send_request
    success_response, exception):
  File "/usr/local/lib/python2.7/dist-packages/botocore/endpoint.py", line 219, in _needs_retry
    caught_exception=caught_exception)
  File "/usr/local/lib/python2.7/dist-packages/botocore/hooks.py", line 226, in emit
    return self._emit(event_name, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/hooks.py", line 209, in _emit
    response = handler(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/usr/local/lib/python2.7/dist-packages/botocore/retryhandler.py", line 250, in __call__
    caught_exception)
  File "/usr/local/lib/python2.7/dist-packages/botocore/retryhandler.py", line 273, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/usr/local/lib/python2.7/dist-packages/botocore/retryhandler.py", line 313, in __call__
    caught_exception)
  File "/usr/local/lib/python2.7/dist-packages/botocore/retryhandler.py", line 222, in __call__
    return self._check_caught_exception(attempt_number, caught_exception)
  File "/usr/local/lib/python2.7/dist-packages/botocore/retryhandler.py", line 355, in _check_caught_exception
    raise caught_exception
SSLError: [Errno 185090050] _ssl.c:344: error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib
```

**Comment by JordonPhillips** [comment]
This looks like an SSL error, specifically an error loading the cacerts. How do you have your certs configured?

**Comment by ocervell** [comment]
I know it looks like SSL error, but I don't think it is. Alternatively I get an EndpointConnectionError:

```
2016-04-27 14:56:40,858 | ERROR | cloud_watch.py | 59 | Could not connect to the endpoint URL: "https://monitoring.us-east-1.amazonaws.com/"
Traceback (most recent call last):
  File "/Users/ocervell/Drive/workspace/ccc/svn/build-support/branches/development-ocervell/devops-monitoring/monitoring/collectors/cloud_watch.py", line 44, in _get_point
    Statistics=self.statistics)
  File "/Users/ocervell/.virtualenvs/monitoring/lib/python2.7/site-packages/botocore-1.3.30-py2.7.egg/botocore/client.py", line 301, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/ocervell/.virtualenvs/monitoring/lib/python2.7/site-packages/botocore-1.3.30-py2.7.egg/botocore/client.py", line 387, in _make_api_call
    operation_model, request_dict)
  File "/Users/ocervell/.virtualenvs/monitoring/lib/python2.7/site-packages/botocore-1.3.30-py2.7.egg/botocore/endpoint.py", line 117, in make_request
    return self._send_request(request_dict, operation_model)
  File "/Users/ocervell/.virtualenvs/monitoring/lib/python2.7/site-packages/botocore-1.3.30-py2.7.egg/botocore/endpoint.py", line 146, in _send_request
    success_response, exception):
  File "/Users/ocervell/.virtualenvs/monitoring/lib/python2.7/site-packages/botocore-1.3.30-py2.7.egg/botocore/endpoint.py", line 219, in _needs_retry
    caught_exception=caught_exception)
  File "/Users/ocervell/.virtualenvs/monitoring/lib/python2.7/site-packages/botocore-1.3.30-py2.7.egg/botocore/hooks.py", line 226, in emit
    return self._emit(event_name, kwargs)
  File "/Users/ocervell/.virtualenvs/monitoring/lib/python2.7/site-packages/botocore-1.3.30-py2.7.egg/botocore/hooks.py", line 209, in _emit
    response = handler(**kwargs)
  File "/Users/ocervell/.virtualenvs/monitoring/lib/python2.7/site-packages/botocore-1.3.30-py2.7.egg/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/Users/ocervell/.virtualenvs/monitoring/lib/python2.7/site-packages/botocore-1.3.30-py2.7.egg/botocore/retryhandler.py", line 250, in __call__
    caught_exception)
  File "/Users/ocervell/.virtualenvs/monitoring/lib/python2.7/site-packages/botocore-1.3.30-py2.7.egg/botocore/retryhandler.py", line 273, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/Users/ocervell/.virtualenvs/monitoring/lib/python2.7/site-packages/botocore-1.3.30-py2.7.egg/botocore/retryhandler.py", line 313, in __call__
    caught_exception)
  File "/Users/ocervell/.virtualenvs/monitoring/lib/python2.7/site-packages/botocore-1.3.30-py2.7.egg/botocore/retryhandler.py", line 222, in __call__
    return self._check_caught_exception(attempt_number, caught_exception)
  File "/Users/ocervell/.virtualenvs/monitoring/lib/python2.7/site-packages/botocore-1.3.30-py2.7.egg/botocore/retryhandler.py", line 355, in _check_caught_exception
    raise caught_exception
EndpointConnectionError: Could not connect to the endpoint URL: "https://monitoring.us-east-1.amazonaws.com/"
```

This happened when I multithreaded my program to have a higher rate of querying CloudWatch. 
This looks like it comes from the default rate limit CloudWatch imposes on users. In this case those error messages don't indicate that at all.

**Comment by ocervell** [comment]
```
2016-04-27 15:07:02,676 | DEBUG | hooks.py | 208 | Event request-created.monitoring.GetMetricStatistics: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x108c6bf90>>
2016-04-27 15:07:02,678 | DEBUG | auth.py | 316 | Calculating signature using v4 auth.
2016-04-27 15:07:02,678 | DEBUG | auth.py | 317 | CanonicalRequest:
POST
/

host:monitoring.us-east-1.amazonaws.com
user-agent:Boto3/1.2.3 Python/2.7.10 Darwin/14.5.0 Botocore/1.3.30
x-amz-date:20160427T200702Z

host;user-agent;x-amz-date
a2b89fd4e32f325697dd961219e1f91973ab24dac0aea0c38c1188d017f90fdd
2016-04-27 15:07:02,679 | DEBUG | auth.py | 319 | StringToSign:
AWS4-HMAC-SHA256
20160427T200702Z
20160427/us-east-1/monitoring/aws4_request
8c3d40d7896056999ea8a08175c762c6e18e6e09c0391576844421735b758902
2016-04-27 15:07:02,680 | DEBUG | auth.py | 321 | Signature:
2edc87dcc46564d624b7a9dac3babe0ac53c6e440f82072e9f858a4484d84532
2016-04-27 15:07:02,682 | DEBUG | endpoint.py | 170 | Sending http request: <PreparedRequest [POST]>
2016-04-27 15:07:02,683 | INFO | connectionpool.py | 735 | Starting new HTTPS connection (5): monitoring.us-east-1.amazonaws.com
2016-04-27 15:07:02,687 | DEBUG | endpoint.py | 181 | ConnectionError received when sending HTTP request.
Traceback (most recent call last):
  File "/Users/ocervell/.virtualenvs/monitoring/lib/python2.7/site-packages/botocore-1.3.30-py2.7.egg/botocore/endpoint.py", line 174, in _get_response
    proxies=self.proxies, timeout=self.timeout)
  File "/Users/ocervell/.virtualenvs/monitoring/lib/python2.7/site-packages/botocore-1.3.30-py2.7.egg/botocore/vendored/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/Users/ocervell/.virtualenvs/monitoring/lib/python2.7/site-packages/botocore-1.3.30-py2.7.egg/botocore/vendored/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', gaierror(8, 'nodename nor servname provided, or not known'))
2016-04-27 15:07:02,687 | ERROR | cloud_watch.py | 58 | CloudWatchDataPoint._get_point() | Could not connect to the endpoint URL: "https://monitoring.us-east-1.amazonaws.com/"
```

Here is the full traceback.

**Comment by JordonPhillips** [comment]
Are you sharing a session between threads?

**Comment by ocervell** [comment]
Yes.

**Comment by ocervell** [comment]
Ok I resolved this issue by NOT sharing my session between threads. 
What I do is instantiate cw = session.client('cloudwatch') and pass this to my threads instead.
Clients seem to be threadsafe.

**Comment by JordonPhillips** [comment]
Ideally you should create new sessions for each thread

**Comment by jamesls** [comment]
As suggested, the best approach is to create clients and either share between threads or have one client per thread.  Closing out issue.
