### ISSUE TITLE
ParamValidationError for "Runtime" from Lambda client.update_function_configuration

### ISSUE THREAD

**Issue by FrancescoRizzi** [boto/botocore#901]
Hello.
I stumbled upon this error:
```
ParamValidationError: Parameter validation failed:
Unknown parameter in input: "Runtime", must be one of: FunctionName, Role, Handler, Description, Timeout, MemorySize, VpcConfig
```

This is triggered when I try to call update_function_configuration on a Lambda client, eg:

```
client = mySession.client('lambda')
response = client.update_function_configuration(
            FunctionName=args['FunctionName'],
            Role=args['Role'],
            Handler=args['Handler'],
            Description=args['Description'],
            Timeout=args['Timeout'],
            MemorySize=args['MemorySize'],
            Runtime=args['Runtime']
            )
```

From the [Readthedocs\Available Services\Lambda\Client\update_function_configuration documentation](http://botocore.readthedocs.io/en/latest/reference/services/lambda.html#Lambda.Client.update_function_configuration), I thought the "Runtime" parameter could be included, and even the [AWS Lambda API Reference](http://docs.aws.amazon.com/lambda/latest/dg/API_UpdateFunctionConfiguration.html) seems to agree.

I'm using:
Mac OS X El Capitan (10.11.4)
Python 2.7.6
botocore 1.4.4
boto3 1.3.0

More stack trace bits, just in case:
```
Traceback (most recent call last):
  [...]
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/client.py", line 228, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/client.py", line 468, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/client.py", line 521, in _convert_to_request_dict
    api_params, operation_model)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/validate.py", line 269, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
ParamValidationError: Parameter validation failed:
Unknown parameter in input: "Runtime", must be one of: FunctionName, Role, Handler, Description, Timeout, MemorySize, VpcConfig
```

**Comment by JordonPhillips** [comment]
That's... really strange. Could you post the debug log for that function? You can enable debugging with `boto3.set_stream_logger('botocore')`.

**Comment by FrancescoRizzi** [comment]
Here's an interactive session:

I replaced [MYARN_FOR_LAMBAS] where I had the actual ARN to a Role,
and I had previously created a 'DEV-SampleLambda1' Lambda Function (with code),
so I'm replicating just the update scenario:

```
Python 2.7.6 (v2.7.6:3a1db0d2747e, Nov 10 2013, 00:42:54) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import boto3
>>> from boto3.session import Session
>>> boto3.set_stream_logger('botocore')
>>> session = Session()
>>> client = session.client('lambda')

2016-04-28 18:41:14,086 botocore.credentials [DEBUG] Skipping environment variable credential check because profile name was explicitly set.
2016-04-28 18:41:14,086 botocore.credentials [DEBUG] Looking for credentials via: env
2016-04-28 18:41:14,086 botocore.credentials [DEBUG] Looking for credentials via: assume-role
2016-04-28 18:41:14,086 botocore.credentials [DEBUG] Looking for credentials via: shared-credentials-file
2016-04-28 18:41:14,087 botocore.credentials [INFO] Found credentials in shared credentials file: ~/.aws/credentials
2016-04-28 18:41:14,124 botocore.client [DEBUG] Registering retry handlers for service: lambda
2016-04-28 18:41:14,127 botocore.hooks [DEBUG] Event creating-client-class.lambda: calling handler <function add_generate_presigned_url at 0x10326a6e0>
2016-04-28 18:41:14,295 botocore.endpoint [DEBUG] Setting lambda timeout as (60, 60)

>>> response = client.update_function_configuration(FunctionName='DEV-SampleLambda1', Role='[MYARN_FOR_LAMBDAS]', Handler='sample_lambda_1.handler', Description='Sample Lambda 1', Timeout=3, MemorySize=128, Runtime='python2.7')

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/client.py", line 228, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/client.py", line 468, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/client.py", line 521, in _convert_to_request_dict
    api_params, operation_model)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/validate.py", line 269, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Unknown parameter in input: "Runtime", must be one of: FunctionName, Role, Handler, Description, Timeout, MemorySize, VpcConfig
```

Thankfully, this is not blocking me atm, as I don't intend to switch (update) Runtime after creation of my Lambda Functions, so I can just skip the Runtime arg when I'm making calls to update_function_configuration, but if it's a surprising error to you it may be something.

HTH

**Comment by JordonPhillips** [comment]
@FrancescoRizzi You seem to be using the old version of Lambda (2014-11-11 vs 2015-03-01). Do you perhaps have that configured in your `config` file? It could also be possible that somehow the new models got deleted somehow. Could check to make sure the directory `botocore/data/lambda/2015-03-01` is available in your install directory? If so, it should have a `service-2.json` file in there.

Could you also try setting the correct api version manually like so:

```python
import boto3

l = boto3.client('lambda', api_version='2015-03-31')
```

**Comment by FrancescoRizzi** [comment]
@JordonPhillips I think you were right: must have had some component outdated (although nothing was configured in the ~/.aws/config).

Thank you so much for looking into this and spotting the problem: I think this can be closed now.

For reference, here's an updated session:

I have done a refresh (via pip install -U) since my original report of botocoroe and boto3 (a few days ago, when an error hinted I had a version of either that was not the latest, as some APIs from the 'apigateway' client were not there)

So this configuration works:
botocore 1.4.15
boto3 1.3.1

```
import boto3
from boto3.session import Session
import botocore

print botocore.__version__
1.4.15

session = Session()
client = session.client('lambda')
response = client.update_function_configuration(
   FunctionName='DEV-SampleLambda1,
   Role='[MY_ROLE_ARN]',
   Handler='sample_lambda_1.handler,
   Description='Updated Description',
   Timeout=3,
   MemorySIze=128,
   Runtime='python2.7'
)
```

No errors, and the Lambda is properly updated.

**Comment by sathiyas** [comment]
pip uninstall botocore made the trick - botocore is out of sync with boto3, uninstalling botocore will make boto3 use the one along with it
