### ISSUE TITLE
APIGateway create_resource AccessDeniedException response leads to ValueError: No JSON object could be decoded (from parsers _parse_body_as_json)

### ISSUE THREAD

**Issue by FrancescoRizzi** [boto/botocore#908]
I hit this error, and it seems to come out of the botocore parser when AWS sends me back an AccessDeniedException response.

```
ValueError: No JSON object could be decoded
```

I replicated in an interactive session (below) with `boto3.set_stream_logger('botocore')` turned on just before the call that triggers the error. In AWS, for reference, I do have an API called "MySampleAPI" with just the default root ('/') resource.

I suspect the call to `create_resource` should specify a non-blank `parentId`, but I was expecting either a pre-roundtrip validation error (missing required parentId argument, of sort), or the botocore client to handle the error response as usual (ie: via botocore exception with ['Error']['Message'] and ['Code']).

Using:
Mac OS X El Capitan (10.11.4)
Python 2.7.6
botocore 1.4.15
boto3 1.3.1

```
Python 2.7.6 (v2.7.6:3a1db0d2747e, Nov 10 2013, 00:42:54) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import json
>>> import boto3
>>> from boto3.session import Session
>>> import botocore
>>> 
>>> print botocore.__version__
1.4.15
>>> 
>>> session = Session()
>>> client = session.client('apigateway')
>>> 
>>> apiName = 'MySampleAPI'
>>> 
>>> response = client.get_rest_apis()
>>> apis = {}
>>> for item in response['items']:
...     apis[item['name']]=item
... 
>>> if apiName not in apis:
...     print "COULD NOT FIND {0!s} API".format(apiName)
...     exit()
... 
>>> apiId = apis[apiName]['id']
>>> print "MySampleAPI id: {0!s}".format(apiId)
MySampleAPI id: 5y070qwwac
>>> 
>>> response = client.get_resources(restApiId=apiId)
>>> resources = response['items']
>>> 
>>> print json.dumps(resources, indent=4)
[
    {
        "path": "/", 
        "id": "d4rak8ejjg"
    }
]
>>> 
>>> boto3.set_stream_logger('botocore')
>>> 
>>> response = client.create_resource(restApiId=apiId, parentId='', pathPart='MyResource1')
2016-05-03 10:54:38,530 botocore.hooks [DEBUG] Event before-call.apigateway.CreateResource: calling handler <function add_accept_header at 0x103277320>
2016-05-03 10:54:38,530 botocore.endpoint [DEBUG] Making request for <botocore.model.OperationModel object at 0x103400ed0> (verify_ssl=True) with params: {'body': '{"pathPart": "MyResource1"}', 'url': u'https://apigateway.us-east-1.amazonaws.com/restapis/5y070qwwac/resources/', 'headers': {'Accept': 'application/json', 'User-Agent': 'Boto3/1.3.1 Python/2.7.6 Darwin/15.4.0 Botocore/1.4.15'}, 'query_string': {}, 'url_path': u'/restapis/5y070qwwac/resources/', 'method': u'POST'}
2016-05-03 10:54:38,530 botocore.hooks [DEBUG] Event request-created.apigateway.CreateResource: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x1034e2c90>>
2016-05-03 10:54:38,530 botocore.auth [DEBUG] Calculating signature using v4 auth.
2016-05-03 10:54:38,530 botocore.auth [DEBUG] CanonicalRequest:
POST
/restapis/5y070qwwac/resources/

accept:application/json
host:apigateway.us-east-1.amazonaws.com
x-amz-date:20160503T145438Z

accept;host;x-amz-date
aab480e5d57b5d06260cb56ea112c0dec2d73e6fa6d9784a95540ea1c9ffa5dc
2016-05-03 10:54:38,531 botocore.auth [DEBUG] StringToSign:
AWS4-HMAC-SHA256
20160503T145438Z
20160503/us-east-1/apigateway/aws4_request
9df28a8a19014ca853c7ac8be31b936fca39b0c8ac64df542971615d37be0af0
2016-05-03 10:54:38,531 botocore.auth [DEBUG] Signature:
504ffff396f7bc1b6c23317b2b59791c7deca0882c87e072b3ab6a516fa0de4c
2016-05-03 10:54:38,531 botocore.endpoint [DEBUG] Sending http request: <PreparedRequest [POST]>
2016-05-03 10:54:38,587 botocore.vendored.requests.packages.urllib3.connectionpool [DEBUG] "POST /restapis/5y070qwwac/resources/ HTTP/1.1" 403 130
2016-05-03 10:54:38,588 botocore.parsers [DEBUG] Response headers: {'x-amzn-requestid': 'f57f6492-113e-11e6-bddf-4329754397a3', 'date': 'Tue, 03 May 2016 14:54:38 GMT', 'content-length': '130'}
2016-05-03 10:54:38,588 botocore.parsers [DEBUG] Response body:
<AccessDeniedException>
  <Message>Unable to determine service/operation name to be authorized</Message>
</AccessDeniedException>

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/client.py", line 252, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/client.py", line 531, in _make_api_call
    operation_model, request_dict)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/endpoint.py", line 117, in make_request
    return self._send_request(request_dict, operation_model)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/endpoint.py", line 144, in _send_request
    request, operation_model, attempts)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/endpoint.py", line 203, in _get_response
    parser.parse(response_dict, operation_model.output_shape)),
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/parsers.py", line 209, in parse
    parsed = self._do_error_parse(response, shape)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/parsers.py", line 686, in _do_error_parse
    error = super(RestJSONParser, self)._do_error_parse(response, shape)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/parsers.py", line 541, in _do_error_parse
    body = self._parse_body_as_json(response['body'])
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/parsers.py", line 573, in _parse_body_as_json
    original_parsed = json.loads(body)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 383, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by jamesls** [comment]
Thanks for letting us know.  The issue here is that we're expecting API gateway to always return JSON (even in the error cases) but here it's returning XML, which we don't expect.

I'll follow up with the service team and see what we can do.

**Comment by mxr** [comment]
Just wondering is this still being investigated? I'm also occasionally hitting an exception decoding JSON, during a DynamoDB Query (via PynamoDB). Unfortunately I don't have a local repro nor boto logs, just this stack, so I don't know if it's the exact same issue -

```
Traceback (most recent call last):
  File "/usr/local/lib/service_venv/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/service_venv/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/service_venv/local/lib/python2.7/site-packages/flask_restful/__init__.py", line 430, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/service_venv/local/lib/python2.7/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/service_venv/local/lib/python2.7/site-packages/flask_restful/__init__.py", line 520, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/srv/service/current/app/resources/api.py", line 132, in get
    status=args.status
  File "/srv/service/current/app/resources/api.py", line 245, in redacted
    reverse=pagination.is_desc(),
  File "/usr/local/lib/service_venv/local/lib/python2.7/site-packages/pynamodb/models.py", line 553, in query
    data = cls._get_connection().query(hash_key, **query_kwargs)
  File "/usr/local/lib/service_venv/local/lib/python2.7/site-packages/pynamodb/connection/table.py", line 175, in query
    select=select)
  File "/usr/local/lib/service_venv/local/lib/python2.7/site-packages/pynamodb/connection/base.py", line 892, in query
    return self.dispatch(QUERY, operation_kwargs)
  File "/usr/local/lib/service_venv/local/lib/python2.7/site-packages/pynamodb/connection/base.py", line 221, in dispatch
    data = method(**operation_kwargs)
  File "/usr/local/lib/service_venv/local/lib/python2.7/site-packages/botocore/client.py", line 228, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/service_venv/local/lib/python2.7/site-packages/botocore/client.py", line 481, in _make_api_call
    operation_model, request_dict)
  File "/usr/local/lib/service_venv/local/lib/python2.7/site-packages/botocore/endpoint.py", line 117, in make_request
    return self._send_request(request_dict, operation_model)
  File "/usr/local/lib/service_venv/local/lib/python2.7/site-packages/botocore/endpoint.py", line 144, in _send_request
    request, operation_model, attempts)
  File "/usr/local/lib/service_venv/local/lib/python2.7/site-packages/botocore/endpoint.py", line 203, in _get_response
    parser.parse(response_dict, operation_model.output_shape)),
  File "/usr/local/lib/service_venv/local/lib/python2.7/site-packages/botocore/parsers.py", line 209, in parse
    parsed = self._do_error_parse(response, shape)
  File "/usr/local/lib/service_venv/local/lib/python2.7/site-packages/botocore/parsers.py", line 540, in _do_error_parse
    body = self._parse_body_as_json(response['body'])
  File "/usr/local/lib/service_venv/local/lib/python2.7/site-packages/botocore/parsers.py", line 572, in _parse_body_as_json
    original_parsed = json.loads(body)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by mxr** [comment]
Nevermind, I solved my problem above by updating PynamoDB - newer versions rely less on botocore (I updated to 1.5.2 from 1.4.0)

**Comment by balihoo-gens** [comment]
I hit the same error calling SWF respond_decision_task_completed. If the payload is too large, AWS responds with the plain string `HTTP content length exceeded 1049600 bytes.`, which then raises `ValueError: No JSON object could be decoded` in ```botocore/parsers.py", line 572, in _parse_body_as_json
    original_parsed = json.loads(body)
```

This can obviously be avoided by just sending a smaller payload, but the issue is that botocore is unable to handle the sporadic cases in which AWS does not return json. Potential solutions would be:
 - catch the exception in `_parse_body_as_json` and return it in a `{ "message": ... }` structure
 - catch the exception in `_do_error_parse`and set `error['Error']['Message'] = response['body']`

**Comment by balihoo-gens** [comment]
https://github.com/boto/botocore/pull/1061

**Comment by joguSD** [comment]
Seeing as @balihoo-gens pull request was merged I'm going to close this issue now.
Thanks for the fix!

If anyone is still having this issue please feel free to continue the discussion.
