### ISSUE TITLE
KeyError with "context" key in "botocore/awsrequest.py" line 314 create_request_object

### ISSUE THREAD

**Issue by defila-aws** [boto/botocore#979]
When AWS Lambda updated to the newest version of the AWS SDK on the 30th of June, a bug appears to have been introduced, which caused an existing (testing) Lambda function (created from a blueprint) to error out.

https://github.com/boto/botocore/commit/28b8831f5f8518bef5accf994fc377c58a3569f7

```
'context': KeyError Traceback (most recent call last):

File "/var/task/lambda_function.py", line 189, in lambda_handler post_to_es(es_payload) # post to ES with exponential backoff

File "/var/task/lambda_function.py", line 80, in post_to_es es_ret_str = post_data_to_es(payload, es_region, creds, es_endpoint, '/_bulk')

File "/var/task/lambda_function.py", line 47, in post_data_to_es req = botocore.awsrequest.create_request_object(params)

File "/var/runtime/botocore/awsrequest.py", line 314, in create_request_object request_object.context.update(r['context'])

KeyError: 'context'
```

To work around this issue, within my Lambda Function code, I added the context key:value pair as:

```
params = {'method': method, 'url': proto + host + path, 'region': region, 'headers': {'Host': host}, 'body': payload, 'context': {'unknown': 'values'}}
	req = botocore.awsrequest.create_request_object(params)
```

instead of the prior value:

```
params = {'method': method, 'url': proto + host + path, 'region': region, 'headers': {'Host': host}, 'body': payload}
	req = botocore.awsrequest.create_request_object(params)
```

**Comment by defila-aws** [comment]
The blueprint was updated in Lambda, regarding calling "create_request_object".  Closing issue.
