### ISSUE TITLE
ssm send_command() ThrottlingException for > 50 instance IDs

### ISSUE THREAD

**Issue by tomstockton** [boto/botocore#993]
See code example below - `test.py`
```
from boto3.session import Session

instance_ids = []

print(len(instance_ids))
aws = Session('XXX', 'XXX', region_name='us-east-1')
output = aws.client('ssm').send_command(
    InstanceIds=instance_ids,
    DocumentName='AWS-RunShellScript',
    Parameters={
        "commands":[
            "echo test"
        ],
        "executionTimeout":["3600"]
    }
)
print(output['Command']['CommandId'])
```

Works fine if len(instance_ids) <= '50'

```
$ python3 test.py
50
dbb11bb6-2f7a-44c2-8653-20f42ba0a950
```

But not if len(instance_ids) > '50'

```
$ python3 test.py
51
Traceback (most recent call last):
  File "test.py", line 18, in <module>
    "executionTimeout":["3600"]
  File "/usr/local/lib/python3.4/site-packages/botocore/client.py", line 252, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.4/site-packages/botocore/client.py", line 542, in _make_api_call
    raise ClientError(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ThrottlingException) when calling the SendCommand operation: Rate exceeded
```

Is it possible for me to run against more than 50 instances or do I need to batch up these requests separately?

**Comment by tomstockton** [comment]
RTFM - http://boto3.readthedocs.io/en/latest/reference/services/ssm.html#SSM.Client.send_command

**Comment by OVSS** [comment]
Have you solved this problem? I get into same trouble. How can I fix it?

Thank you.

**Comment by kapilt** [comment]
ideally send to multiple instances via targets/tags as specification instead of individual instance ids, else mini batch and backoff.
