### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by Fale** [boto/botocore#997]
I'm trying to run the tests from my machine but I consistently have some failed tests.

I run tests on Python 2.7.11 with the following command: nosetests-2.7 --with-coverage --cover-erase --cover-package botocore --with-xunit --cover-xml -v tests/unit/ tests/functional/

```
======================================================================
ERROR: test_create_memory_clients_in_loop (tests.functional.leak.test_resource_leaks.TestDoesNotLeakMemory)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/botocore-1.4.42/tests/functional/leak/test_resource_leaks.py", line 56, in test_create_memory_clients_in_loop
    self.cmd('create_multiple_clients', '200', 's3')
  File "/builddir/build/BUILD/botocore-1.4.42/tests/__init__.py", line 151, in cmd
    self.driver.cmd(*args)
  File "/builddir/build/BUILD/botocore-1.4.42/tests/__init__.py", line 249, in cmd
    "Error from command '%s': %s" % (cmd, result))
RuntimeError: Error from command '('create_multiple_clients', '200', 's3')': 

======================================================================
ERROR: test_create_memory_clients_in_loop (tests.functional.leak.test_resource_leaks.TestDoesNotLeakMemory)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/botocore-1.4.42/tests/__init__.py", line 164, in tearDown
    self.driver.stop()
  File "/builddir/build/BUILD/botocore-1.4.42/tests/__init__.py", line 203, in stop
    self.cmd('exit')
  File "/builddir/build/BUILD/botocore-1.4.42/tests/__init__.py", line 245, in cmd
    self.send_cmd(*cmd)
  File "/builddir/build/BUILD/botocore-1.4.42/tests/__init__.py", line 226, in send_cmd
    self._popen.stdin.write(cmd_bytes)
IOError: [Errno 32] Broken pipe

======================================================================
ERROR: test_create_memory_paginators_in_loop (tests.functional.leak.test_resource_leaks.TestDoesNotLeakMemory)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/botocore-1.4.42/tests/functional/leak/test_resource_leaks.py", line 107, in test_create_memory_paginators_in_loop
    self.cmd('create_multiple_paginators', '200', 's3', 'list_objects')
  File "/builddir/build/BUILD/botocore-1.4.42/tests/__init__.py", line 151, in cmd
    self.driver.cmd(*args)
  File "/builddir/build/BUILD/botocore-1.4.42/tests/__init__.py", line 249, in cmd
    "Error from command '%s': %s" % (cmd, result))
RuntimeError: Error from command '('create_multiple_paginators', '200', 's3', 'list_objects')': 

======================================================================
ERROR: test_create_memory_paginators_in_loop (tests.functional.leak.test_resource_leaks.TestDoesNotLeakMemory)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/botocore-1.4.42/tests/__init__.py", line 164, in tearDown
    self.driver.stop()
  File "/builddir/build/BUILD/botocore-1.4.42/tests/__init__.py", line 203, in stop
    self.cmd('exit')
  File "/builddir/build/BUILD/botocore-1.4.42/tests/__init__.py", line 245, in cmd
    self.send_cmd(*cmd)
  File "/builddir/build/BUILD/botocore-1.4.42/tests/__init__.py", line 226, in send_cmd
    self._popen.stdin.write(cmd_bytes)
IOError: [Errno 32] Broken pipe

======================================================================
ERROR: test_create_memory_waiters_in_loop (tests.functional.leak.test_resource_leaks.TestDoesNotLeakMemory)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/botocore-1.4.42/tests/functional/leak/test_resource_leaks.py", line 81, in test_create_memory_waiters_in_loop
    self.cmd('create_multiple_waiters', '200', 's3', 'bucket_exists')
  File "/builddir/build/BUILD/botocore-1.4.42/tests/__init__.py", line 151, in cmd
    self.driver.cmd(*args)
  File "/builddir/build/BUILD/botocore-1.4.42/tests/__init__.py", line 249, in cmd
    "Error from command '%s': %s" % (cmd, result))
RuntimeError: Error from command '('create_multiple_waiters', '200', 's3', 'bucket_exists')': 

======================================================================
ERROR: test_create_memory_waiters_in_loop (tests.functional.leak.test_resource_leaks.TestDoesNotLeakMemory)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/botocore-1.4.42/tests/__init__.py", line 164, in tearDown
    self.driver.stop()
  File "/builddir/build/BUILD/botocore-1.4.42/tests/__init__.py", line 203, in stop
    self.cmd('exit')
  File "/builddir/build/BUILD/botocore-1.4.42/tests/__init__.py", line 245, in cmd
    self.send_cmd(*cmd)
  File "/builddir/build/BUILD/botocore-1.4.42/tests/__init__.py", line 226, in send_cmd
    self._popen.stdin.write(cmd_bytes)
IOError: [Errno 32] Broken pipe

======================================================================
ERROR: test_create_single_client_memory_constant (tests.functional.leak.test_resource_leaks.TestDoesNotLeakMemory)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/botocore-1.4.42/tests/functional/leak/test_resource_leaks.py", line 29, in test_create_single_client_memory_constant
    self.cmd('create_client', 's3')
  File "/builddir/build/BUILD/botocore-1.4.42/tests/__init__.py", line 151, in cmd
    self.driver.cmd(*args)
  File "/builddir/build/BUILD/botocore-1.4.42/tests/__init__.py", line 249, in cmd
    "Error from command '%s': %s" % (cmd, result))
RuntimeError: Error from command '('create_client', 's3')': 

======================================================================
ERROR: test_create_single_client_memory_constant (tests.functional.leak.test_resource_leaks.TestDoesNotLeakMemory)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/botocore-1.4.42/tests/__init__.py", line 164, in tearDown
    self.driver.stop()
  File "/builddir/build/BUILD/botocore-1.4.42/tests/__init__.py", line 203, in stop
    self.cmd('exit')
  File "/builddir/build/BUILD/botocore-1.4.42/tests/__init__.py", line 245, in cmd
    self.send_cmd(*cmd)
  File "/builddir/build/BUILD/botocore-1.4.42/tests/__init__.py", line 226, in send_cmd
    self._popen.stdin.write(cmd_bytes)
IOError: [Errno 32] Broken pipe

======================================================================
ERROR: test_create_single_paginator_memory_constant (tests.functional.leak.test_resource_leaks.TestDoesNotLeakMemory)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/botocore-1.4.42/tests/functional/leak/test_resource_leaks.py", line 94, in test_create_single_paginator_memory_constant
    self.cmd('create_paginator', 's3', 'list_objects')
  File "/builddir/build/BUILD/botocore-1.4.42/tests/__init__.py", line 151, in cmd
    self.driver.cmd(*args)
  File "/builddir/build/BUILD/botocore-1.4.42/tests/__init__.py", line 249, in cmd
    "Error from command '%s': %s" % (cmd, result))
RuntimeError: Error from command '('create_paginator', 's3', 'list_objects')': 

======================================================================
ERROR: test_create_single_paginator_memory_constant (tests.functional.leak.test_resource_leaks.TestDoesNotLeakMemory)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/botocore-1.4.42/tests/__init__.py", line 164, in tearDown
    self.driver.stop()
  File "/builddir/build/BUILD/botocore-1.4.42/tests/__init__.py", line 203, in stop
    self.cmd('exit')
  File "/builddir/build/BUILD/botocore-1.4.42/tests/__init__.py", line 245, in cmd
    self.send_cmd(*cmd)
  File "/builddir/build/BUILD/botocore-1.4.42/tests/__init__.py", line 226, in send_cmd
    self._popen.stdin.write(cmd_bytes)
IOError: [Errno 32] Broken pipe

======================================================================
ERROR: test_create_single_waiter_memory_constant (tests.functional.leak.test_resource_leaks.TestDoesNotLeakMemory)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/botocore-1.4.42/tests/functional/leak/test_resource_leaks.py", line 68, in test_create_single_waiter_memory_constant
    self.cmd('create_waiter', 's3', 'bucket_exists')
  File "/builddir/build/BUILD/botocore-1.4.42/tests/__init__.py", line 151, in cmd
    self.driver.cmd(*args)
  File "/builddir/build/BUILD/botocore-1.4.42/tests/__init__.py", line 249, in cmd
    "Error from command '%s': %s" % (cmd, result))
RuntimeError: Error from command '('create_waiter', 's3', 'bucket_exists')': 

======================================================================
ERROR: test_create_single_waiter_memory_constant (tests.functional.leak.test_resource_leaks.TestDoesNotLeakMemory)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/botocore-1.4.42/tests/__init__.py", line 164, in tearDown
    self.driver.stop()
  File "/builddir/build/BUILD/botocore-1.4.42/tests/__init__.py", line 203, in stop
    self.cmd('exit')
  File "/builddir/build/BUILD/botocore-1.4.42/tests/__init__.py", line 245, in cmd
    self.send_cmd(*cmd)
  File "/builddir/build/BUILD/botocore-1.4.42/tests/__init__.py", line 226, in send_cmd
    self._popen.stdin.write(cmd_bytes)
IOError: [Errno 32] Broken pipe

----------------------------------------------------------------------
XML: /builddir/build/BUILD/botocore-1.4.42/nosetests.xml
----------------------------------------------------------------------
Ran 1848 tests in 163.572s
```

I have similar errors with Python 3.5.1 running tests with the following commands: nosetests-3.5 --with-coverage --cover-erase --cover-package botocore --with-xunit --cover-xml -v tests/unit/ tests/functional/

```
======================================================================
ERROR: test_create_memory_clients_in_loop (tests.functional.leak.test_resource_leaks.TestDoesNotLeakMemory)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/botocore-1.4.42/tests/functional/leak/test_resource_leaks.py", line 56, in test_create_memory_clients_in_loop
    self.cmd('create_multiple_clients', '200', 's3')
  File "/builddir/build/BUILD/botocore-1.4.42/tests/__init__.py", line 151, in cmd
    self.driver.cmd(*args)
  File "/builddir/build/BUILD/botocore-1.4.42/tests/__init__.py", line 249, in cmd
    "Error from command '%s': %s" % (cmd, result))
RuntimeError: Error from command '('create_multiple_clients', '200', 's3')': b''

======================================================================
ERROR: test_create_memory_clients_in_loop (tests.functional.leak.test_resource_leaks.TestDoesNotLeakMemory)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/botocore-1.4.42/tests/__init__.py", line 164, in tearDown
    self.driver.stop()
  File "/builddir/build/BUILD/botocore-1.4.42/tests/__init__.py", line 203, in stop
    self.cmd('exit')
  File "/builddir/build/BUILD/botocore-1.4.42/tests/__init__.py", line 245, in cmd
    self.send_cmd(*cmd)
  File "/builddir/build/BUILD/botocore-1.4.42/tests/__init__.py", line 227, in send_cmd
    self._popen.stdin.flush()
BrokenPipeError: [Errno 32] Broken pipe

======================================================================
ERROR: test_create_memory_paginators_in_loop (tests.functional.leak.test_resource_leaks.TestDoesNotLeakMemory)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/botocore-1.4.42/tests/functional/leak/test_resource_leaks.py", line 107, in test_create_memory_paginators_in_loop
    self.cmd('create_multiple_paginators', '200', 's3', 'list_objects')
  File "/builddir/build/BUILD/botocore-1.4.42/tests/__init__.py", line 151, in cmd
    self.driver.cmd(*args)
  File "/builddir/build/BUILD/botocore-1.4.42/tests/__init__.py", line 249, in cmd
    "Error from command '%s': %s" % (cmd, result))
RuntimeError: Error from command '('create_multiple_paginators', '200', 's3', 'list_objects')': b''

======================================================================
ERROR: test_create_memory_paginators_in_loop (tests.functional.leak.test_resource_leaks.TestDoesNotLeakMemory)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/botocore-1.4.42/tests/__init__.py", line 164, in tearDown
    self.driver.stop()
  File "/builddir/build/BUILD/botocore-1.4.42/tests/__init__.py", line 203, in stop
    self.cmd('exit')
  File "/builddir/build/BUILD/botocore-1.4.42/tests/__init__.py", line 245, in cmd
    self.send_cmd(*cmd)
  File "/builddir/build/BUILD/botocore-1.4.42/tests/__init__.py", line 227, in send_cmd
    self._popen.stdin.flush()
BrokenPipeError: [Errno 32] Broken pipe

======================================================================
ERROR: test_create_memory_waiters_in_loop (tests.functional.leak.test_resource_leaks.TestDoesNotLeakMemory)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/botocore-1.4.42/tests/functional/leak/test_resource_leaks.py", line 81, in test_create_memory_waiters_in_loop
    self.cmd('create_multiple_waiters', '200', 's3', 'bucket_exists')
  File "/builddir/build/BUILD/botocore-1.4.42/tests/__init__.py", line 151, in cmd
    self.driver.cmd(*args)
  File "/builddir/build/BUILD/botocore-1.4.42/tests/__init__.py", line 249, in cmd
    "Error from command '%s': %s" % (cmd, result))
RuntimeError: Error from command '('create_multiple_waiters', '200', 's3', 'bucket_exists')': b''

======================================================================
ERROR: test_create_memory_waiters_in_loop (tests.functional.leak.test_resource_leaks.TestDoesNotLeakMemory)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/botocore-1.4.42/tests/__init__.py", line 164, in tearDown
    self.driver.stop()
  File "/builddir/build/BUILD/botocore-1.4.42/tests/__init__.py", line 203, in stop
    self.cmd('exit')
  File "/builddir/build/BUILD/botocore-1.4.42/tests/__init__.py", line 245, in cmd
    self.send_cmd(*cmd)
  File "/builddir/build/BUILD/botocore-1.4.42/tests/__init__.py", line 227, in send_cmd
    self._popen.stdin.flush()
BrokenPipeError: [Errno 32] Broken pipe

======================================================================
ERROR: test_create_single_client_memory_constant (tests.functional.leak.test_resource_leaks.TestDoesNotLeakMemory)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/botocore-1.4.42/tests/functional/leak/test_resource_leaks.py", line 29, in test_create_single_client_memory_constant
    self.cmd('create_client', 's3')
  File "/builddir/build/BUILD/botocore-1.4.42/tests/__init__.py", line 151, in cmd
    self.driver.cmd(*args)
  File "/builddir/build/BUILD/botocore-1.4.42/tests/__init__.py", line 249, in cmd
    "Error from command '%s': %s" % (cmd, result))
RuntimeError: Error from command '('create_client', 's3')': b''

======================================================================
ERROR: test_create_single_client_memory_constant (tests.functional.leak.test_resource_leaks.TestDoesNotLeakMemory)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/botocore-1.4.42/tests/__init__.py", line 164, in tearDown
    self.driver.stop()
  File "/builddir/build/BUILD/botocore-1.4.42/tests/__init__.py", line 203, in stop
    self.cmd('exit')
  File "/builddir/build/BUILD/botocore-1.4.42/tests/__init__.py", line 245, in cmd
    self.send_cmd(*cmd)
  File "/builddir/build/BUILD/botocore-1.4.42/tests/__init__.py", line 227, in send_cmd
    self._popen.stdin.flush()
BrokenPipeError: [Errno 32] Broken pipe

======================================================================
ERROR: test_create_single_paginator_memory_constant (tests.functional.leak.test_resource_leaks.TestDoesNotLeakMemory)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/botocore-1.4.42/tests/functional/leak/test_resource_leaks.py", line 94, in test_create_single_paginator_memory_constant
    self.cmd('create_paginator', 's3', 'list_objects')
  File "/builddir/build/BUILD/botocore-1.4.42/tests/__init__.py", line 151, in cmd
    self.driver.cmd(*args)
  File "/builddir/build/BUILD/botocore-1.4.42/tests/__init__.py", line 249, in cmd
    "Error from command '%s': %s" % (cmd, result))
RuntimeError: Error from command '('create_paginator', 's3', 'list_objects')': b''

======================================================================
ERROR: test_create_single_paginator_memory_constant (tests.functional.leak.test_resource_leaks.TestDoesNotLeakMemory)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/botocore-1.4.42/tests/__init__.py", line 164, in tearDown
    self.driver.stop()
  File "/builddir/build/BUILD/botocore-1.4.42/tests/__init__.py", line 203, in stop
    self.cmd('exit')
  File "/builddir/build/BUILD/botocore-1.4.42/tests/__init__.py", line 245, in cmd
    self.send_cmd(*cmd)
  File "/builddir/build/BUILD/botocore-1.4.42/tests/__init__.py", line 227, in send_cmd
    self._popen.stdin.flush()
BrokenPipeError: [Errno 32] Broken pipe

======================================================================
ERROR: test_create_single_waiter_memory_constant (tests.functional.leak.test_resource_leaks.TestDoesNotLeakMemory)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/botocore-1.4.42/tests/functional/leak/test_resource_leaks.py", line 68, in test_create_single_waiter_memory_constant
    self.cmd('create_waiter', 's3', 'bucket_exists')
  File "/builddir/build/BUILD/botocore-1.4.42/tests/__init__.py", line 151, in cmd
    self.driver.cmd(*args)
  File "/builddir/build/BUILD/botocore-1.4.42/tests/__init__.py", line 249, in cmd
    "Error from command '%s': %s" % (cmd, result))
RuntimeError: Error from command '('create_waiter', 's3', 'bucket_exists')': b''

======================================================================
ERROR: test_create_single_waiter_memory_constant (tests.functional.leak.test_resource_leaks.TestDoesNotLeakMemory)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/botocore-1.4.42/tests/__init__.py", line 164, in tearDown
    self.driver.stop()
  File "/builddir/build/BUILD/botocore-1.4.42/tests/__init__.py", line 203, in stop
    self.cmd('exit')
  File "/builddir/build/BUILD/botocore-1.4.42/tests/__init__.py", line 245, in cmd
    self.send_cmd(*cmd)
  File "/builddir/build/BUILD/botocore-1.4.42/tests/__init__.py", line 227, in send_cmd
    self._popen.stdin.flush()
BrokenPipeError: [Errno 32] Broken pipe

----------------------------------------------------------------------
XML: /builddir/build/BUILD/botocore-1.4.42/nosetests.xml
----------------------------------------------------------------------
Ran 1850 tests in 148.494s
```

**Comment by jamesls** [comment]
Are you running these tests interactively in your terminal?  Or through some CI system?

These tests are passing on travis (https://travis-ci.org/boto/botocore/jobs/149648456#L2860) and jenkins, as well as locally for me, so I'm not sure what would be causing these issues for you.

Is there anything else you can share about your environment?

**Comment by Fale** [comment]
Hi,
It's actually a [koji build](http://koji.fedoraproject.org/koji/taskinfo?taskID=15140250).
I have a couple of logs that describe the [environment](https://kojipkgs.fedoraproject.org//work/tasks/250/15140250/root.log) and [all operations](https://kojipkgs.fedoraproject.org//work/tasks/250/15140250/build.log) during the build/test time

**Comment by kyleknap** [comment]
We will have to do more researching. It looks like all of the memory leak tests are failing because the command runner, ``cmd-runner`` is not able to import ``botocore.session``. More deep diving is needed to figure out why the ``cmd-runner`` is unable to import ``botocore.session``.

**Comment by jamesls** [comment]
Took a while to figure out how @kyleknap knew the failure was due to failing to import `botocore.session`.  It's from the linked logs [here](https://kojipkgs.fedoraproject.org//work/tasks/250/15140250/build.log):

```
test_create_memory_clients_in_loop (tests.functional.leak.test_resource_leaks.TestDoesNotLeakMemory) ... Traceback (most recent call last):
  File "/builddir/build/BUILD/botocore-1.4.42/tests/cmd-runner", line 72, in <module>
    import botocore.session
ImportError: No module named botocore.session
ERROR
```

This gives me a little more to go on.  Let me see what I can find.

**Comment by JordonPhillips** [comment]
@Fale is this still an issue for you?

**Comment by JordonPhillips** [comment]
Based on the fact that you've got successful builds, it looks like you've found a workaround. Closing out the issue here, but feel free to re-open and ping me if you're still having issues.
